### ISSUE TITLE
Fix CI on Python 3.

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/planemo#1005]
Looks like the CI tests are currently passing on Python 2 and not 3. I don't know how that happened. Some broken training material generation tests I think.

**Comment by bernt-matthias** [comment]
Seems that the tutorial tests fail because:

```
'Error cloning repository: Command \'[\'hg\', \'clone\', \'-r\', \'13\', \'https://toolshed.g2.bx.psu.edu/repos/bgruening/text_processing\', \'/tmp/tmpfqq9xqd3/shed_tools/toolshed.g2.bx.psu.edu/repos/bgruening/text_processing/0a8c6b61f0f4/text_processing\']\' returned non-zero exit status 1.

Output was:
Traceback (most recent call last):
  File "/tmp/planemo-test-workspace/gx_venv/bin/hg", line 43, in <module>
    dispatch.run()\n  File "/opt/hostedtoolcache/Python/3.6.11/x64/lib/python3.6/importlib/util.py", line 233, in __getattribute__
    self.__spec__.loader.exec_module(self)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/planemo-test-workspace/gx_venv/lib/python3.6/site-packages/mercurial/dispatch.py", line 22, in <module>
    from .i18n import _
  File "/opt/hostedtoolcache/Python/3.6.11/x64/lib/python3.6/importlib/util.py", line 233, in __getattribute__
    self.__spec__.loader.exec_module(self)
  File "/tmp/planemo-test-workspace/gx_venv/lib/python3.6/site-packages/mercurial/i18n.py", line 15, in <module>
    from .pycompat import getattr
ImportError: cannot import name \'getattr\',
```

Still, I don't understand the problem.

**Comment by jmchilton** [comment]
Well this error seems to happen on Github actions and Travis, on Python 3.6 and 3.7, under nose and pytest 😆 - how this is a Planemo thing and not a Galaxy thing I have no clue.

**Comment by jmchilton** [comment]
And I've now also tried mercurial 5.3.2, 5.4, and 5.4.2 😭.

**Comment by mvdbeek** [comment]
I've spent a day on this as well to no avail -- the only thing I didn't try was not using gunicorn, I'll give that a shot.

**Comment by jmchilton** [comment]
I have some important gunicorn fixes in that branch I don't want to lose but might be worth just adding an option to force paste and see if it is something gunicorn is doing to the environment. I will also try Python 3.5 - that is a good idea - hopefully all the dependencies work. 

Thanks for the ideas both of you - I was reaching the end of the ones I could come up.

**Comment by mvdbeek** [comment]
I did try paste here: acb8267507dd566f95c0d69c5882310d8ce35d56-- no luck :(

**Comment by jmchilton** [comment]
Maybe we need to pin an older virtualenv for Planemo

**Comment by mvdbeek** [comment]
> The `hg` code uses a special importer for py2.x and py >=3.6 https://www.mercurial-scm.org/repo/hg/file/tip/hg#l29 which raises the error. Would be interesting to check if py3.5 works.

https://fossies.org/linux/mercurial/hgdemandimport/__init__.py -- seems like we could set the `HGDEMANDIMPORT` to `disable` to try the regular importer ?

**Comment by mvdbeek** [comment]
OK, this looks slightliy better with `HGDEMANDIMPORT=false`:
```
Traceback (most recent call last):\n  File "/Users/mvandenb/src/galaxy/.venv/bin/hg", line 35, in <module>\n    from mercurial import dispatch\n  File "/Users/mvandenb/src/galaxy/.venv/lib/python3.8/site-packages/mercurial/dispatch.py", line 22, in <module>\n    from .i18n import _\n  File "/Users/mvandenb/src/galaxy/.venv/lib/python3.8/site-packages/mercurial/i18n.py", line 15, in <module>\n    from .pycompat import getattr\n  File "/Users/mvandenb/src/galaxy/.venv/lib/python3.8/site-packages/mercurial/pycompat.py", line 133, in <module>\n    stdin = sys.stdin.buffer\nAttributeError: \'NoneType\' object has no attribute \'buffer\'\n', 'id': '54f2a3a23292eb07', 'includes_datatypes': False, 'installed_changeset_revision': '0a8c6b61f0f4', 'name': 'text_processing', 'owner': 'bgruening', 'status': 'Error', 'tool_shed': 'toolshed.g2.bx.psu.edu', 'tool_shed_status': None, 'uninstalled': False, 'url': '/api/tool_shed_repositories/54f2a3a23292eb07'
```
that's a lead at least.

**Comment by mvdbeek** [comment]
That's with https://github.com/mvdbeek/galaxy/commit/26d20f7b688b36532455083a6cf6c6cef0ce45f3

**Comment by mvdbeek** [comment]
Alright, with https://github.com/mvdbeek/galaxy/commit/81e619c086b190847e1297d8724d475f93c2a4b9 `pytest -s  tests/test_training_tutorial.py -k get_hands_on_boxes_from_local_galaxy` passes!

**Comment by jmchilton** [comment]
I think at this point test_shed_serve might still be broken - something odd going on there but things are green and I'm dropping Python 2 support so I'm going to close this.
