### ISSUE TITLE
planemo run fails with "Provided API key is not valid."

### ISSUE THREAD

**Issue by simonbray** [galaxyproject/planemo#1071]
I am just testing with this workflow: https://github.com/usegalaxy-eu/workflow-testing/tree/master/example1

Running `planemo run wf3-shed-tools.ga wf3-shed-tools-job.yml --galaxy_url https://usegalaxy.eu/ --galaxy_user_key APIKEY --engine external_galaxy` gives:

```
bioblend ERROR: GET: error 403: b'{"err_msg": "Provided API key is not valid.", "err_code": 403001}', 0 attempts left
Traceback (most recent call last):
  File "/home/simon/Repos/.planemo_gh/bin/planemo", line 8, in <module>
    sys.exit(planemo())
  File "/home/simon/Repos/.planemo_gh/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/simon/Repos/.planemo_gh/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/simon/Repos/.planemo_gh/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/simon/Repos/.planemo_gh/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/simon/Repos/.planemo_gh/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/simon/Repos/.planemo_gh/lib/python3.7/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/simon/Repos/.planemo_gh/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/simon/Repos/.planemo_gh/lib/python3.7/site-packages/planemo/cli.py", line 98, in handle_blended_options
    return f(*args, **kwds)
  File "/home/simon/Repos/.planemo_gh/lib/python3.7/site-packages/planemo/commands/cmd_run.py", line 41, in cli
    run_result = engine.run(path, job_path)
  File "/home/simon/Repos/.planemo_gh/lib/python3.7/site-packages/planemo/engine/interface.py", line 60, in run
    run_response = self._run(runnable, job_path)
  File "/home/simon/Repos/.planemo_gh/lib/python3.7/site-packages/planemo/engine/galaxy.py", line 35, in _run
    with self.ensure_runnables_served([runnable]) as config:
  File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/simon/Repos/.planemo_gh/lib/python3.7/site-packages/planemo/engine/galaxy.py", line 131, in ensure_runnables_served
    config.install_workflows()
  File "/home/simon/Repos/.planemo_gh/lib/python3.7/site-packages/planemo/galaxy/config.py", line 761, in install_workflows
    self._install_workflow(runnable)
  File "/home/simon/Repos/.planemo_gh/lib/python3.7/site-packages/planemo/galaxy/config.py", line 770, in _install_workflow
    self._kwds.get("install_repository_dependencies", True))
  File "/home/simon/Repos/.planemo_gh/lib/python3.7/site-packages/planemo/galaxy/workflows.py", line 51, in install_shed_repos
    default_install_repository_dependencies=install_repository_dependencies)
  File "/home/simon/Repos/.planemo_gh/lib/python3.7/site-packages/ephemeris/shed_tools.py", line 161, in install_repositories
    filtered_repos = self.filter_installed_repos(repository_list)
  File "/home/simon/Repos/.planemo_gh/lib/python3.7/site-packages/ephemeris/shed_tools.py", line 96, in filter_installed_repos
    installed_repos = flatten_repo_info(self.installed_repositories())
  File "/home/simon/Repos/.planemo_gh/lib/python3.7/site-packages/ephemeris/shed_tools.py", line 85, in installed_repositories
    get_all_tools=True
  File "/home/simon/Repos/.planemo_gh/lib/python3.7/site-packages/ephemeris/get_tool_list_from_galaxy.py", line 141, in tool_list
    repo_list = self.repository_list
  File "/home/simon/Repos/.planemo_gh/lib/python3.7/site-packages/ephemeris/get_tool_list_from_galaxy.py", line 102, in repository_list
    walk_tools(self.toolbox, record_repo)
  File "/home/simon/Repos/.planemo_gh/lib/python3.7/site-packages/ephemeris/get_tool_list_from_galaxy.py", line 78, in toolbox
    return get_tool_panel(self.gi)
  File "/home/simon/Repos/.planemo_gh/lib/python3.7/site-packages/ephemeris/get_tool_list_from_galaxy.py", line 19, in get_tool_panel
    return tool_client.get_tool_panel()
  File "/home/simon/Repos/.planemo_gh/lib/python3.7/site-packages/bioblend/galaxy/tools/__init__.py", line 60, in get_tool_panel
    return self._raw_get_tool(in_panel=True)
  File "/home/simon/Repos/.planemo_gh/lib/python3.7/site-packages/bioblend/galaxy/tools/__init__.py", line 66, in _raw_get_tool
    return self._get(params=params)
  File "/home/simon/Repos/.planemo_gh/lib/python3.7/site-packages/bioblend/galaxy/client.py", line 150, in _get
    status_code=r.status_code)
bioblend.ConnectionError: GET: error 403: b'{"err_msg": "Provided API key is not valid.", "err_code": 403001}', 0 attempts left: {"err_msg": "Provided API key is not valid.", "err_code": 403001}

```

**Comment by simonbray** [comment]
Solution: add the `--no_shed_install` flag.

```
planemo run wf3-shed-tools.ga wf3-shed-tools-job.yml --galaxy_url https://usegalaxy.eu/ --galaxy_user_key APIKEY --engine external_galaxy --no_shed_install
```
