### ISSUE TITLE
Planemo failing on IUC tool tests

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/planemo#1085]
https://github.com/galaxyproject/tools-iuc/pull/3212/checks?check_run_id=1172370699

```
Run planemo ci_find_repos --changed_in_commit_range HEAD~.. --exclude packages --exclude deprecated --exclude_from .tt_skip --output changed_repositories.list
galaxy.util ERROR: Error parsing file /home/runner/work/tools-iuc/tools-iuc/tools/mothur/chimera.check.xml
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/galaxy/util/__init__.py", line 237, in parse_xml
    tree = etree.parse(fname, parser=parser)
  File "src/lxml/etree.pyx", line 3521, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1859, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1885, in lxml.etree._parseDocumentFromURL
  File "src/lxml/parser.pxi", line 1789, in lxml.etree._parseDocFromFile
  File "src/lxml/parser.pxi", line 1177, in lxml.etree._BaseParser._parseDocFromFile
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
  File "/home/runner/work/tools-iuc/tools-iuc/tools/mothur/chimera.check.xml", line 70
lxml.etree.XMLSyntaxError: attributes construct error, line 70, column 86
Error loading tool with path /home/runner/work/tools-iuc/tools-iuc/tools/mothur/chimera.check.xml
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/galaxy/tool_util/loader_directory.py", line 110, in _load_tools_from_path
    tool_element = loader_func(possible_tool_file)
  File "/home/runner/work/tools-iuc/tools-iuc/tools/mothur/chimera.check.xml", line 70
lxml.etree.XMLSyntaxError: attributes construct error, line 70, column 86
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/planemo/shed/__init__.py", line 957, in _build_raw_repo_objects
    config = shed_repo_config(ctx, raw_dir, name=name)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/planemo/shed/__init__.py", line 441, in shed_repo_config
    _expand_raw_config(ctx, config, path, name=name)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/planemo/shed/__init__.py", line 568, in _expand_raw_config
    repos = _build_auto_tool_repos(ctx, path, config, auto_tool_repos)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/planemo/shed/__init__.py", line 617, in _build_auto_tool_repos
    repository_config = _build_repository(tool_path, tool_source)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/planemo/shed/__init__.py", line 592, in _build_repository
    tool_id = tool_source.parse_id().lower()
AttributeError: 'object' object has no attribute 'parse_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.9/x64/bin/planemo", line 8, in <module>
    sys.exit(planemo())
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/planemo/cli.py", line 98, in handle_blended_options
    return f(*args, **kwds)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/planemo/commands/cmd_ci_find_repos.py", line 24, in cli
    repos = find_raw_repositories(ctx, paths, **kwds)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/planemo/shed/__init__.py", line 754, in find_raw_repositories
    raw_repo_objects.extend(_find_raw_repositories(ctx, path, **kwds))
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/planemo/shed/__init__.py", line 940, in _find_raw_repositories
    return _build_raw_repo_objects(ctx, raw_dirs, **kwds_copy)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/planemo/shed/__init__.py", line 961, in _build_raw_repo_objects
    _handle_realization_error(exception, **kwds)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/planemo/shed/__init__.py", line 1349, in _handle_realization_error
    raise exception
RuntimeError: Problem parsing file .shed.yml in directory /home/runner/work/tools-iuc/tools-iuc/tools/mothur, skipping repository. Message: ['object' object has no attribute 'parse_id'].
Error: Process completed with exit code 1.
```

Also the releases on github (0.62.1) and pypi (0.72) are out of sync.

**Comment by mvdbeek** [comment]
I guess we've solved this in the meantime
