### ISSUE TITLE
Workflow testing on external galaxy fails with 500 Internal server error

### ISSUE THREAD

**Issue by jancrichter** [galaxyproject/planemo#1143]
I am running workflow tests on an external Galaxy with the following command

```
 planemo --verbose \
         test --engine external_galaxy \
              --galaxy_user_key $GLX_DEV_INSTALL \
              --galaxy_admin_key $GLX_DEV_INSTALL \
              --test_output test.html \
              --no_shed_install \
              --galaxy_url $GALAXY_BASEURL \
              gxid://workflows/${WORKFLOW_ID}?runnable_path=${CI_PROJECT_DIR}/${WORKFLOW}
```

the workflow is invoked and executed successfully but the test fails with the following error message.

```
Failed to execute Galaxy activity, throwing ErrorRunResponse
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/planemo/galaxy/activity.py", line 48, in execute
    return _execute(ctx, config, runnable, job_path, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/planemo/galaxy/activity.py", line 219, in _execute
    run_response.collect_outputs(ctx, output_directory)
  File "/usr/local/lib/python3.6/dist-packages/planemo/galaxy/activity.py", line 358, in collect_outputs
    dataset_dict = get_dataset(dataset)
  File "/usr/local/lib/python3.6/dist-packages/planemo/galaxy/activity.py", line 337, in get_dataset
    destination = self.download_output_to(dataset_details, output_directory, filename=filename)
  File "/usr/local/lib/python3.6/dist-packages/planemo/galaxy/activity.py", line 430, in download_output_to
    filename=filename,
  File "/usr/local/lib/python3.6/dist-packages/planemo/galaxy/activity.py", line 443, in _history_content_download
    r.raise_for_status()
  File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: BASEURL/api/histories/5eaf6075747779e4/contents/f811d48e90c6cbe4/display
Test case [TestCase (Test outline for ts_tool_test.ga) for runnable (Runnable(uri='gxid://workflows/3af9fbe9a5f5994b?runnable_path=/opt/mount/workflows/test/ts_tool_test/ts_tool_test.ga', type=<RunnableType.galaxy_workflow: 3>)) with job ({'input_file': {'class': 'File', 'path': 'test-data/input_file.tabular'}}) and expected outputs ({'output_file': {'class': 'File', 'path': 'test-data/output_file.tabular'}}) in directory (/opt/mount/workflows/test/ts_tool_test) with id (0)] resulted in run response [Run failed with message [500 Server Error: Internal Server Error for url: BASEURL/api/histories/5eaf6075747779e4/contents/f811d48e90c6cbe4/display]]
engine.test returning [<planemo.test.results.StructuredData object at 0x7f73b815cf98>]
```

I replaced the actual Galaxy URL with BASEURL in this. 

The URL to retrieve the dataset works fine in a browser with an authenticated Galaxy session, as well as using curl from the command line with the authentication cookie from the browser session.

Planemo version is 0.74.1, running against a Galaxy 21.01

**Comment by mvdbeek** [comment]
Can you look up the exception on the Galaxy server ?

**Comment by jancrichter** [comment]
Thanks for reminding me of those logs. This is from a rerun I did just now

```
galaxy.webapps.galaxy.api.datasets ERROR 2021-02-24 13:04:42,977 [p:41176,w:3,m:0] [uWSGIWorker3Core0] Error getting display data for dataset (e6693f4d1a4d9f91) from history (e9859c1e537d1ced)
Traceback (most recent call last):
  File "lib/galaxy/webapps/galaxy/api/datasets.py", line 441, in display
    hda = self.hda_manager.get_accessible(decoded_content_id, trans.user)
  File "lib/galaxy/managers/secured.py", line 33, in get_accessible
    return self.error_unless_accessible(item, user, **kwargs)
  File "lib/galaxy/managers/secured.py", line 43, in error_unless_accessible
    raise exceptions.ItemAccessibilityException("%s is not accessible by user" % (self.model_class.__name__))
galaxy.exceptions.ItemAccessibilityException: HistoryDatasetAssociation is not accessible by user
10.10.58.115 - - [24/Feb/2021:13:04:42 +0200] "GET /api/histories/e9859c1e537d1ced/contents/e6693f4d1a4d9f91/display HTTP/1.1" 500 - "-" "python-requests/2.25.1"
```

**Comment by mvdbeek** [comment]
Thank, I see we're not passing in the user's API key to that request.

**Comment by mvdbeek** [comment]
Although, the error in the Galaxy log is a permission error, while the error further up is an internal server error. Can you search in Galaxy's logs for f811d48e90c6cbe4, which should be the dataset that couldn't be downloaded and that led to the exception ?

**Comment by mvdbeek** [comment]
Nevermind, I see this is a 500 error that should actually be a 400 error, that's a Galaxy bug.

**Comment by jancrichter** [comment]
This is all I can find for that ID

```
[pid: 41168|app: 0|req: 6328/25279] 10.10.58.115 () {38 vars in 629 bytes} [Wed Feb 24 12:36:13 2021] GET /api/histories/5eaf6075747779e4/contents/f811d48e90c6cbe4?key=3061198d116e2a4ee5fcffac63263b14 => generated 366327 bytes in 127 msecs (HTTP/1.1 200) 3 headers in 139 bytes (2 switches on core 2)
galaxy.webapps.galaxy.api.datasets ERROR 2021-02-24 12:36:13,772 [p:41176,w:3,m:0] [uWSGIWorker3Core2] Error getting display data for dataset (f811d48e90c6cbe4) from history (5eaf6075747779e4)
Traceback (most recent call last):
  File "lib/galaxy/webapps/galaxy/api/datasets.py", line 441, in display
    hda = self.hda_manager.get_accessible(decoded_content_id, trans.user)
  File "lib/galaxy/managers/secured.py", line 33, in get_accessible
    return self.error_unless_accessible(item, user, **kwargs)
  File "lib/galaxy/managers/secured.py", line 43, in error_unless_accessible
    raise exceptions.ItemAccessibilityException("%s is not accessible by user" % (self.model_class.__name__))
galaxy.exceptions.ItemAccessibilityException: HistoryDatasetAssociation is not accessible by user
10.10.58.115 - - [24/Feb/2021:12:36:13 +0200] "GET /api/histories/5eaf6075747779e4/contents/f811d48e90c6cbe4/display HTTP/1.1" 500 - "-" "python-requests/2.25.1"
[pid: 41176|app: 0|req: 6323/25280] 10.10.58.115 () {38 vars in 572 bytes} [Wed Feb 24 12:36:13 2021] GET /api/histories/5eaf6075747779e4/contents/f811d48e90c6cbe4/display => generated 91 bytes in 23 msecs (HTTP/1.1 500) 3 headers in 158 bytes (1 switches on core 2)

```

**Comment by jancrichter** [comment]
Confirmed working for my use-case.

Thanks for the quick fix and release!

**Comment by mvdbeek** [comment]
You're welcome, thank for the report!
