### ISSUE TITLE
ImportError: cannot import name 'outputs_normalized' from 'gxformat2.normalize' 

### ISSUE THREAD

**Issue by martenson** [galaxyproject/planemo#1147]
May be fixed by https://github.com/galaxyproject/planemo/pull/1145

```
Run planemo merge_test_reports json_output/*.json tool_test_output.json
  planemo merge_test_reports json_output/*.json tool_test_output.json
  shell: /bin/bash -e {0}
  env:
    GALAXY_REPO: https://github.com/galaxyproject/galaxy
    GALAXY_RELEASE: release_20.09
    MAX_CHUNKS: 4
    pythonLocation: /opt/hostedtoolcache/Python/3.7.10/x64
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.10/x64/bin/planemo", line 5, in <module>
    from planemo.cli import planemo
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/planemo/cli.py", line 11, in <module>
    from planemo.galaxy import profiles
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/planemo/galaxy/__init__.py", line 5, in <module>
    from .config import galaxy_config
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/planemo/galaxy/config.py", line 27, in <module>
    from planemo.galaxy.workflows import remote_runnable_to_workflow_id
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/planemo/galaxy/workflows.py", line 13, in <module>
    from gxformat2.normalize import inputs_normalized, outputs_normalized
ImportError: cannot import name 'outputs_normalized' from 'gxformat2.normalize' (/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/gxformat2/normalize.py)
Error: Process completed with exit code 1.
```

**Comment by fubar2** [comment]
This in Travis CI fail logs - ?related?:
```raceback (most recent call last):

  File "/tmp/tmp.98CzLscKCv/.venv/bin/planemo", line 5, in <module>

    from planemo.cli import planemo

  File "/tmp/tmp.98CzLscKCv/.venv/lib/python3.7/site-packages/planemo/cli.py", line 11, in <module>

    from planemo.galaxy import profiles

  File "/tmp/tmp.98CzLscKCv/.venv/lib/python3.7/site-packages/planemo/galaxy/__init__.py", line 5, in <module>

    from .config import galaxy_config

  File "/tmp/tmp.98CzLscKCv/.venv/lib/python3.7/site-packages/planemo/galaxy/config.py", line 28, in <module>

    from planemo.galaxy.workflows import remote_runnable_to_workflow_id

  File "/tmp/tmp.98CzLscKCv/.venv/lib/python3.7/site-packages/planemo/galaxy/workflows.py", line 13, in <module>

    from gxformat2.normalize import inputs_normalized, outputs_normalized

ImportError: cannot import name 'outputs_normalized' from 'gxformat2.normalize' (/tmp/tmp.98CzLscKCv/.venv/lib/python3.7/site-packages/gxformat2/normalize.py)

Makefile:86: recipe for target 'gxwf-test-test' failed

make: *** [gxwf-test-test] Error 1

ERROR: InvocationError for command /usr/bin/make setup-venv gxwf-test-test (exited with code 2)```

**Comment by fubar2** [comment]
Could  #1078 be related? Same complaint about importing the same name...

**Comment by mvdbeek** [comment]
Should be fixed by https://github.com/galaxyproject/planemo/pull/1145, which is release with 0.74.3. Should be a duplicate, yes

**Comment by fubar2** [comment]
Thanks @mvdbeek !
