### ISSUE TITLE
`planemo shed_serve --shed_target testtoolshed` in a folder without `.shed.yml` gives unhelpful errors.

### ISSUE THREAD

**Issue by marehr** [galaxyproject/planemo#1192]
I wanted to start a galaxy instance where I can install tools from the testtoolshed, but I haven't found an option for `planemo --serve` to change the toolshed. After some `planemo --help` reading I thought I just could use `planemo shed_serve --shed_target testtoolshed` for that.

My use case: Make my self written tools accessible in galaxy AND install more tools from the testtoolshed.

But that gave me an error (`planemo serve` was working in the same folder)

```
> planemo shed_serve --shed_target testtoolshed

Traceback (most recent call last):
  File "/home/marehr/develope/fastq2fasta-example-galaxy/workflow-build/planemo-venv/bin/planemo", line 8, in <module>
    sys.exit(planemo())
  File "/home/marehr/develope/fastq2fasta-example-galaxy/workflow-build/planemo-venv/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/marehr/develope/fastq2fasta-example-galaxy/workflow-build/planemo-venv/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/marehr/develope/fastq2fasta-example-galaxy/workflow-build/planemo-venv/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/marehr/develope/fastq2fasta-example-galaxy/workflow-build/planemo-venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/marehr/develope/fastq2fasta-example-galaxy/workflow-build/planemo-venv/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/marehr/develope/fastq2fasta-example-galaxy/workflow-build/planemo-venv/lib/python3.9/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/marehr/develope/fastq2fasta-example-galaxy/workflow-build/planemo-venv/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/marehr/develope/fastq2fasta-example-galaxy/workflow-build/planemo-venv/lib/python3.9/site-packages/planemo/cli.py", line 98, in handle_blended_options
    return f(*args, **kwds)
  File "/home/marehr/develope/fastq2fasta-example-galaxy/workflow-build/planemo-venv/lib/python3.9/site-packages/planemo/commands/cmd_shed_serve.py", line 31, in cli
    install_args_list = shed.install_arg_lists(ctx, paths, **kwds)
  File "/home/marehr/develope/fastq2fasta-example-galaxy/workflow-build/planemo-venv/lib/python3.9/site-packages/planemo/shed/__init__.py", line 238, in install_arg_lists
    exit_code = for_each_repository(ctx, process_repo, paths, **kwds)
  File "/home/marehr/develope/fastq2fasta-example-galaxy/workflow-build/planemo-venv/lib/python3.9/site-packages/planemo/shed/__init__.py", line 770, in for_each_repository
    function(realized_repository)
  File "/home/marehr/develope/fastq2fasta-example-galaxy/workflow-build/planemo-venv/lib/python3.9/site-packages/planemo/shed/__init__.py", line 235, in process_repo
    install_args_list.append(realized_repository.install_args(ctx, shed_context))
  File "/home/marehr/develope/fastq2fasta-example-galaxy/workflow-build/planemo-venv/lib/python3.9/site-packages/planemo/shed/__init__.py", line 1335, in install_args
    changeset_revision=self.latest_installable_revision(
  File "/home/marehr/develope/fastq2fasta-example-galaxy/workflow-build/planemo-venv/lib/python3.9/site-packages/planemo/shed/__init__.py", line 1324, in latest_installable_revision
    return latest_installable_revision(shed_context.tsi, repository_id)
  File "/home/marehr/develope/fastq2fasta-example-galaxy/workflow-build/planemo-venv/lib/python3.9/site-packages/planemo/shed/interface.py", line 48, in latest_installable_revision
    owner = info["owner"]
TypeError: list indices must be integers or slices, not str
```

After more reading I somehow figured out that I probably need a valid `.shed.yml` (I can't remember any more how I figured that out)

Two question:
* is there an easier way for my use case?
* could you provide a better error diagnostic?

**Comment by simonbray** [comment]
I think that should be the best approach. Did it work once you added the `.shed.yml`?

I think you could also use `planemo serve --galaxy_root ~/galaxy --shed_tool_conf ~/galaxy/config/shed_tool_conf.xml`, with a list of tools. That should work for the testtoolshed as well.
