### ISSUE TITLE
Planemo serve fails on Debian due to system python customizations

### ISSUE THREAD

**Issue by NickSto** [galaxyproject/planemo#1216]
FYI, I just installed a fresh version of Planemo on Ubuntu and tried running `planemo serve`, but it failed apparently because Debian [modifies its version of Python](https://bugs.launchpad.net/ubuntu/+source/python3.4/+bug/1290847) so that the standard library module `ensurepip` is missing.

## Reproducing

0. Have Ubuntu 20.04.3
1. Install Planemo
`$ python3 -m pip install --user planemo`
    - This installed Planemo 0.74.9
2. Run `planemo serve`
`$ planemo serve --conda_use_local`
    - I ran this from a directory containing Galaxy tool xmls and a `.shed.yml`.

## Result

The command fails. I think this is the important part of the error message (full output below):
```
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt install python3.8-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: ['/home/me/.planemo/gx_venv_3/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']
```

## Workaround

Installing `python3-venv` through apt did prevent this issue.

I did have to delete the existing virtualenv at `/home/me/.planemo/gx_venv_3`, though. I assume that's because it got left in an invalid state after the first failed attempt - that directory existed, but it contained no `bin/activate`. I see the bit of shell code checks if the directory exists, but not whether `bin/activate` is present inside.

## Full output

```
planemo couldn't find a target test-data directory, you should likely create a test-data directory or pass an explicit path using --test_data.
git clone --mirror https://github.com/galaxyproject/galaxy /home/me/.planemo/gx_repo
Cloning into bare repository '/home/me/.planemo/gx_repo'...
remote: Enumerating objects: 683096, done.
remote: Counting objects: 100% (102/102), done.
remote: Compressing objects: 100% (73/73), done.
remote: Total 683096 (delta 36), reused 88 (delta 29), pack-reused 682994
Receiving objects: 100% (683096/683096), 702.94 MiB | 43.25 MiB/s, done.
Resolving deltas: 100% (510287/510287), done.
git clone --branch master /home/me/.planemo/gx_repo /tmp/tmpznts31q1/galaxy-dev
Cloning into '/tmp/tmpznts31q1/galaxy-dev'...
done.
if [ -d .venv ]; then GALAXY_VIRTUAL_ENV=.venv; else GALAXY_VIRTUAL_ENV=/home/me/.planemo/gx_venv_3; fi && export GALAXY_VIRTUAL_ENV && if [ ! -e "$GALAXY_VIRTUAL_ENV" ]; then /usr/bin/python3 -m venv $GALAXY_VIRTUAL_ENV; echo "Created virtualenv"; fi && if [ -e "$GALAXY_VIRTUAL_ENV" ]; then . "$GALAXY_VIRTUAL_ENV"/bin/activate; echo "Activated a virtualenv for Galaxy"; echo "$VIRTUAL_ENV"; else echo "Failed to activate virtualenv."; fi && COMMON_STARTUP_ARGS=; $(grep -q 'skip-venv' run_tests.sh) && COMMON_STARTUP_ARGS="--dev-wheels"; export COMMON_STARTUP_ARGS; echo "Set COMMON_STARTUP_ARGS to ${COMMON_STARTUP_ARGS}" && ./scripts/common_startup.sh ${COMMON_STARTUP_ARGS}
galaxy.util.commands WARNING: Passing program arguments as a string may be a security hazard if combined with untrusted input
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt install python3.8-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: ['/home/me/.planemo/gx_venv_3/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']

Created virtualenv
/bin/sh: 1: .: Can't open /home/me/.planemo/gx_venv_3/bin/activate
Traceback (most recent call last):
  File "/home/me/.local/bin/planemo", line 8, in <module>
    sys.exit(planemo())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/me/.local/lib/python3.8/site-packages/planemo/cli.py", line 98, in handle_blended_options
    return f(*args, **kwds)
  File "/home/me/.local/lib/python3.8/site-packages/planemo/commands/cmd_serve.py", line 43, in cli
    galaxy_serve(ctx, runnables, **kwds)
  File "/home/me/.local/lib/python3.8/site-packages/planemo/galaxy/serve.py", line 25, in serve
    return _serve(ctx, runnables, **kwds)
  File "/home/me/.local/lib/python3.8/site-packages/planemo/galaxy/serve.py", line 45, in _serve
    with galaxy_config(ctx, runnables, **kwds) as config:
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/me/.local/lib/python3.8/site-packages/planemo/galaxy/config.py", line 232, in galaxy_config
    with c(ctx, runnables, **kwds) as config:
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/me/.local/lib/python3.8/site-packages/planemo/galaxy/config.py", line 406, in local_galaxy_config
    _install_galaxy(ctx, galaxy_root, install_env, kwds)
  File "/home/me/.local/lib/python3.8/site-packages/planemo/galaxy/config.py", line 1229, in _install_galaxy
    _install_galaxy_via_git(ctx, galaxy_root, env, kwds)
  File "/home/me/.local/lib/python3.8/site-packages/planemo/galaxy/config.py", line 1247, in _install_galaxy_via_git
    _install_with_command(ctx, galaxy_root, env, kwds)
  File "/home/me/.local/lib/python3.8/site-packages/planemo/galaxy/config.py", line 1281, in _install_with_command
    raise Exception("Failed to install Galaxy via command [%s]" % install_cmd)
Exception: Failed to install Galaxy via command [if [ -d .venv ]; then GALAXY_VIRTUAL_ENV=.venv; else GALAXY_VIRTUAL_ENV=/home/me/.planemo/gx_venv_3; fi && export GALAXY_VIRTUAL_ENV && if [ ! -e "$GALAXY_VIRTUAL_ENV" ]; then /usr/bin/python3 -m venv $GALAXY_VIRTUAL_ENV; echo "Created virtualenv"; fi && if [ -e "$GALAXY_VIRTUAL_ENV" ]; then . "$GALAXY_VIRTUAL_ENV"/bin/activate; echo "Activated a virtualenv for Galaxy"; echo "$VIRTUAL_ENV"; else echo "Failed to activate virtualenv."; fi && COMMON_STARTUP_ARGS=; $(grep -q 'skip-venv' run_tests.sh) && COMMON_STARTUP_ARGS="--dev-wheels"; export COMMON_STARTUP_ARGS; echo "Set COMMON_STARTUP_ARGS to ${COMMON_STARTUP_ARGS}" && ./scripts/common_startup.sh ${COMMON_STARTUP_ARGS}]
```

**Comment by mvdbeek** [comment]
I don't think there's much we can do in planemo, potentially something we could address in Galaxy if that is still an issue.
