### ISSUE TITLE
Planenmo test with <has_line line="..."> fails when stdout is bigger than 2**14 characters long.

### ISSUE THREAD

**Issue by Lain-inrae** [galaxyproject/planemo#1235]
When we use the test `has_line` in a tool's xml's tests the stdout is cut if its length is greater than 2**14 characters.

Here are two examples of xml tools.
This one works fine because the output will be 200 lines long:
```xml
<tool id="ok_planemo_gx" name="ok_planemo_gx" version="1.0.0" profile="22.01">
    <requirements>
        <requirement type="package">python</requirement>
    </requirements>
    <command><![CDATA[python -c 'print("\n".join(map("{:05}".format, range(200))))']]></command>
    <inputs><param type="data" format="txt" name="i"/></inputs>
    <outputs><data name="o" format="txt" /></outputs>
    <tests>
        <test>
            <param name="i" value="input.txt" />
            <assert_stdout>
                <has_line line="00123" />
            </assert_stdout>
        </test>
    </tests>
</tool>
```

But in this one, the test fails because the stdout is cut in the area shown above:
```xml
<tool id="bug_planemo_gx" name="bug_planemo_gx" version="1.0.0" profile="22.01">
    <requirements>
        <requirement type="package">python</requirement>
    </requirements>
    <command><![CDATA[python -c 'print("\n".join(map(map("{:05}".format, range(6000))))']]></command>
    <inputs><param type="data" format="txt" name="i"/></inputs>
    <outputs><data name="o" format="txt" /></outputs>
    <tests>
        <test>
            <param name="i" value="input.txt" />
            <assert_stdout>
                <has_line line="03000" />
            </assert_stdout>
        </test>
    </tests>
</tool>
```

Output is cut here:
```txt
02727
02728
02729
02
..
9
03270
03271
03272
```

As we can see, the first part of the output is 6*2729+3 (=16377) characters long. Which is only seven characters away from to 2**14 (=16384).

I suppose other tests like `has_text`, `not_has_text`, `has_text_matching` - and so on - will be prone to this problem.

**Comment by Lain-inrae** [comment]
There is another problem, that may be corrected by the same bugfix (so I did not open a new issue).

When the stdout is less than 2**14, the  stdout is duplicated.

For example, I get an error when running this tool's test:
```xml
<tool id="ok_planemo_gx" name="ok_planemo_gx" version="1.0.0" profile="22.01">
    <requirements>
        <requirement type="package">python</requirement>
    </requirements>
    <command><![CDATA[python -c 'print("0" * 200)']]></command>
    <inputs><param type="data" format="txt" name="i"/></inputs>
    <outputs><data name="o" format="txt" /></outputs>
    <tests>
        <test>
            <param name="i" value="input.txt" />
            <assert_stdout>
                <has_size value="200" />
            </assert_stdout>
        </test>
    </tests>
</tool>
```
Planemo's outputs:
```
---------------------- >> begin tool stdout << -----------------------
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

----------------------- >> end tool stdout << ------------------------

---------------------- >> begin tool stderr << -----------------------

----------------------- >> end tool stderr << ------------------------
FAIL

======================================================================
FAIL: ( ok_planemo_gx ) > Test-1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/tmper40nzja/galaxy-dev/test/functional/test_toolbox.py", line 98, in test_tool
    self.do_it(tool_version=tool_version, test_index=test_index)
  File "/tmp/tmper40nzja/galaxy-dev/test/functional/test_toolbox.py", line 35, in do_it
    verify_tool(tool_id, self.galaxy_interactor, resource_parameters=resource_parameters, test_index=test_index, tool_version=tool_version, register_job_data=register_job_data)
  File "/tmp/tmper40nzja/galaxy-dev/lib/galaxy/tool_util/verify/interactor.py", line 1127, in verify_tool
    raise e
  File "/tmp/tmper40nzja/galaxy-dev/lib/galaxy/tool_util/verify/interactor.py", line 1123, in verify_tool
    job_stdio = _verify_outputs(testdef, test_history, jobs, data_list, data_collection_list, galaxy_interactor, quiet=quiet)
  File "/tmp/tmper40nzja/galaxy-dev/lib/galaxy/tool_util/verify/interactor.py", line 1299, in _verify_outputs
    raise JobOutputsError(found_exceptions, job_stdio)
galaxy.tool_util.verify.interactor.JobOutputsError: Standard output of the job different than expected
Expected file size of 200+-0 found 403
```

As we can see, the stdout is duplicated, so the output's size is duplicated too.

**Comment by Lain-inrae** [comment]
The problem comes from the way galaxy tests a tool:
`galaxy.tool_util.verify.script._test_tool` function uses the `galaxy.tool_util.verify.interactor.verify_tool`, which uses the interactor (so, the api) to retrieve the job's json data... 
This json's `stdout` attribute is always reduced in size, even with `?full=true`.

So, this is galaxy issue.

**Comment by simonbray** [comment]
Hi @Lain-inrae, thanks for looking into this!

Maybe we can add a line to the docs for `assert_stderr` and `assert_stdout` warning users that stderr and stdout get cut when stored in the database.
