### ISSUE TITLE
Workflow outputs for optional workflow input fail testing

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/planemo#1289]
```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.14/x64/lib/python3.7/site-packages/planemo/galaxy/activity.py", line 53, in execute
    return _execute(ctx, config, runnable, job_path, **kwds)
  File "/opt/hostedtoolcache/Python/3.7.14/x64/lib/python3.7/site-packages/planemo/galaxy/activity.py", line 227, in _execute
    run_response.collect_outputs(ctx, output_directory)
  File "/opt/hostedtoolcache/Python/3.7.14/x64/lib/python3.7/site-packages/planemo/galaxy/activity.py", line 420, in collect_outputs
    output_src = self.output_src(runnable_output)
  File "/opt/hostedtoolcache/Python/3.7.14/x64/lib/python3.7/site-packages/planemo/galaxy/activity.py", line 621, in output_src
    raise Exception(f"Failed to find output [{output_name}] in invocation outputs [{invocation['outputs']}]")
Exception: Failed to find output [af_filter_threshold] in invocation outputs [{'all_variants_all_samples': {'id': 'c8335b7916cc2314', 'src': 'hda', 'workflow_step_id': '60e68e80f94e5adf'}, 'by_variant_report': {'id': '918fee5d6b202582', 'src': 'hda', 'workflow_step_id': '70dc17380d69578d'}, 'combined_variant_report': {'id': 'e5a2f43dfe66c20f', 'src': 'hda', 'workflow_step_id': '15deb50af0d8e0b7'}, 'variant_frequency_plot': {'id': 'b9adee4e95c9316a', 'src': 'hda', 'workflow_step_id': '4fd53021125dfbdb'}}]
```

**Comment by mvdbeek** [comment]
Fixed in https://github.com/galaxyproject/planemo/pull/1297
