### ISSUE TITLE
[BUG] between version 0.75.0 and 0.75.1 on autoupdate

### ISSUE THREAD

**Issue by lldelisle** [galaxyproject/planemo#1311]
I may have done something wrong because:
https://github.com/planemo-autoupdate/autoupdate/actions/runs/3376419931/jobs/5604120700#step:6:462
With version 0.75.0:
```
(.venv3) [ldelisle@SV-49-002 TrimNs]$ planemo autoupdate .
Auto-updating tool /tmp/test/tools-iuc/tools/TrimNs/TrimNs.xml
Tool version does not contain @TOOL_VERSION@ as required by autoupdate.
```
With version 0.75.1:
```
(.venv3) [ldelisle@SV-49-002 TrimNs]$ planemo autoupdate .
Traceback (most recent call last):
  File "/tmp/test/.venv3/bin/planemo", line 8, in <module>
    sys.exit(planemo())
  File "/tmp/test/.venv3/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/tmp/test/.venv3/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/tmp/test/.venv3/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/tmp/test/.venv3/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tmp/test/.venv3/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/tmp/test/.venv3/lib/python3.10/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/tmp/test/.venv3/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/tmp/test/.venv3/lib/python3.10/site-packages/planemo/cli.py", line 102, in handle_blended_options
    return f(*args, **kwds)
  File "/tmp/test/.venv3/lib/python3.10/site-packages/planemo/commands/cmd_autoupdate.py", line 95, in cli
    if any(r.type in {RunnableType.galaxy_tool, RunnableType.directory} for r in runnables):
  File "/tmp/test/.venv3/lib/python3.10/site-packages/planemo/commands/cmd_autoupdate.py", line 95, in <genexpr>
    if any(r.type in {RunnableType.galaxy_tool, RunnableType.directory} for r in runnables):
AttributeError: 'list' object has no attribute 'type'
```

**Comment by mvdbeek** [comment]
Yep, I see where this went wrong, I'll have a fix in a second.

**Comment by lldelisle** [comment]
I think a test like this could be added to tests autoupdate:
```

    def test_autoupdate_directory(self):
        """Test autoupdate command."""
        with self._isolate():
            xmlfile = create_tmp_test_tool_file("0.6.0")
            t = tempfile.mkdtemp()
            new_xmlfile = os.path.join(t, "tool.xml")
            shutil.copyfile(xmlfile, new_xmlfile)
            autoupdate_command = ["autoupdate", t, "--conda_channels", "bioconda"]
            result = self._runner.invoke(self._cli.planemo, autoupdate_command)
            assert f'Updating tool.xml from version 0.6.0 to 0.7.3' in result.output
            assert f"Tool tool.xml successfully updated." in result.output
            with open(new_xmlfile) as f:
                xmlfile_contents = f.read()
            assert "2017.11.9" in xmlfile_contents

```
