### ISSUE TITLE
planemo workflow_edit currently not working?

### ISSUE THREAD

**Issue by jancrichter** [galaxyproject/planemo#1318]
When running planemo workflow_edit I am currently getting this error:

```
Traceback (most recent call last):
  File "/usr/local/bin/planemo", line 8, in <module>
    sys.exit(planemo())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/planemo/cli.py", line 96, in handle_blended_options
    return f(*args, **kwds)
  File "/usr/local/lib/python3.8/dist-packages/planemo/commands/cmd_workflow_edit.py", line 21, in cli
    runnable = for_runnable_identifier(ctx, workflow_identifier, kwds.get("profile"))
  File "/usr/local/lib/python3.8/dist-packages/planemo/runnable_resolve.py", line 15, in for_runnable_identifier
    current_profile = kwds.get("profile")
AttributeError: 'NoneType' object has no attribute 'get'
```

I created the pull request #1300 to get me past this, however all I then get is a Galaxy instance just as I would using `planemo serve`. This Galaxy instance also does not contain my workflow, nor does it have any of the workflow's tools installed.

Planemo version 0.74.11 and 0.75.2
Galaxy versions 22.01 and 22.05

I seem to remember, that in the past the command directly opened only a workflow editor, with the workflow. Back then I wasn't able to use it directly, because I had not set up planemo to know my toolshed and therefore it couldn't get any tools from there.

**Comment by mvdbeek** [comment]
This is fixed in planemo 0.75.21 ... sorry for the long delay here.
