### ISSUE TITLE
Error in planemo testing

### ISSUE THREAD

**Issue by domenico-simone** [galaxyproject/planemo#1339]
Hello,

I am running a Galaxy instance (19.05) on a CentOS 7 system. Since the .venv required by Galaxy 19.05 is python2 based, I am running planemo from a separate .venv with python3 (installation in a python2-based venv didn't succeed). I am trying to create a wrapper from this conda package https://anaconda.org/bioconda/rmlst_api. The `planemo lint` went smooth, but I'm facing troubles during the `planemo test` step:

```
2022-12-16 14:34:43,251 DEBUG [galaxy.tools.deps.conda_util] Executing command: /home/galaxy/miniconda3/bin/conda create -y --quiet --override-channels --channel conda-forge --channel bioconda --channel defaults --name __bcftools@1.5 bcftools=1.5
WARNING conda.exceptions:print_unexpected_error_report(1137): KeyError('pkgs_dirs')
Traceback (most recent call last):
  File "/home/galaxy/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1003, in __call__
    return func(*args, **kwargs)
  File "/home/galaxy/miniconda3/lib/python3.7/site-packages/conda/cli/main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "/home/galaxy/miniconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 80, in do_call
    module = import_module(relative_mod, __name__.rsplit('.', 1)[0])
  File "/home/galaxy/miniconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/galaxy/miniconda3/lib/python3.7/site-packages/conda/cli/main_create.py", line 10, in <module>
    from .install import install
  File "/home/galaxy/miniconda3/lib/python3.7/site-packages/conda/cli/install.py", line 18, in <module>
    from ..core.index import calculate_channel_urls, get_index
  File "/home/galaxy/miniconda3/lib/python3.7/site-packages/conda/core/index.py", line 10, in <module>
    from .package_cache_data import PackageCacheData
  File "/home/galaxy/miniconda3/lib/python3.7/site-packages/conda/core/package_cache_data.py", line 15, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "/home/galaxy/miniconda3/lib/python3.7/site-packages/conda/core/path_actions.py", line 31, in <module>
    from ..gateways.connection.download import download
  File "/home/galaxy/miniconda3/lib/python3.7/site-packages/conda/gateways/connection/__init__.py", line 21, in <module>
    from requests import ConnectionError, HTTPError, Session
  File "/home/galaxy/miniconda3/lib/python3.7/site-packages/requests/__init__.py", line 95, in <module>
    from urllib3.contrib import pyopenssl
  File "/home/galaxy/miniconda3/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/home/galaxy/miniconda3/lib/python3.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/home/galaxy/miniconda3/lib/python3.7/site-packages/OpenSSL/crypto.py", line 1553, in <module>
    class X509StoreFlags(object):
  File "/home/galaxy/miniconda3/lib/python3.7/site-packages/OpenSSL/crypto.py", line 1573, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
```
Please find attached the whole log here: [planemo_test.log](https://github.com/galaxyproject/planemo/files/10253572/planemo_test.log).

Here's the content of the xml file:
```
<tool id="rmlst_api" name="rmlst_api" version="@TOOL_VERSION@+galaxy@VERSION_SUFFIX@" profile="19.05">
    <description>Run rMLST API through a python script for species identification of a bacterial assembly</description>
    <macros>
        <token name="@TOOL_VERSION@">0.1.3</token>
        <token name="@VERSION_SUFFIX@">0</token>
        <xml name="bio_tools">
            <xrefs>
                <xref type="bio.tools">rmlst_api</xref>
            </xrefs>
        </xml>
    </macros>
    <requirements>
        <requirement type="package" version="@TOOL_VERSION@">rmlst_api</requirement>
        <requirement type="package" version=">=8.1.3">click</requirement>
        <requirement type="package" version="2.28.1">requests</requirement>
    </requirements>
    <command detect_errors="exit_code"><![CDATA[
        ln -s '${file_input} '$assembly' &&
        rmlst_api $assembly
        --output-tab 'rmlst_api_output.tab'
        --output-json 'rmlst_api_output.json'
    ]]></command>
    <inputs>
        <param name="file_input" type="data" format="fasta" label="Bacterial genome assembly file (FASTA)" help="To be rMLST'ed, must be FASTA file." />
    </inputs>
    <outputs>
        <data name="outfile_tab" label="${tool.name} on ${on_string}" format="tab" />
        <data name="outfile_json" label="${tool.name} on ${on_string}" format="json" />
    </outputs>
    <tests>
        <test expect_num_outputs="2">
            <param name="file_input" value="sample_genome.fasta" />
            <output name="outfile_tab" file="rmlst_api_output.tab" ftype="tab" />
            <output name="outfile_json" file="rmlst_api_output.json" ftype="json" />
        </test>
    </tests>
    <help><![CDATA[
        "Run rMLST API for species identification of a bacterial genome assembly."
    ]]></help>
    <citations>
        <citation type="doi">10.5281/zenodo.7447005</citation>
    </citations>
</tool>
```

what could be the error?

Thank you,

Domenico

**Comment by nsoranzo** [comment]
I think something is broken with your conda installation in `/home/galaxy/miniconda3/` , you can check by running:

```shell
/home/galaxy/miniconda3/bin/conda create -y --quiet --override-channels --channel conda-forge --channel bioconda --channel defaults --name __bcftools@1.5 bcftools=1.5
```

outside of Planemo/Galaxy. If that's confirmed, you can rename that directory, reinstall miniconda3 and see if that fixes it.

By the way, Galaxy 19.05 is not supported any more, please update to at least 22.01 if you can.

**Comment by domenico-simone** [comment]
@nsoranzo thank you for the hint, I reinstalled miniconda and it worked!

I know you're right about the Galaxy version, unfortunately the platform where I'm deploying Galaxy provides 19.05 only. Do you think it could be a good strategy to develop and test Galaxy wrappers on another machine where I can deploy a v22 and install them on the official 19.05 deployment?

Thank you,

Domenico
