### ISSUE TITLE
Cheetah parsing error of variable on Galaxy execution when planemo tests using the same variable pass

### ISSUE THREAD

**Issue by pcm32** [galaxyproject/planemo#1405]
I have a strange case on a tool which passed planemo tests with latest version of planemo, but execution of the same tool on the galaxy instance (22.05) fails because cheetah fails to find a variable. The variable in question looks like this in the [tool](https://github.com/ebi-gene-expression-group/container-galaxy-sc-tertiary/blob/c8c39f14eeee6e7a6d097fd0cb9430b12793eb8b/tools/tertiary-analysis/decoupler/decoupler_aucell_score.xml):

```
<conditional name="gene_lists_source">
            <param name="source" type="select" label="Source of gene lists to score" help="Choose between using a GMT file and specified gene sets or enumerated genes and gene set names.">
                <option value="gmt" selected="true">Gene sets from GMT file</option>
                <option value="enumerated">Gene sets enumerated manually</option>
            </param>
            <when value="gmt">
                <param name="gmt_file" type="data" format="txt" label="GMT file with gene sets" />
                <param name="gene_sets_to_score" type="text" label="Gene sets to score within the GMT file" />
            </when>
            <when value="enumerated">
                <param name="gene_lists_to_score" type="text" label="Genes to score" />
                <param name="score_names" type="text" label="Score names" />
            </when>
        </conditional>
```

it is the `gene_sets_to_score` variable, which is used like this in the command part (directly by the name):

```
python '$__tool_directory__/decoupler_aucell_score.py'
            --input_file '$input_file'
            #if $gene_lists_source.source == "gmt"
            --gmt_file '$gmt_file'
            --gene_sets_to_score '$gene_sets_to_score'
            #else:
            --gene_lists_to_score '$gene_lists_to_score'
            --score_names '$score_names'
```

On tests, the field is referred to directly by the name:

```
<test expect_num_outputs="1">
            <param name="input_file" value="mito_counted_anndata.h5ad"/>
            <param name="gene_sets_to_score" value="HALLMARK_NOTCH_SIGNALING,HALLMARK_APICAL_SURFACE"/>
            <param name="gmt_file" value="mouse_hallmark_ss.gmt"/>
            <param name="gene_symbols_field" value="Symbol"/>
            <param name="write_anndata" value="true"/>
            <conditional name="gene_lists_source">
                <param name="source" value="gmt"/>
            </conditional>
            <output name="output_ad">
                <assert_contents>
                    <has_h5_keys keys="obs/AUCell_HALLMARK_NOTCH_SIGNALING"/>
                    <has_h5_keys keys="obs/AUCell_HALLMARK_APICAL_SURFACE"/>
                </assert_contents>
            </output>
        </test>
```

On the CI using the latest planemo at that point (2nd of November), the tool passes the tests, and the field is correctly substituted by the proposed variable:

![image](https://github.com/galaxyproject/planemo/assets/368478/da6f01c5-ae19-432a-bd8a-af1edca6757a)

The report is available [here](https://github.com/ebi-gene-expression-group/container-galaxy-sc-tertiary/actions/runs/6738738326) for some time.

However, on execution on Galaxy, providing a text value for that field, produces the following error:

```
Traceback (most recent call last):
  File "/galaxy/server/lib/galaxy/jobs/runners/__init__.py", line 260, in prepare_job
    job_wrapper.prepare()
  File "/galaxy/server/lib/galaxy/jobs/__init__.py", line 1238, in prepare
    ) = tool_evaluator.build()
  File "/galaxy/server/lib/galaxy/tools/evaluation.py", line 552, in build
    global_tool_logs(self._build_command_line, config_file, "Building Command Line")
  File "/galaxy/server/lib/galaxy/tools/evaluation.py", line 89, in global_tool_logs
    raise e
  File "/galaxy/server/lib/galaxy/tools/evaluation.py", line 85, in global_tool_logs
    return func()
  File "/galaxy/server/lib/galaxy/tools/evaluation.py", line 569, in _build_command_line
    command_line = fill_template(
  File "/galaxy/server/lib/galaxy/util/template.py", line 111, in fill_template
    raise first_exception or e
  File "/galaxy/server/lib/galaxy/util/template.py", line 83, in fill_template
    return unicodify(t, log_exception=False)
  File "/galaxy/server/lib/galaxy/util/__init__.py", line 1141, in unicodify
    value = str(value)
  File "/galaxy/server/.venv/lib/python3.10/site-packages/Cheetah/Template.py", line 1053, in __unicode__
    return getattr(self, mainMethName)()
  File "cheetah_DynamicallyCompiledCheetahTemplate_1699884044_3119001_33446.py", line 101, in respond
NameMapper.NotFound: cannot find 'gene_sets_to_score'
```

Shouldn't this issue be catched by planemo, either because the test is giving the field name incorrectly or because the command is badly using the field (by not prepending the conditional field name)? Thanks!

**Comment by mvdbeek** [comment]
Yep, we're more lenient in our fallbacks, but you should use the fully qualified variable, which is `gene_lists_source. gene_sets_to_score `
