### ISSUE TITLE
Cryptic AttributeError attempting to use shed_upload

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/planemo#153]
This was my first attempt to use `planemo shed_upload`, where I first manually generated a tar-ball (which I would normally have uploaded to the Tool Shed by hand) supplied here with the `--tar` option.

I presume `PROJECT` means a folder (containing `.shed.yml`), thus I tried:

```
$ planemo shed_upload --shed_target testtoolshed --message "v0.0.8; fixed missing rpy error; relaxed test" --tar ~/toolshed_archives/venn_list_v0.0.8.tar.gz ~/repositories/pico_galaxy/tools/venn_list/
/mnt/galaxy/repositories/planemo/.venv/lib/python2.6/site-packages/requests-2.6.2-py2.6.egg/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
/mnt/galaxy/repositories/planemo/.venv/lib/python2.6/site-packages/requests-2.6.2-py2.6.egg/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
Traceback (most recent call last):
  File "/mnt/galaxy/repositories/planemo/.venv/bin/planemo", line 9, in <module>
    load_entry_point('planemo==0.9.0.dev0', 'console_scripts', 'planemo')()
  File "/mnt/galaxy/repositories/planemo/.venv/lib/python2.6/site-packages/click-4.0-py2.6.egg/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/mnt/galaxy/repositories/planemo/.venv/lib/python2.6/site-packages/click-4.0-py2.6.egg/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/mnt/galaxy/repositories/planemo/.venv/lib/python2.6/site-packages/click-4.0-py2.6.egg/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/mnt/galaxy/repositories/planemo/.venv/lib/python2.6/site-packages/click-4.0-py2.6.egg/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/galaxy/repositories/planemo/.venv/lib/python2.6/site-packages/click-4.0-py2.6.egg/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/mnt/galaxy/repositories/planemo/.venv/lib/python2.6/site-packages/click-4.0-py2.6.egg/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/mnt/galaxy/repositories/planemo/.venv/lib/python2.6/site-packages/click-4.0-py2.6.egg/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/mnt/galaxy/repositories/planemo/.venv/lib/python2.6/site-packages/planemo-0.9.0.dev0-py2.6.egg/planemo/commands/cmd_shed_upload.py", line 63, in cli
    exit_code = shed.for_each_repository(upload, path, **kwds)
  File "/mnt/galaxy/repositories/planemo/.venv/lib/python2.6/site-packages/planemo-0.9.0.dev0-py2.6.egg/planemo/shed.py", line 417, in for_each_repository
    function(realized_repository)
  File "/mnt/galaxy/repositories/planemo/.venv/lib/python2.6/site-packages/planemo-0.9.0.dev0-py2.6.egg/planemo/commands/cmd_shed_upload.py", line 61, in upload
    return __handle_upload(ctx, realized_repository, **kwds)
  File "/mnt/galaxy/repositories/planemo/.venv/lib/python2.6/site-packages/planemo-0.9.0.dev0-py2.6.egg/planemo/commands/cmd_shed_upload.py", line 99, in __handle_upload
    exception_content = e.read()
AttributeError: 'exceptions.TypeError' object has no attribute 'read'
```

Note that I expected this to read the name and owner from the `.shed.yml` file (including the `--name` and `--owner` arguments made no difference):

```
$ more ~/repositories/pico_galaxy/tools/venn_list/.shed.yml
name: venn_list
owner: peterjc
homepage_url: https://github.com/peterjc/pico_galaxy/tools/venn_list
remote_repository_url: https://github.com/peterjc/pico_galaxy/tools/venn_list
description: Draw Venn Diagram (PDF) from lists, FASTA files, etc
long_description: |
  Draw Venn Diagrams for 1, 2 or 3 sets of identifiers as a PDF file.

  Can parse FASTA, FASTQ, SFF or tabular files (taking column one) for identifiers.
  This can be combined with the extensive tabular file filtering and manipulation
  tools within Galaxy to prepare the input data.

  Uses the R/Bioconductor package limma to draw the PDF file, called from Python with
  rpy.

  Uses Biopython to parse SFF files.
categories:
- Graphics
- Sequence Analysis
- Visualization
type: unrestricted
```

**Comment by peterjc** [comment]
Debugging,
```
$ git diff
diff --git a/planemo/commands/cmd_shed_upload.py b/planemo/commands/cmd_shed_upload.py
index 4a075cb..810e71a 100644
--- a/planemo/commands/cmd_shed_upload.py
+++ b/planemo/commands/cmd_shed_upload.py
@@ -95,7 +95,10 @@ def __handle_upload(ctx, realized_repository, **kwds):
 
     try:
         tsi.repositories.update_repository(repo_id, tar_path, **update_kwds)
-    except Exception as e:
+    except TypeError as e:
+        error("Calling update_repository failed: %s" % e)
+        return -1
+    except Exception as e:        
         exception_content = e.read()
         try:
             # Galaxy passes nice JSON messages as their errors, which bioblend
```

gives:

```
Calling update_repository failed: object of type 'NoneType' has no len()
```

**Comment by erasche** [comment]
@peterjc sorry about the debugging statements, that error catching is a complete mess and it's 100% on me. I had...so much trouble getting it to behave nicely and I've been meaning to go back and fix that (#116)

**Comment by peterjc** [comment]
Good point - definitely has links with #116. If I remove that error handling,
```
$ git diff
diff --git a/planemo/commands/cmd_shed_upload.py b/planemo/commands/cmd_shed_upload.py
index 4a075cb..dbf1017 100644
--- a/planemo/commands/cmd_shed_upload.py
+++ b/planemo/commands/cmd_shed_upload.py
@@ -93,19 +93,7 @@ def __handle_upload(ctx, realized_repository, **kwds):
         return -1
     # TODO: support updating repo information if it changes in the config file
 
-    try:
-        tsi.repositories.update_repository(repo_id, tar_path, **update_kwds)
-    except Exception as e:
-        exception_content = e.read()
-        try:
-            # Galaxy passes nice JSON messages as their errors, which bioblend
-            # blindly returns. Attempt to parse those.
-            upstream_error = json.loads(exception_content)
-            error(upstream_error['err_msg'])
-        except Exception as e2:
-            error("Could not update %s" % realized_repository.name)
-            error(exception_content)
-            error(e2.read())
-        return -1
+    tsi.repositories.update_repository(repo_id, tar_path, **update_kwds)
+
     info("Repository %s updated successfully." % realized_repository.name)
     return 0
```

then I can see where this is breaking inside bioblend:

```
$ planemo shed_upload --shed_target testtoolshed --message "v0.0.8; fixed missing rpy error; relaxed test" --tar ~/toolshed_archives/venn_list_v0.0.8.tar.gz ~/repositories/pico_galaxy/tools/venn_list 
/mnt/galaxy/repositories/planemo/.venv/lib/python2.6/site-packages/requests-2.6.2-py2.6.egg/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
/mnt/galaxy/repositories/planemo/.venv/lib/python2.6/site-packages/requests-2.6.2-py2.6.egg/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
Traceback (most recent call last):
  File "/mnt/galaxy/repositories/planemo/.venv/bin/planemo", line 9, in <module>
    load_entry_point('planemo==0.9.0.dev0', 'console_scripts', 'planemo')()
  File "/mnt/galaxy/repositories/planemo/.venv/lib/python2.6/site-packages/click-4.0-py2.6.egg/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/mnt/galaxy/repositories/planemo/.venv/lib/python2.6/site-packages/click-4.0-py2.6.egg/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/mnt/galaxy/repositories/planemo/.venv/lib/python2.6/site-packages/click-4.0-py2.6.egg/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/mnt/galaxy/repositories/planemo/.venv/lib/python2.6/site-packages/click-4.0-py2.6.egg/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/galaxy/repositories/planemo/.venv/lib/python2.6/site-packages/click-4.0-py2.6.egg/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/mnt/galaxy/repositories/planemo/.venv/lib/python2.6/site-packages/click-4.0-py2.6.egg/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/mnt/galaxy/repositories/planemo/.venv/lib/python2.6/site-packages/click-4.0-py2.6.egg/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/mnt/galaxy/repositories/planemo/.venv/lib/python2.6/site-packages/planemo-0.9.0.dev0-py2.6.egg/planemo/commands/cmd_shed_upload.py", line 63, in cli
    exit_code = shed.for_each_repository(upload, path, **kwds)
  File "/mnt/galaxy/repositories/planemo/.venv/lib/python2.6/site-packages/planemo-0.9.0.dev0-py2.6.egg/planemo/shed.py", line 417, in for_each_repository
    function(realized_repository)
  File "/mnt/galaxy/repositories/planemo/.venv/lib/python2.6/site-packages/planemo-0.9.0.dev0-py2.6.egg/planemo/commands/cmd_shed_upload.py", line 61, in upload
    return __handle_upload(ctx, realized_repository, **kwds)
  File "/mnt/galaxy/repositories/planemo/.venv/lib/python2.6/site-packages/planemo-0.9.0.dev0-py2.6.egg/planemo/commands/cmd_shed_upload.py", line 96, in __handle_upload
    tsi.repositories.update_repository(repo_id, tar_path, **update_kwds)
  File "build/bdist.linux-x86_64/egg/bioblend/toolshed/repositories/__init__.py", line 278, in update_repository
    
  File "build/bdist.linux-x86_64/egg/bioblend/galaxy/client.py", line 171, in _post
  File "build/bdist.linux-x86_64/egg/bioblend/galaxyclient.py", line 92, in make_post_request
  File "/mnt/galaxy/repositories/planemo/.venv/lib/python2.6/site-packages/poster-0.8.1-py2.6.egg/poster/encode.py", line 411, in multipart_encode
  File "/mnt/galaxy/repositories/planemo/.venv/lib/python2.6/site-packages/poster-0.8.1-py2.6.egg/poster/encode.py", line 311, in get_headers
  File "/mnt/galaxy/repositories/planemo/.venv/lib/python2.6/site-packages/poster-0.8.1-py2.6.egg/poster/encode.py", line 302, in get_body_size
  File "/mnt/galaxy/repositories/planemo/.venv/lib/python2.6/site-packages/poster-0.8.1-py2.6.egg/poster/encode.py", line 302, in <genexpr>
  File "/mnt/galaxy/repositories/planemo/.venv/lib/python2.6/site-packages/poster-0.8.1-py2.6.egg/poster/encode.py", line 265, in get_size
TypeError: object of type 'NoneType' has no len()
```

**Comment by erasche** [comment]
No way it's a result of your insecure platform warnings?

**Comment by peterjc** [comment]
I would assume that is a warning only. It looks like switching to Python 2.7 on this user account would be a pain (not even sure that would fix the warning), so I would prefer to keep using the same underlying Python 2.6 instance which our Galaxy is running under.

**Comment by erasche** [comment]
Fair enough. That said, it looks like it's getting back an empty response. Don't suppose you can `tcpdump` that (or similar) and verify?

**Comment by jmchilton** [comment]
@peterjc Hmm... poster is sort of old and unmaintained. We have [replaced](https://github.com/galaxyproject/bioblend/commit/20f482b341789da163b11b9a714dee6f6e924979) it in bioblend. It would be interesting to see if upgrading bioblend to the latest ``master`` revision would help - I suppose it would still give you an error but maybe a more infromative one?

**Comment by peterjc** [comment]
I can give that a go...

**Comment by peterjc** [comment]
Fresh virtual env, installed bioblend from github (using requests-toolbelt rather than poster) and then planemo from github, both via ``python setup.py install``:

```
$ planemo shed_upload --shed_target testtoolshed --message "v0.0.8; fixed missing rpy error; relaxed test" --tar ~/toolshed_archives/venn_list_v0.0.8.tar.gz ~/repositories/pico_galaxy/tools/venn_list 
/mnt/galaxy/repositories/planemo/.venv/lib/python2.6/site-packages/requests-2.6.2-py2.6.egg/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "/mnt/galaxy/repositories/planemo/.venv/bin/planemo", line 9, in <module>
    load_entry_point('planemo==0.9.0.dev0', 'console_scripts', 'planemo')()
  File "/mnt/galaxy/repositories/planemo/.venv/lib/python2.6/site-packages/click-4.0-py2.6.egg/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/mnt/galaxy/repositories/planemo/.venv/lib/python2.6/site-packages/click-4.0-py2.6.egg/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/mnt/galaxy/repositories/planemo/.venv/lib/python2.6/site-packages/click-4.0-py2.6.egg/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/mnt/galaxy/repositories/planemo/.venv/lib/python2.6/site-packages/click-4.0-py2.6.egg/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/galaxy/repositories/planemo/.venv/lib/python2.6/site-packages/click-4.0-py2.6.egg/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/mnt/galaxy/repositories/planemo/.venv/lib/python2.6/site-packages/click-4.0-py2.6.egg/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/mnt/galaxy/repositories/planemo/.venv/lib/python2.6/site-packages/click-4.0-py2.6.egg/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/mnt/galaxy/repositories/planemo/.venv/lib/python2.6/site-packages/planemo-0.9.0.dev0-py2.6.egg/planemo/commands/cmd_shed_upload.py", line 63, in cli
    exit_code = shed.for_each_repository(upload, path, **kwds)
  File "/mnt/galaxy/repositories/planemo/.venv/lib/python2.6/site-packages/planemo-0.9.0.dev0-py2.6.egg/planemo/shed.py", line 417, in for_each_repository
    function(realized_repository)
  File "/mnt/galaxy/repositories/planemo/.venv/lib/python2.6/site-packages/planemo-0.9.0.dev0-py2.6.egg/planemo/commands/cmd_shed_upload.py", line 61, in upload
    return __handle_upload(ctx, realized_repository, **kwds)
  File "/mnt/galaxy/repositories/planemo/.venv/lib/python2.6/site-packages/planemo-0.9.0.dev0-py2.6.egg/planemo/commands/cmd_shed_upload.py", line 96, in __handle_upload
    tsi.repositories.update_repository(repo_id, tar_path, **update_kwds)
  File "build/bdist.linux-x86_64/egg/bioblend/toolshed/repositories/__init__.py", line 283, in update_repository
    
  File "build/bdist.linux-x86_64/egg/bioblend/galaxy/client.py", line 171, in _post
  File "build/bdist.linux-x86_64/egg/bioblend/galaxyclient.py", line 112, in make_post_request
bioblend.galaxy.client.ConnectionError: Unexpected response from galaxy: 403: API Authentication Required for this request
```

(the debugging hacks used earlier were not needed, the exception this time must have a ``.read()`` method?)

Adding my Tool Shed username and password to the command seems to work:

```
$ planemo shed_upload --shed_target testtoolshed --message "v0.0.8; fixed missing rpy error; relaxed test" --tar ~/toolshed_archives/venn_list_v0.0.8.tar.gz ~/repositories/pico_galaxy/tools/venn_list --shed_email xxx --shed_password xxx
/mnt/galaxy/repositories/planemo/.venv/lib/python2.6/site-packages/requests-2.6.2-py2.6.egg/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Repository venn_list updated successfully.
```

Recommendations:

* Making planemo depend on a more recent bioblend should fix the mystery exception.
* Do something with the exception handling (#116).
* Make ``planemo shed_upload`` check has user credentials (rather than trying the upload and hitting the Error 403)

Meanwhile I need to read about the planemo configuration files and using an API key rather than my Tool Shed password...

**Comment by peterjc** [comment]
This is also working for me with an API key set via ``~/.planemo.yml``.

**Comment by jmchilton** [comment]
We are already depending on the newest bioblend unfortunately.

@afgane Any chance for a new bioblend release? It would improve this error message and it would also allow me to formalize Python 3 support for planemo.

**Comment by jmchilton** [comment]
Python 3 now fully supported - probably not an issue still.
