### ISSUE TITLE
too aggressive in finding potential tool XML files

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/planemo#250]
We can try to reproduce this later, but this is what I think we just saw during a GCC2015 training session using a tool in the user's home directory, say ``~/example.xml``.

When running ``planemo serve`` numerous exception messages were shown from attempting to parse XML files under the home directory as Galaxy tool files. Specifically this included files like ``~/.somelibrary/blah.xml``.

We should probably not recurse into hidden folders.

**Comment by peterjc** [comment]
This also affects the Galaxy Tool Shed special XML files ``repository_dependencies.xml`` and ``tool_dependencies.xml``

e.g. https://travis-ci.org/peterjc/galaxy_mira/jobs/79507693

```
$ planemo test ${TRAVIS_BUILD_DIR}/tools/
...
galaxy.tools.toolbox.base ERROR 2015-09-09 16:43:12,156 Failed to load potential tool /home/travis/build/peterjc/galaxy_mira/tools/mira4_0/repository_dependencies.xml.
Traceback (most recent call last):
  File "/home/travis/build/peterjc/galaxy_mira/galaxy-master/lib/galaxy/tools/toolbox/base.py", line 707, in quick_load
    tool = self.load_tool( tool_file )
  File "/home/travis/build/peterjc/galaxy_mira/galaxy-master/lib/galaxy/tools/toolbox/base.py", line 735, in load_tool
    tool = self.create_tool( config_file=config_file, repository_id=repository_id, guid=guid, **kwds )
  File "/home/travis/build/peterjc/galaxy_mira/galaxy-master/lib/galaxy/tools/__init__.py", line 159, in create_tool
    tool = ToolClass( config_file, tool_source, self.app, guid=guid, repository_id=repository_id, **kwds )
  File "/home/travis/build/peterjc/galaxy_mira/galaxy-master/lib/galaxy/tools/__init__.py", line 487, in __init__
    raise e
Exception: Missing tool 'name'
galaxy.tools.toolbox.base ERROR 2015-09-09 16:43:12,157 Failed to load potential tool /home/travis/build/peterjc/galaxy_mira/tools/mira4_0/tool_dependencies.xml.
Traceback (most recent call last):
  File "/home/travis/build/peterjc/galaxy_mira/galaxy-master/lib/galaxy/tools/toolbox/base.py", line 707, in quick_load
    tool = self.load_tool( tool_file )
  File "/home/travis/build/peterjc/galaxy_mira/galaxy-master/lib/galaxy/tools/toolbox/base.py", line 735, in load_tool
    tool = self.create_tool( config_file=config_file, repository_id=repository_id, guid=guid, **kwds )
  File "/home/travis/build/peterjc/galaxy_mira/galaxy-master/lib/galaxy/tools/__init__.py", line 159, in create_tool
    tool = ToolClass( config_file, tool_source, self.app, guid=guid, repository_id=repository_id, **kwds )
  File "/home/travis/build/peterjc/galaxy_mira/galaxy-master/lib/galaxy/tools/__init__.py", line 487, in __init__
    raise e
Exception: Missing tool 'name'
```

**Comment by jmchilton** [comment]
I believe this has been fixed with enhancements to Galaxy's ``galaxy.tools.loader_directory``'s  ``looks_like_a_tool``.

```
TOOL_REGEX = re.compile(r"<tool\s")

...


def looks_like_a_tool(path, invalid_names=[], enable_beta_formats=False):
    """ Whether true in a strict sense or not, lets say the intention and
    purpose of this procedure is to serve as a filter - all valid tools must
    "looks_like_a_tool" but not everything that looks like a tool is actually
    a valid tool.

    invalid_names may be supplid in the context of the tool shed to quickly
    rule common tool shed XML files.
    """
    looks = False

    if os.path.basename(path) in invalid_names:
        return False

    if looks_like_a_tool_xml(path):
        looks = True

    if not looks and enable_beta_formats:
        for tool_checker in BETA_TOOL_CHECKERS.values():
            if tool_checker(path):
                looks = True
                break

    return looks


def looks_like_a_tool_xml(path):
    full_path = os.path.abspath(path)

    if not full_path.endswith(".xml"):
        return False

    if not os.path.getsize(full_path):
        return False

    if(checkers.check_binary(full_path) or
       checkers.check_image(full_path) or
       checkers.check_gzip(full_path)[0] or
       checkers.check_bz2(full_path)[0] or
       checkers.check_zip(full_path)):
        return False

    with open(path, "r") as f:
        start_contents = f.read(5 * 1024)
        if TOOL_REGEX.search(start_contents):
            return True

    return False
```

**Comment by peterjc** [comment]
Yes, that should cut down on the false positives massively - thanks John.
