### ISSUE TITLE
AttributeError: 'module' object has no attribute 'is_tool_load_error'

### ISSUE THREAD

**Issue by remimarenco** [galaxyproject/planemo#324]
Hi!

Firstly, thank you for this tool! It can help us a lot improving our tool development's workflow.

Here is the description of the issue:

I am trying to install Planemo in a virtual environment. Usual stuff. It installs properly, but when I want to launch Planemo (any command), I get this output:

```
(env_galaxy_clean)[fnc-galaxy@bioinf-gal001 galaxy]$ planemo t
Traceback (most recent call last):
  File "/data/galaxy/env_galaxy_clean/bin/planemo", line 11, in <module>
    sys.exit(planemo())
  File "/data/galaxy/env_galaxy_clean/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/data/galaxy/env_galaxy_clean/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/data/galaxy/env_galaxy_clean/lib/python2.7/site-packages/click/core.py", line 1022, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/data/galaxy/env_galaxy_clean/lib/python2.7/site-packages/click/core.py", line 1061, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/data/galaxy/env_galaxy_clean/lib/python2.7/site-packages/planemo/cli.py", line 101, in get_command
    return name_to_command(name)
  File "/data/galaxy/env_galaxy_clean/lib/python2.7/site-packages/planemo/cli.py", line 86, in name_to_command
    mod = __import__(mod_name, None, None, ['cli'])
  File "/data/galaxy/env_galaxy_clean/lib/python2.7/site-packages/planemo/commands/cmd_test.py", line 7, in <module>
    from planemo import galaxy_config
  File "/data/galaxy/env_galaxy_clean/lib/python2.7/site-packages/planemo/galaxy_config.py", line 23, in <module>
    from planemo.shed import tool_shed_url
  File "/data/galaxy/env_galaxy_clean/lib/python2.7/site-packages/planemo/shed/__init__.py", line 28, in <module>
    from planemo.tools import load_tool_elements_from_path
  File "/data/galaxy/env_galaxy_clean/lib/python2.7/site-packages/planemo/tools.py", line 7, in <module>
    is_tool_load_error = loader_directory.is_tool_load_error
AttributeError: 'module' object has no attribute 'is_tool_load_error'
```

> Your operating system name and version, versions of other relevant software such as Galaxy or Docker.

CentOS release 6.7 (Final)

> Any details about your local setup that might be helpful in troubleshooting.

We have a virtualenv at the same level than the Galaxy folder. We are using it for Planemo and Galaxy.

> Detailed steps to reproduce the bug.

This is the tricky part. I have absolutely no idea how to reproduce it. I have recreated a virtualenv, and planemo is installing and running properly :s.

I tried to uninstall all the Planemo package dependencies, and let pip/Planemo install them, and I still have the same error :s.

Thanks for the help/resolve on this!

**Comment by jmchilton** [comment]
Best guess is this has something to do with running planemo from inside of Galaxy's root - is it picking up Galaxy's ``galaxy.tool`` module instead of planemo's.

**Comment by remimarenco** [comment]
Thanks for the answer @jmchilton ! That is quite weird as I can place myself in any part of my server, the error will still happen (outside of the Galaxy's root) :s.

**Comment by jmchilton** [comment]
We've improved the packaging a lot - hopefully not still an issue.
