### ISSUE TITLE
SPARQLWrapper-1.7.3 breaks planemo install

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/planemo#365]
```
$ git pull
$ pip install --upgrade .
...
Collecting SPARQLWrapper (from rdflib>=4.2.0->cwltool->planemo==0.19.1.dev0)
  Downloading SPARQLWrapper-1.7.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-mFHok2/SPARQLWrapper/setup.py", line 45, in <module>
        requirements = list(parse_requirements('requirements.txt', session=PipSession()))
      File "/home/soranzon/software/galaxyproject_planemo/.venv/local/lib/python2.7/site-packages/pip/req/req_file.py", line 77, in parse_requirements
        filename, comes_from=comes_from, session=session
      File "/home/soranzon/software/galaxyproject_planemo/.venv/local/lib/python2.7/site-packages/pip/download.py", line 416, in get_file_content
        'Could not open requirements file: %s' % str(exc)
    pip.exceptions.InstallationError: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
```

See https://github.com/RDFLib/sparqlwrapper/issues/66 .

**Comment by wikier** [comment]
@nsoranzo [SPARQLWrapper 1.7.4](https://pypi.python.org/pypi/SPARQLWrapper/1.7.4) is out fixing such detail

**Comment by nsoranzo** [comment]
Thanks @wikier!
