### ISSUE TITLE
planemo test broken with conda python

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/planemo#399]
Not quite sure if this is an issue with conda, galaxy or planemo ...
```
(/home/galaxy/miniconda)galaxy@vm0148:~$ conda create --name python_2_7_10 python==2.7.10
Fetching package metadata: ........
Solving package specifications: ........
Package plan for installation in environment /home/galaxy/miniconda/envs/python_2_7_10:

The following NEW packages will be INSTALLED:

    openssl:    1.0.2d-0     
    pip:        7.1.2-py27_0 
    python:     2.7.10-2     
    readline:   6.2-2        
    setuptools: 19.1.1-py27_0
    sqlite:     3.8.4.1-1    
    tk:         8.5.18-0     
    wheel:      0.26.0-py27_1
    zlib:       1.2.8-0      

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ]|#############################################################################################################################################################################| 100%
#
# To activate this environment, use:
# $ source activate python_2_7_10
#
# To deactivate this environment, use:
# $ source deactivate
#
(/home/galaxy/miniconda)galaxy@vm0148:~$ source activate python_2_7_10
discarding /home/galaxy/miniconda/bin from PATH
prepending /home/galaxy/miniconda/envs/python_2_7_10/bin to PATH
(python_2_7_10)galaxy@vm0148:~$ pip install planemo
Collecting planemo
  Using cached planemo-0.21.1-py2.py3-none-any.whl
Collecting cwltool (from planemo)
Collecting PyGithub (from planemo)
Collecting Click (from planemo)
  Using cached click-6.2-py2.py3-none-any.whl
Collecting virtualenv (from planemo)
  Using cached virtualenv-13.1.2-py2.py3-none-any.whl
Collecting jinja2 (from planemo)
  Using cached Jinja2-2.8-py2.py3-none-any.whl
Collecting six>=1.7.0 (from planemo)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting docutils (from planemo)
Collecting glob2 (from planemo)
Collecting pyyaml (from planemo)
  Using cached PyYAML-3.11.tar.gz
Collecting bioblend (from planemo)
Collecting rdflib-jsonld>=0.3.0 (from cwltool->planemo)
Collecting requests (from cwltool->planemo)
  Using cached requests-2.9.1-py2.py3-none-any.whl
Collecting shellescape (from cwltool->planemo)
  Using cached shellescape-3.4.1-py2.py3-none-any.whl
Collecting rdflib>=4.2.0 (from cwltool->planemo)
Collecting schema-salad==1.4.20160108200836 (from cwltool->planemo)
Collecting MarkupSafe (from jinja2->planemo)
Collecting requests-toolbelt (from bioblend->planemo)
  Using cached requests_toolbelt-0.5.1-py2.py3-none-any.whl
Collecting boto>=2.9.7 (from bioblend->planemo)
  Using cached boto-2.38.0-py2.py3-none-any.whl
Collecting html5lib (from rdflib>=4.2.0->cwltool->planemo)
Collecting SPARQLWrapper (from rdflib>=4.2.0->cwltool->planemo)
Collecting pyparsing (from rdflib>=4.2.0->cwltool->planemo)
  Using cached pyparsing-2.0.7-py2.py3-none-any.whl
Collecting isodate (from rdflib>=4.2.0->cwltool->planemo)
Collecting mistune (from schema-salad==1.4.20160108200836->cwltool->planemo)
  Using cached mistune-0.7.1-py2.py3-none-any.whl
Collecting avro (from schema-salad==1.4.20160108200836->cwltool->planemo)
Collecting keepalive>=0.5 (from SPARQLWrapper->rdflib>=4.2.0->cwltool->planemo)
Building wheels for collected packages: pyyaml
  Running setup.py bdist_wheel for pyyaml
  Stored in directory: /home/galaxy/.cache/pip/wheels/fa/db/f6/dee55793d344f1706dc4a5a693298f0115241d1085cc212364
Successfully built pyyaml
Installing collected packages: six, html5lib, keepalive, SPARQLWrapper, pyparsing, isodate, rdflib, rdflib-jsonld, requests, shellescape, mistune, avro, pyyaml, schema-salad, cwltool, PyGithub, Click, virtualenv, MarkupSafe, jinja2, docutils, glob2, requests-toolbelt, boto, bioblend, planemo
Successfully installed Click-6.2 MarkupSafe-0.23 PyGithub-1.26.0 SPARQLWrapper-1.7.6 avro-1.7.7 bioblend-0.7.0 boto-2.38.0 cwltool-1.0.20160108200940 docutils-0.12 glob2-0.4.1 html5lib-0.9999999 isodate-0.5.4 jinja2-2.8 keepalive-0.5 mistune-0.7.1 planemo-0.21.1 pyparsing-2.0.7 pyyaml-3.11 rdflib-4.2.1 rdflib-jsonld-0.3 requests-2.9.1 requests-toolbelt-0.5.1 schema-salad-1.4.20160108200836 shellescape-3.4.1 six-1.10.0 virtualenv-13.1.2
(python_2_7_10)galaxy@vm0148:~$ ls
environment.yml  galaxy  miniconda  pip_list  tools-artbio
(python_2_7_10)galaxy@vm0148:~$ cd tools-artbio/
(python_2_7_10)galaxy@vm0148:~/tools-artbio$ cd tools/yac_clipper/
(python_2_7_10)galaxy@vm0148:~/tools-artbio/tools/yac_clipper$ planemo test
git --git-dir /home/galaxy/.planemo/gx_repo fetch >/dev/null 2>&1
cd /tmp/tmp4dmieR; git clone  --branch 'dev' '/home/galaxy/.planemo/gx_repo' 'galaxy-dev'; cd galaxy-dev; if [ -d .venv ] || [ -f dist-eggs.ini ]; then GALAXY_VIRTUAL_ENV=.venv;  else GALAXY_VIRTUAL_ENV=/home/galaxy/.planemo/gx_venv; fi; export GALAXY_VIRTUAL_ENV; if [ ! -e $GALAXY_VIRTUAL_ENV ]; then /home/galaxy/miniconda/envs/python_2_7_10/bin/virtualenv -p /home/galaxy/miniconda/envs/python_2_7_10/bin/python2.7 $GALAXY_VIRTUAL_ENV; fi; [ -e $GALAXY_VIRTUAL_ENV ] && . $GALAXY_VIRTUAL_ENV/bin/activate; COMMON_STARTUP_ARGS=; $(grep -q 'skip-venv' run_tests.sh) && COMMON_STARTUP_ARGS="--skip-venv --dev-wheels"; export COMMON_STARTUP_ARGS; echo "Set COMMON_STARTUP_ARGS to ${COMMON_STARTUP_ARGS}"; ./scripts/common_startup.sh ${COMMON_STARTUP_ARGS}
Cloning into 'galaxy-dev'...
done.
Set COMMON_STARTUP_ARGS to --skip-venv --dev-wheels
Initializing config/migrated_tools_conf.xml from migrated_tools_conf.xml.sample
Initializing config/shed_tool_conf.xml from shed_tool_conf.xml.sample
Initializing config/shed_tool_data_table_conf.xml from shed_tool_data_table_conf.xml.sample
Initializing config/shed_data_manager_conf.xml from shed_data_manager_conf.xml.sample
Initializing lib/tool_shed/scripts/bootstrap_tool_shed/user_info.xml from user_info.xml.sample
Initializing tool-data/shared/ucsc/builds.txt from builds.txt.sample
Initializing tool-data/shared/ucsc/manual_builds.txt from manual_builds.txt.sample
Initializing tool-data/shared/ucsc/ucsc_build_sites.txt from ucsc_build_sites.txt.sample
Initializing tool-data/shared/igv/igv_build_sites.txt from igv_build_sites.txt.sample
Initializing tool-data/shared/rviewer/rviewer_build_sites.txt from rviewer_build_sites.txt.sample
Initializing tool-data/add_scores.loc from add_scores.loc.sample
Initializing tool-data/alignseq.loc from alignseq.loc.sample
Initializing tool-data/all_fasta.loc from all_fasta.loc.sample
Initializing tool-data/bfast_indexes.loc from bfast_indexes.loc.sample
Initializing tool-data/binned_scores.loc from binned_scores.loc.sample
Initializing tool-data/codingSnps.loc from codingSnps.loc.sample
Initializing tool-data/encode_datasets.loc from encode_datasets.loc.sample
Initializing tool-data/faseq.loc from faseq.loc.sample
Initializing tool-data/funDo.loc from funDo.loc.sample
Initializing tool-data/liftOver.loc from liftOver.loc.sample
Initializing tool-data/maf_index.loc from maf_index.loc.sample
Initializing tool-data/maf_pairwise.loc from maf_pairwise.loc.sample
Initializing tool-data/microbial_data.loc from microbial_data.loc.sample
Initializing tool-data/mosaik_index.loc from mosaik_index.loc.sample
Initializing tool-data/ngs_sim_fasta.loc from ngs_sim_fasta.loc.sample
Initializing tool-data/perm_base_index.loc from perm_base_index.loc.sample
Initializing tool-data/perm_color_index.loc from perm_color_index.loc.sample
Initializing tool-data/phastOdds.loc from phastOdds.loc.sample
Initializing tool-data/picard_index.loc from picard_index.loc.sample
Initializing tool-data/quality_scores.loc from quality_scores.loc.sample
Initializing tool-data/regions.loc from regions.loc.sample
Initializing tool-data/sequence_index_base.loc from sequence_index_base.loc.sample
Initializing tool-data/sequence_index_color.loc from sequence_index_color.loc.sample
Initializing tool-data/sift_db.loc from sift_db.loc.sample
Initializing tool-data/srma_index.loc from srma_index.loc.sample
Initializing tool-data/twobit.loc from twobit.loc.sample
Initializing static/welcome.html from welcome.html.sample
Requirement already satisfied (use --upgrade to upgrade): numpy in /home/galaxy/.planemo/gx_venv/lib/python2.7/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): bx-python in /home/galaxy/.planemo/gx_venv/lib/python2.7/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe in /home/galaxy/.planemo/gx_venv/lib/python2.7/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): PyYAML in /home/galaxy/.planemo/gx_venv/lib/python2.7/site-packages (from -r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): SQLAlchemy in /home/galaxy/.planemo/gx_venv/lib/python2.7/site-packages (from -r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): mercurial<3.5 in /home/galaxy/.planemo/gx_venv/lib/python2.7/site-packages (from -r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): pycrypto in /home/galaxy/.planemo/gx_venv/lib/python2.7/site-packages (from -r requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): Paste in /home/galaxy/.planemo/gx_venv/lib/python2.7/site-packages (from -r requirements.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): PasteDeploy in /home/galaxy/.planemo/gx_venv/lib/python2.7/site-packages (from -r requirements.txt (line 9))
Requirement already satisfied (use --upgrade to upgrade): docutils in /home/galaxy/.planemo/gx_venv/lib/python2.7/site-packages (from -r requirements.txt (line 10))
Requirement already satisfied (use --upgrade to upgrade): wchartype in /home/galaxy/.planemo/gx_venv/lib/python2.7/site-packages (from -r requirements.txt (line 11))
Requirement already satisfied (use --upgrade to upgrade): repoze.lru in /home/galaxy/.planemo/gx_venv/lib/python2.7/site-packages (from -r requirements.txt (line 12))
Requirement already satisfied (use --upgrade to upgrade): Routes in /home/galaxy/.planemo/gx_venv/lib/python2.7/site-packages (from -r requirements.txt (line 13))
Requirement already satisfied (use --upgrade to upgrade): WebOb in /home/galaxy/.planemo/gx_venv/lib/python2.7/site-packages (from -r requirements.txt (line 14))
Requirement already satisfied (use --upgrade to upgrade): WebHelpers in /home/galaxy/.planemo/gx_venv/lib/python2.7/site-packages (from -r requirements.txt (line 15))
Requirement already satisfied (use --upgrade to upgrade): Mako in /home/galaxy/.planemo/gx_venv/lib/python2.7/site-packages (from -r requirements.txt (line 16))
Requirement already satisfied (use --upgrade to upgrade): pytz in /home/galaxy/.planemo/gx_venv/lib/python2.7/site-packages (from -r requirements.txt (line 17))
Requirement already satisfied (use --upgrade to upgrade): Babel in /home/galaxy/.planemo/gx_venv/lib/python2.7/site-packages (from -r requirements.txt (line 18))
Requirement already satisfied (use --upgrade to upgrade): Beaker in /home/galaxy/.planemo/gx_venv/lib/python2.7/site-packages (from -r requirements.txt (line 19))
Requirement already satisfied (use --upgrade to upgrade): Cheetah in /home/galaxy/.planemo/gx_venv/lib/python2.7/site-packages (from -r requirements.txt (line 20))
Requirement already satisfied (use --upgrade to upgrade): bioblend in /home/galaxy/.planemo/gx_venv/lib/python2.7/site-packages (from -r requirements.txt (line 21))
Requirement already satisfied (use --upgrade to upgrade): boto in /home/galaxy/.planemo/gx_venv/lib/python2.7/site-packages (from -r requirements.txt (line 22))
Requirement already satisfied (use --upgrade to upgrade): requests in /home/galaxy/.planemo/gx_venv/lib/python2.7/site-packages (from -r requirements.txt (line 23))
Requirement already satisfied (use --upgrade to upgrade): kombu in /home/galaxy/.planemo/gx_venv/lib/python2.7/site-packages (from -r requirements.txt (line 24))
Requirement already satisfied (use --upgrade to upgrade): sqlalchemy-migrate in /home/galaxy/.planemo/gx_venv/lib/python2.7/site-packages (from -r requirements.txt (line 25))
Requirement already satisfied (use --upgrade to upgrade): decorator in /home/galaxy/.planemo/gx_venv/lib/python2.7/site-packages (from -r requirements.txt (line 26))
Requirement already satisfied (use --upgrade to upgrade): Tempita in /home/galaxy/.planemo/gx_venv/lib/python2.7/site-packages (from -r requirements.txt (line 27))
Requirement already satisfied (use --upgrade to upgrade): sqlparse in /home/galaxy/.planemo/gx_venv/lib/python2.7/site-packages (from -r requirements.txt (line 28))
Requirement already satisfied (use --upgrade to upgrade): six in /home/galaxy/.planemo/gx_venv/lib/python2.7/site-packages (from -r requirements.txt (line 29))
Requirement already satisfied (use --upgrade to upgrade): Parsley in /home/galaxy/.planemo/gx_venv/lib/python2.7/site-packages (from -r requirements.txt (line 30))
Requirement already satisfied (use --upgrade to upgrade): nose in /home/galaxy/.planemo/gx_venv/lib/python2.7/site-packages (from -r requirements.txt (line 31))
Requirement already satisfied (use --upgrade to upgrade): SVGFig in /home/galaxy/.planemo/gx_venv/lib/python2.7/site-packages (from -r requirements.txt (line 32))
Requirement already satisfied (use --upgrade to upgrade): Fabric in /home/galaxy/.planemo/gx_venv/lib/python2.7/site-packages (from -r requirements.txt (line 33))
Requirement already satisfied (use --upgrade to upgrade): Whoosh==2.4.1+gx1 in /home/galaxy/.planemo/gx_venv/lib/python2.7/site-packages (from -r requirements.txt (line 34))
Requirement already satisfied (use --upgrade to upgrade): pysam==0.8.3+gx1 in /home/galaxy/.planemo/gx_venv/lib/python2.7/site-packages (from -r requirements.txt (line 35))
Requirement already satisfied (use --upgrade to upgrade): Markdown>=2.0.1 in /home/galaxy/.planemo/gx_venv/lib/python2.7/site-packages (from Cheetah->-r requirements.txt (line 20))
Requirement already satisfied (use --upgrade to upgrade): requests-toolbelt in /home/galaxy/.planemo/gx_venv/lib/python2.7/site-packages (from bioblend->-r requirements.txt (line 21))
Requirement already satisfied (use --upgrade to upgrade): amqp<2.0,>=1.4.5 in /home/galaxy/.planemo/gx_venv/lib/python2.7/site-packages (from kombu->-r requirements.txt (line 24))
Requirement already satisfied (use --upgrade to upgrade): anyjson>=0.3.3 in /home/galaxy/.planemo/gx_venv/lib/python2.7/site-packages (from kombu->-r requirements.txt (line 24))
Requirement already satisfied (use --upgrade to upgrade): pbr<2.0,>=1.3 in /home/galaxy/.planemo/gx_venv/lib/python2.7/site-packages (from sqlalchemy-migrate->-r requirements.txt (line 25))
Requirement already satisfied (use --upgrade to upgrade): paramiko>=1.10 in /home/galaxy/.planemo/gx_venv/lib/python2.7/site-packages (from Fabric->-r requirements.txt (line 33))
Requirement already satisfied (use --upgrade to upgrade): ecdsa>=0.11 in /home/galaxy/.planemo/gx_venv/lib/python2.7/site-packages (from paramiko>=1.10->Fabric->-r requirements.txt (line 33))
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/tmp4dmieR/galaxy-dev/lib/galaxy/dependencies/__init__.py", line 10, in <module>
    from galaxy.util import asbool
  File "/tmp/tmp4dmieR/galaxy-dev/lib/galaxy/util/__init__.py", line 18, in <module>
    import smtplib
  File "/home/galaxy/miniconda/lib/python2.7/smtplib.py", line 48, in <module>
    import hmac
  File "/home/galaxy/miniconda/lib/python2.7/hmac.py", line 8, in <module>
    from operator import _compare_digest as compare_digest
ImportError: cannot import name _compare_digest
Testing using galaxy_root /tmp/tmp4dmieR/galaxy-dev
Testing tools with command [cd /tmp/tmp4dmieR/galaxy-dev; COMMON_STARTUP_ARGS=; $(grep -q 'skip-venv' run_tests.sh) && COMMON_STARTUP_ARGS="--skip-venv --skip-common-startup"; export COMMON_STARTUP_ARGS; echo "Set COMMON_STARTUP_ARGS to ${COMMON_STARTUP_ARGS}"; if [ -d .venv ] || [ -f dist-eggs.ini ]; then GALAXY_VIRTUAL_ENV=.venv;  else GALAXY_VIRTUAL_ENV=/home/galaxy/.planemo/gx_venv; fi; export GALAXY_VIRTUAL_ENV; if [ ! -e $GALAXY_VIRTUAL_ENV ]; then /home/galaxy/miniconda/envs/python_2_7_10/bin/virtualenv -p /home/galaxy/miniconda/envs/python_2_7_10/bin/python2.7 $GALAXY_VIRTUAL_ENV; fi; [ -e $GALAXY_VIRTUAL_ENV ] && . $GALAXY_VIRTUAL_ENV/bin/activate; sh run_tests.sh $COMMON_STARTUP_ARGS --report_file /home/galaxy/tools-artbio/tools/yac_clipper/tool_test_output.html --xunit_report_file /tmp/tmp4dmieR/xunit.xml --structured_data_report_file /home/galaxy/tools-artbio/tools/yac_clipper/tool_test_output.json functional.test_toolbox]
Set COMMON_STARTUP_ARGS to --skip-venv --skip-common-startup
Traceback (most recent call last):
  File "./scripts/functional_tests.py", line 17, in <module>
    from base.tool_shed_util import parse_tool_panel_config
  File "/tmp/tmp4dmieR/galaxy-dev/test/base/tool_shed_util.py", line 8, in <module>
    from galaxy.util import parse_xml
  File "/tmp/tmp4dmieR/galaxy-dev/lib/galaxy/util/__init__.py", line 18, in <module>
    import smtplib
  File "/home/galaxy/miniconda/lib/python2.7/smtplib.py", line 48, in <module>
    import hmac
  File "/home/galaxy/miniconda/lib/python2.7/hmac.py", line 8, in <module>
    from operator import _compare_digest as compare_digest
ImportError: cannot import name _compare_digest
Cannot locate xUnit report option for tests - update Galaxy for more detailed breakdown.
Warning: Problem with target Galaxy, it did not produce a structured test results files - summary information and planemo reports will be incorrect.
Traceback (most recent call last):
  File "/home/galaxy/miniconda/envs/python_2_7_10/bin/planemo", line 11, in <module>
    sys.exit(planemo())
  File "/home/galaxy/miniconda/envs/python_2_7_10/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/galaxy/miniconda/envs/python_2_7_10/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/galaxy/miniconda/envs/python_2_7_10/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/galaxy/miniconda/envs/python_2_7_10/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/galaxy/miniconda/envs/python_2_7_10/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/galaxy/miniconda/envs/python_2_7_10/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/home/galaxy/miniconda/envs/python_2_7_10/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/galaxy/miniconda/envs/python_2_7_10/lib/python2.7/site-packages/planemo/commands/cmd_test.py", line 59, in cli
    return_value = run_in_config(ctx, config, **kwds)
  File "/home/galaxy/miniconda/envs/python_2_7_10/lib/python2.7/site-packages/planemo/galaxy_test/actions.py", line 83, in run_in_config
    return_code,
  File "/home/galaxy/miniconda/envs/python_2_7_10/lib/python2.7/site-packages/planemo/galaxy_test/structures.py", line 166, in __init__
    sd = StructuredData(output_json_path)
  File "/home/galaxy/miniconda/envs/python_2_7_10/lib/python2.7/site-packages/planemo/galaxy_test/structures.py", line 78, in __init__
    self.structured_data = structured_data
UnboundLocalError: local variable 'structured_data' referenced before assignment
(python_2_7_10)galaxy@vm0148:~/tools-artbio/tools/yac_clipper$ 
```

**Comment by gregvonkuster** [comment]
This exception is the one I've been seeing for quite some time now - I don't think it is related to conda.

**Comment by mvdbeek** [comment]
I'm using VMs provided by the IFB. If I don't install conda everything works fine ... but indeed, it might be related to python-2.7.11 that conda is shipping with. Or other things ... I'm at a loss, but if this works I could easily test our tools in travis.

**Comment by jmchilton** [comment]
@natefoo added some parameters to Galaxy's scripts to fix this, I need to adapt planemo to them.

**Comment by jmchilton** [comment]
xref #377  https://github.com/galaxyproject/galaxy/issues/1150

**Comment by jmchilton** [comment]
Instructions for running Galaxy tools in a conda with planemo here  https://github.com/galaxyproject/planemo/commit/9f3957d3552153cd76ec34697e9857be13a24e73, though that is for planemo installed via brew or in a virtualenv.

If for some reason you want to install planemo into a conda environment, then Galaxy needs to already have its virtual environment setup and cannot reuse the same conda environment (planemo depends on galaxy-lib which conflicts with galaxy). So just clone galaxy (dev or release_16.01), run run.sh once, and then call planemo with --galaxy_root.

Does this make sense - are these restrictions fair? If not, we can keep the issue open and try to improve the conda+galaxy+planemo story

**Comment by gregvonkuster** [comment]
What if you've installed planemo via pip?

**Comment by jmchilton** [comment]
An expanded summary of the state of planemo, Galaxy, conda:

https://github.com/galaxyproject/planemo/commit/9f3957d3552153cd76ec34697e9857be13a24e73#commitcomment-15445672

**Comment by mvdbeek** [comment]
awesome, thanks @jmchilton , I'll give it a go.

**Comment by yhoogstrate** [comment]
Here `planeme test` crashes with the error reported above by @mvdbeek and otherwise I get this error (planemo 0.22.2, via homebrew):

![screenshot from 2016-01-26 08-52-26 - 1](https://cloud.githubusercontent.com/assets/2264697/12575121/3f1eab1e-c40a-11e5-91d6-83adca84ea89.png)

**Comment by jmchilton** [comment]
You've placed galaxy-lib in the same Python environment as Galaxy. Galaxy and Planemo must be installed in different environments currently.

**Comment by jmchilton** [comment]
Closing this for now, I'll keep working on the galaxy-lib problem - there doesn't seem to be a clean fix.
