### ISSUE TITLE
shed_create raises an exception

### ISSUE THREAD

**Issue by tiagoantao** [galaxyproject/planemo#423]
When creating a repository on the test toolshed, I got (look at the force_repository_creation key at the end):

```
package_stacks_1_37$ planemo shed_create --shed_target testtoolshed
Repository created
cd '/home/tiago_antao/Dropbox/soft/galaxy-stacks/packages/package_stacks_1_37' && git rev-parse HEAD
cd '/home/tiago_antao/Dropbox/soft/galaxy-stacks/packages/package_stacks_1_37' && git diff --quiet
Could not update package_stacks_1_37
('Connection broken: IncompleteRead(5788 bytes read, 4452 more expected)', IncompleteRead(5788 bytes read, 4452 more expected))
Traceback (most recent call last):
  File "/home/tiago_antao/miniconda/envs/planemo/bin/planemo", line 6, in <module>
    sys.exit(planemo.cli.planemo())
  File "/home/tiago_antao/miniconda/envs/planemo/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/tiago_antao/miniconda/envs/planemo/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/tiago_antao/miniconda/envs/planemo/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/tiago_antao/miniconda/envs/planemo/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/tiago_antao/miniconda/envs/planemo/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/tiago_antao/miniconda/envs/planemo/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/home/tiago_antao/miniconda/envs/planemo/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/tiago_antao/miniconda/envs/planemo/lib/python2.7/site-packages/planemo-0.23.0-py2.7.egg/planemo/commands/cmd_shed_create.py", line 39, in cli
    exit_code = shed.for_each_repository(ctx, create, paths, **kwds)
  File "/home/tiago_antao/miniconda/envs/planemo/lib/python2.7/site-packages/planemo-0.23.0-py2.7.egg/planemo/shed/__init__.py", line 687, in for_each_repository
    function(realized_repository)
  File "/home/tiago_antao/miniconda/envs/planemo/lib/python2.7/site-packages/planemo-0.23.0-py2.7.egg/planemo/commands/cmd_shed_create.py", line 30, in create
    ctx, realized_repository, **kwds
  File "/home/tiago_antao/miniconda/envs/planemo/lib/python2.7/site-packages/planemo-0.23.0-py2.7.egg/planemo/shed/__init__.py", line 243, in upload_repository
    if repo_id is None and kwds["force_repository_creation"]:
KeyError: 'force_repository_creation'
```

**Comment by bgruening** [comment]
As a workaround, just use `shed_update` with the force option this is working for me. Actually I never use the `shed_create` option.

**Comment by tiagoantao** [comment]
I ended up doing that...

**Comment by jmchilton** [comment]
I think this should be mostly better with 3314598800fc92bf7e31e35464d2eb461898ee12 and 358a42c3be70f57a43c80b0f5ad2080a39991ca1.
