### ISSUE TITLE
TypeError: can't concat bytes to str (planemo shed_update)

### ISSUE THREAD

**Issue by remimarenco** [galaxyproject/planemo#438]
Hi :),

Little issue when using `planemo shed_update --check_diff --shed_target testtoolshed` => `TypeError: can't concat bytes to str`

Here are the details asked in the guidelines:
- Your operating system name and version, versions of other relevant software such as Galaxy or Docker.
  - Mac OSX El Capitan / Version 10.11.4
  - Last master Galaxy (16.04)
  - Planemo 0.24.0
- Links to relevant tools.
  - https://testtoolshed.g2.bx.psu.edu/view/remimarenco/hubarchivecreator/b412077866aa
- Detailed steps to reproduce the bug.
  - `planemo shed_update --check_diff --shed_target testtoolshed`

And you get:

`cd '/Users/remi/Google_Drive/Dev/galaxy_remi/tools/hub_assembly' && git rev-parse HEAD
cd '/Users/remi/Google_Drive/Dev/galaxy_remi/tools/hub_assembly' && git diff --quiet
Traceback (most recent call last):
  File "/Users/remi/miniconda3/bin/planemo", line 11, in <module>
    sys.exit(planemo())
  File "/Users/remi/miniconda3/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/remi/miniconda3/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/remi/miniconda3/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/remi/miniconda3/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/remi/miniconda3/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/remi/miniconda3/lib/python3.5/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/Users/remi/miniconda3/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/remi/miniconda3/lib/python3.5/site-packages/planemo/commands/cmd_shed_update.py", line 143, in cli
    exit_code = shed.for_each_repository(ctx, update, paths, **kwds)
  File "/Users/remi/miniconda3/lib/python3.5/site-packages/planemo/shed/__init__.py", line 702, in for_each_repository
    function(realized_repository)
  File "/Users/remi/miniconda3/lib/python3.5/site-packages/planemo/commands/cmd_shed_update.py", line 81, in update
    ctx, realized_repository, **kwds
  File "/Users/remi/miniconda3/lib/python3.5/site-packages/planemo/shed/__init__.py", line 256, in upload_repository
    _update_commit_message(ctx, realized_repository, update_kwds, **kwds)
  File "/Users/remi/miniconda3/lib/python3.5/site-packages/planemo/shed/__init__.py", line 286, in _update_commit_message
    git_rev = realized_repository.git_rev(ctx)
  File "/Users/remi/miniconda3/lib/python3.5/site-packages/planemo/shed/__init__.py", line 1172, in git_rev
    return git.rev_if_git(ctx, self.real_path)
  File "/Users/remi/miniconda3/lib/python3.5/site-packages/planemo/git.py", line 48, in rev_if_git
    the_rev += "-dirty"
TypeError: can't concat bytes to str`

Hope you can find why! Let me know if you need more informations. Thanks!

**Comment by jmchilton** [comment]
Thanks for the issue - as a heads up generally Python 2 is better supported but I like someone close to the project is using Python 3 and finding these issue :smile:.

**Comment by remimarenco** [comment]
:), will keep this in mind thanks!

Working perfectly with Python 2.7 👍

**Comment by jmchilton** [comment]
Python 3 support is now... not broken. Should be closed. -John
