### ISSUE TITLE
Failing Python 3 Tests on Travis

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/planemo#446]
```
======================================================================
ERROR: tests.test_git.test_rev_dirty_if_git
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/galaxyproject/planemo/.tox/py34/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/galaxyproject/planemo/tests/test_git.py", line 30, in test_rev_dirty_if_git
    rev = git.rev_if_git(None, t)
  File "/home/travis/build/galaxyproject/planemo/planemo/git.py", line 48, in rev_if_git
    the_rev += "-dirty"
nose.proxy.TypeError: can't concat bytes to str
-------------------- >> begin captured stdout << ---------------------
[32m[1mcd '/tmp/planemo_tmp_v0mx9c9c' && git init . && git add README && GIT_COMMITTER_DATE='2000-01-01T00:00:00+0000' GIT_COMMITTER_NAME='a' GIT_COMMITTER_EMAIL='a@example.com' git commit --date='2000-01-01T00:00:00+0000' --author='a <a@example.com>' -m 'initial'[0m
[32m[1mcd '/tmp/planemo_tmp_v0mx9c9c' && git rev-parse HEAD[0m
[32m[1mcd '/tmp/planemo_tmp_v0mx9c9c' && git diff --quiet[0m

--------------------- >> end captured stdout << ----------------------

======================================================================
FAIL: test_lint_fails_if_no_doi (tests.test_build_and_lint.BuildAndLintTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/galaxyproject/planemo/tests/test_build_and_lint.py", line 32, in test_lint_fails_if_no_doi
    self._check_lint(exit_code=1)
  File "/home/travis/build/galaxyproject/planemo/tests/test_build_and_lint.py", line 36, in _check_lint
    self._check_exit_code(lint_cmd, exit_code=exit_code)
  File "/home/travis/build/galaxyproject/planemo/tests/test_utils.py", line 96, in _check_exit_code
    raise AssertionError(message)
nose.proxy.AssertionError: Planemo command [lint --fail_level warn seqtk_seq.xml] resulted in unexpected exit code [0], expected exit code [1]]. Command output [[32m[1mLinting tool /tmp/tmp0x7rh2z1/seqtk_seq.xml[0m
Applying linter top_level... CHECK
.. CHECK: Tool defines a version.
.. CHECK: Tool defines a name.
.. CHECK: Tool defines an id name.
Applying linter tests... CHECK
.. CHECK: 1 test(s) found.
Applying linter output... CHECK
.. INFO: 1 outputs found.
Applying linter inputs... CHECK
.. INFO: Found 1 input parameters.
Applying linter help... CHECK
.. CHECK: Tool contains help section.
.. CHECK: Help contains valid reStructuredText.
Applying linter command... CHECK
.. INFO: Tool contains a command.
]
-------------------- >> begin captured stdout << ---------------------
[32m[1mTool written to seqtk_seq.xml[0m
[32m[1mNo test-data directory, creating one.[0m
[32m[1mmkdir -p 'test-data'[0m
[32m[1mCopying test-file 2.fastq[0m
[32m[1mcp '2.fastq' 'test-data'[0m
[32m[1mCopying test-file 2.fasta[0m
[32m[1mcp '2.fasta' 'test-data'[0m

[32m[1mLinting tool /tmp/tmp0x7rh2z1/seqtk_seq.xml[0m
Applying linter top_level... CHECK
.. CHECK: Tool defines a version.
.. CHECK: Tool defines a name.
.. CHECK: Tool defines an id name.
Applying linter tests... CHECK
.. CHECK: 1 test(s) found.
Applying linter output... CHECK
.. INFO: 1 outputs found.
Applying linter inputs... CHECK
.. INFO: Found 1 input parameters.
Applying linter help... CHECK
.. CHECK: Tool contains help section.
.. CHECK: Help contains valid reStructuredText.
Applying linter command... CHECK
.. INFO: Tool contains a command.


--------------------- >> end captured stdout << ----------------------
>>  raise AssertionError('Planemo command [lint --fail_level warn seqtk_seq.xml] resulted in unexpected exit code [0], expected exit code [1]]. Command output [\x1b[32m\x1b[1mLinting tool /tmp/tmp0x7rh2z1/seqtk_seq.xml\x1b[0m\nApplying linter top_level... CHECK\n.. CHECK: Tool defines a version.\n.. CHECK: Tool defines a name.\n.. CHECK: Tool defines an id name.\nApplying linter tests... CHECK\n.. CHECK: 1 test(s) found.\nApplying linter output... CHECK\n.. INFO: 1 outputs found.\nApplying linter inputs... CHECK\n.. INFO: Found 1 input parameters.\nApplying linter help... CHECK\n.. CHECK: Tool contains help section.\n.. CHECK: Help contains valid reStructuredText.\nApplying linter command... CHECK\n.. INFO: Tool contains a command.\n]')


======================================================================
FAIL: tests.test_git.test_rev
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/galaxyproject/planemo/.tox/py34/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/galaxyproject/planemo/tests/test_git.py", line 18, in test_rev
    assert rev == EXPECTED_HELLO_REV, rev
nose.proxy.AssertionError: b'1c36390f585f8baa953548c00fc18c58e32fcf8b'
-------------------- >> begin captured stdout << ---------------------
[32m[1mcd '/tmp/planemo_tmp__yy_aquj' && git init . && git add README && GIT_COMMITTER_DATE='2000-01-01T00:00:00+0000' GIT_COMMITTER_NAME='a' GIT_COMMITTER_EMAIL='a@example.com' git commit --date='2000-01-01T00:00:00+0000' --author='a <a@example.com>' -m 'initial'[0m
[32m[1mcd '/tmp/planemo_tmp__yy_aquj' && git rev-parse HEAD[0m

--------------------- >> end captured stdout << ----------------------
    b'1c36390f585f8baa953548c00fc18c58e32fcf8b' = <module 'planemo.git' from '/home/travis/build/galaxyproject/planemo/planemo/git.py'>.b'1c36390f585f8baa953548c00fc18c58e32fcf8b'(None, '/tmp/planemo_tmp__yy_aquj')
>>  assert b'1c36390f585f8baa953548c00fc18c58e32fcf8b' == '1c36390f585f8baa953548c00fc18c58e32fcf8b', b'1c36390f585f8baa953548c00fc18c58e32fcf8b'
```

xref #438

**Comment by mvdbeek** [comment]
I think these are all working fine by now.
