### ISSUE TITLE
Error with test if --galaxy_root is a fresh Galaxy clone

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/planemo#50]
```
$ planemo test --galaxy_root=$HOME/software/galaxy-central ~/software/galaxyproject_tools-devteam/tools/trimmer/trimmer.xml 
Testing using galaxy_root /home/nicola/software/galaxy-central
Testing tools with command [type deactivate >/dev/null 2>&1 && deactivate; cd /home/nicola/software/galaxy-central; [ -e .venv ] && . .venv/bin/activate; sh run_tests.sh --report_file /home/nicola/software/galaxyproject_planemo/tool_test_output.html --xunit_report_file /tmp/tmpkUivlK/xunit.xml --structured_data_report_file /home/nicola/software/galaxyproject_planemo/tool_test_output.json  functional.test_toolbox]
...
Traceback (most recent call last):
  File "./scripts/functional_tests.py", line 547, in <module>
    sys.exit( main() )
  File "./scripts/functional_tests.py", line 372, in main
    app = UniverseApplication( **kwargs )
  File "/home/nicola/software/galaxy-central/lib/galaxy/app.py", line 66, in __init__
    self._configure_tool_data_tables( from_shed_config=False )
  File "/home/nicola/software/galaxy-central/lib/galaxy/config.py", line 739, in _configure_tool_data_tables
    from_shed_config=from_shed_config )
  File "/home/nicola/software/galaxy-central/lib/galaxy/tools/data/__init__.py", line 77, in load_from_config_file
    tree = util.parse_xml( filename )
  File "/home/nicola/software/galaxy-central/lib/galaxy/util/__init__.py", line 174, in parse_xml
    tree = ElementTree.parse(fname)
  File "/home/nicola/software/galaxy-central/eggs/elementtree-1.2.6_20050316-py2.7.egg/elementtree/ElementTree.py", line 859, in parse
  File "/home/nicola/software/galaxy-central/eggs/elementtree-1.2.6_20050316-py2.7.egg/elementtree/ElementTree.py", line 576, in parse
IOError: [Errno 2] No such file or directory: './config/shed_tool_data_table_conf.xml'
Cannot locate xUnit report option for tests - update Galaxy for more detailed breakdown.
One or more tests failed. See /home/nicola/software/galaxyproject_planemo/tool_test_output.html for detailed breakdown.
```

Probably ```scripts/common_startup.sh``` should be run in the provided galaxy_root , which would create the missing './config/shed_tool_data_table_conf.xml' file.

A similar error is encountered if running ```./run_functional_tests.sh``` in a fresh Galaxy clone, just with a different missing file:

```
Traceback (most recent call last):
  File "./scripts/functional_tests.py", line 547, in <module>
    sys.exit( main() )
  File "./scripts/functional_tests.py", line 372, in main
    app = UniverseApplication( **kwargs )
  File "/home/nicola/software/galaxy-central/lib/galaxy/app.py", line 36, in __init__
    self.config.check()
  File "/home/nicola/software/galaxy-central/lib/galaxy/config.py", line 586, in check
    raise ConfigurationError("Tool config file not found: %s" % path )
galaxy.config.ConfigurationError: Tool config file not found: ./config/shed_tool_conf.xml
```

So maybe this should be better fixed on the Galaxy side.

**Comment by jmchilton** [comment]
Thanks for the bug report @nsoranzo - this should be fixed galaxy-central [eb61b02](https://bitbucket.org/galaxy/galaxy-central/commits/eb61b02da1866c4a7da0f2fa357ce43e6c62b57c).

**Comment by nsoranzo** [comment]
Thanks John, this fixed ```run_tests.sh``` in Galaxy, but for planemo I have a new error:

```
(.venv)$ planemo test --galaxy_root ~/software/galaxy-central/ ~/software/galaxyproject_tools-devteam/tools/cut_columns/
Testing using galaxy_root /home/nicola/software/galaxy-central
Testing tools with command [type deactivate >/dev/null 2>&1 && deactivate; cd /home/nicola/software/galaxy-central; [ -e .venv ] && . .venv/bin/activate; sh run_tests.sh --report_file /home/nicola/software/galaxyproject_planemo/tool_test_output.html --xunit_report_file /tmp/tmpvVRCE6/xunit.xml --structured_data_report_file /home/nicola/software/galaxyproject_planemo/tool_test_output.json  functional.test_toolbox]
Initializing config/migrated_tools_conf.xml from migrated_tools_conf.xml.sample
Initializing config/shed_tool_conf.xml from shed_tool_conf.xml.sample
Initializing config/shed_tool_data_table_conf.xml from shed_tool_data_table_conf.xml.sample
...
Initializing static/welcome.html from welcome.html.sample
Traceback (most recent call last):
  File "./scripts/check_eggs.py", line 42, in <module>
    from galaxy.eggs import Crate
  File "/home/nicola/software/galaxyproject_planemo/.venv/local/lib/python2.7/site-packages/galaxy/eggs/__init__.py", line 7, in <module>
    raise ImportError(PLANEMO_WARNING)
ImportError: It looks like you are trying to use Galaxy from within a Python environment that has planemo installed. Please either deactivate planemo's virtual environment, set up one for Galaxy, or uninstall planemo from this environment.
Some eggs are out of date, attempting to fetch...
Traceback (most recent call last):
  File "./scripts/fetch_eggs.py", line 37, in <module>
    from galaxy.eggs import Crate, EggNotFetchable
  File "/home/nicola/software/galaxyproject_planemo/.venv/local/lib/python2.7/site-packages/galaxy/eggs/__init__.py", line 7, in <module>
    raise ImportError(PLANEMO_WARNING)
ImportError: It looks like you are trying to use Galaxy from within a Python environment that has planemo installed. Please either deactivate planemo's virtual environment, set up one for Galaxy, or uninstall planemo from this environment.
Fetch failed.
...
```

And then there are other import erros later on.

**Comment by jmchilton** [comment]
Yes - I seemed to have actually made things worse in some respects. That startup_common.sh should be there in run_tests.sh for people using Galaxy directly but planemo doesn't like it.

**Comment by jmchilton** [comment]
I believe this should be addressed by pull request #56. Can you update planemo and let me know if the issue persists? It should be fixed now for both pip installs and brew installs of planemo.

**Comment by nsoranzo** [comment]
Unfortunately there are still problems:

```
(.venv)[nicola@angus galaxyproject_planemo]$ planemo test --galaxy_root ~/software/galaxy-central/ ~/software/galaxyproject_tools-devteam/tools/cut_columns/
Testing using galaxy_root /home/nicola/software/galaxy-central
Testing tools with command [cd /home/nicola/software/galaxy-central; [ -e .venv ] && . .venv/bin/activate; sh run_tests.sh --report_file /home/nicola/software/galaxyproject_planemo/tool_test_output.html --xunit_report_file /tmp/tmpA5Zu_K/xunit.xml --structured_data_report_file /home/nicola/software/galaxyproject_planemo/tool_test_output.json  functional.test_toolbox]
Initializing config/migrated_tools_conf.xml from migrated_tools_conf.xml.sample
Initializing config/shed_tool_conf.xml from shed_tool_conf.xml.sample
...
Initializing static/welcome.html from welcome.html.sample
Traceback (most recent call last):
  File "./scripts/check_eggs.py", line 42, in <module>
    from galaxy.eggs import Crate
ImportError: No module named eggs
Some eggs are out of date, attempting to fetch...
Traceback (most recent call last):
  File "./scripts/fetch_eggs.py", line 37, in <module>
    from galaxy.eggs import Crate, EggNotFetchable
ImportError: No module named eggs
Fetch failed.
...
```

Then there are other import errors and in fact only some eggs have been downloaded:

```
[nicola@angus galaxy-central]$ python scripts/check_eggs.py 
Some of your Galaxy eggs are out of date.  Please update them
by running:
  python scripts/fetch_eggs.py 
```

**Comment by jmchilton** [comment]
Can you do a `ls .venv/lib/python2.7/site-packages/` on your virtualenv and post the results for me?

**Comment by nsoranzo** [comment]
```
[nicola@angus galaxyproject_planemo]$ rm -rf .venv/
[nicola@angus galaxyproject_planemo]$ virtualenv .venv
New python executable in .venv/bin/python
Installing setuptools, pip...done.
[nicola@angus galaxyproject_planemo]$ . .venv/bin/activate
(.venv)[nicola@angus galaxyproject_planemo]$ pip install .
...
(.venv)[nicola@angus galaxyproject_planemo]$ ls .venv/lib/python2.7/site-packages/
click                pip-1.5.6.dist-info           setuptools
click-3.3.dist-info  pkg_resources.py              setuptools-3.6.dist-info
easy_install.py      pkg_resources.pyc             six-1.9.0.dist-info
easy_install.pyc     planemo                       six.py
galaxy               planemo-0.1.0-py2.7.egg-info  six.pyc
_markerlib           planemo_ext                   yaml
pip                  PyYAML-3.11-py2.7.egg-info
```

**Comment by jmchilton** [comment]
Hmm.... so the problem is the `galaxy` directory in there and I got the same thing when I installed it the way you did (using `pip install .`) from version `0.1.0`. Can you do a `rm -rf galaxy build dist` from the project directory and then repeat the fresh install? This hopefully isn't needed unless installing from a directory directly this way.

**Comment by nsoranzo** [comment]
Using a fresh planemo git clone on another machine works fine, I will double check on my home laptop later today.

**Comment by nsoranzo** [comment]
I can confirm that the either using a fresh planemo git clone or executing ```git clean -d -x``` before reinstalling with pip fixes the problem.
