### ISSUE TITLE
planemo test returning 0 even if tests failed

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/planemo#516]
e.g. https://travis-ci.org/peterjc/galaxy_mira/jobs/142489886

```
$ planemo test --galaxy_root ${TRAVIS_BUILD_DIR}/galaxy-${GALAXY_BRANCH} --skip_venv tools/
...
----------------------------------------------------------------------
XML: /tmp/tmp92qSd5/xunit.xml
----------------------------------------------------------------------
Ran 17 tests in 362.438s
FAILED (failures=7)
test_driver INFO 2016-07-05 15:36:07,537 Shutting down
test_driver INFO 2016-07-05 15:36:07,537 Shutting down embedded galaxy web server
test_driver INFO 2016-07-05 15:36:07,540 Embedded web server galaxy stopped
test_driver INFO 2016-07-05 15:36:07,541 Stopping application galaxy
galaxy.jobs.handler INFO 2016-07-05 15:36:07,541 sending stop signal to worker thread
galaxy.jobs.handler INFO 2016-07-05 15:36:07,541 job handler queue stopped
galaxy.jobs.runners INFO 2016-07-05 15:36:07,541 TaskRunner: Sending stop signal to 2 worker threads
galaxy.jobs.runners INFO 2016-07-05 15:36:07,541 LocalRunner: Sending stop signal to 4 worker threads
galaxy.jobs.handler INFO 2016-07-05 15:36:07,542 sending stop signal to worker thread
galaxy.jobs.handler INFO 2016-07-05 15:36:07,542 job handler stop queue stopped
test_driver INFO 2016-07-05 15:36:07,543 Application galaxy stopped.
galaxy.jobs.handler INFO 2016-07-05 15:36:08,421 sending stop signal to worker thread
galaxy.jobs.handler INFO 2016-07-05 15:36:08,421 job handler queue stopped
galaxy.jobs.runners INFO 2016-07-05 15:36:08,421 TaskRunner: Sending stop signal to 2 worker threads
galaxy.jobs.runners INFO 2016-07-05 15:36:08,421 LocalRunner: Sending stop signal to 4 worker threads
galaxy.jobs.handler INFO 2016-07-05 15:36:08,421 sending stop signal to worker thread
galaxy.jobs.handler INFO 2016-07-05 15:36:08,421 job handler stop queue stopped
Testing complete. HTML report is in "/home/travis/build/peterjc/galaxy_mira/tool_test_output.html".
There were problems with 7 test(s) - out of 17 test(s) executed. See /home/travis/build/peterjc/galaxy_mira/tool_test_output.html for detailed breakdown.
mira_4_0_bait[0]: passed
mira_4_0_bait[1]: passed
mira_4_0_bait[2]: passed
mira_4_0_convert[0]: passed
mira_4_0_convert[1]: passed
mira_4_0_de_novo[0]: passed
mira_4_0_de_novo[1]: passed
mira_4_0_mapping[0]: passed
mira_4_0_mapping[1]: passed
mira_4_9_bait[0]: failed
mira_4_9_bait[1]: failed
mira_4_9_bait[2]: failed
mira_4_9_bait[3]: failed
mira_4_9_bait[4]: failed
mira_4_9_bait[5]: failed
mira_4_9_bait[6]: failed
mira_assembler[0]: passed
The command "planemo test --galaxy_root ${TRAVIS_BUILD_DIR}/galaxy-${GALAXY_BRANCH} --skip_venv tools/" exited with 0.
Done. Your build exited with 0.
```

This run was using MIRA 4.9.6 but the test output was generated with 4.9.5, so the test failures are not entirely unexpected.

However, ``planemo test`` should have returned a non-zero exit code.

**Comment by peterjc** [comment]
Updated to include the planemo version in the TravisCI output, confirming this is breaking with planemo version 0.27.0:
https://travis-ci.org/peterjc/galaxy_mira/jobs/142501030

**Comment by peterjc** [comment]
Another example from a different repository https://travis-ci.org/peterjc/galaxy_blast/jobs/142483741

```
$ planemo test --galaxy_root ${TRAVIS_BUILD_DIR}/galaxy-${GALAXY_BRANCH} --skip_venv tools/
...
----------------------------------------------------------------------
XML: /tmp/tmpTHU9Wa/xunit.xml
----------------------------------------------------------------------
Ran 70 tests in 1307.423s
FAILED (errors=1, failures=14)
test_driver INFO 2016-07-05 15:34:46,947 Shutting down
test_driver INFO 2016-07-05 15:34:46,947 Shutting down embedded galaxy web server
test_driver INFO 2016-07-05 15:34:46,950 Embedded web server galaxy stopped
test_driver INFO 2016-07-05 15:34:46,950 Stopping application galaxy
galaxy.jobs.handler INFO 2016-07-05 15:34:46,950 sending stop signal to worker thread
galaxy.jobs.handler INFO 2016-07-05 15:34:46,950 job handler queue stopped
galaxy.jobs.runners INFO 2016-07-05 15:34:46,950 TaskRunner: Sending stop signal to 2 worker threads
galaxy.jobs.runners INFO 2016-07-05 15:34:46,951 LocalRunner: Sending stop signal to 4 worker threads
galaxy.jobs.handler INFO 2016-07-05 15:34:46,952 sending stop signal to worker thread
galaxy.jobs.handler INFO 2016-07-05 15:34:46,952 job handler stop queue stopped
test_driver INFO 2016-07-05 15:34:46,952 Application galaxy stopped.
galaxy.jobs.handler INFO 2016-07-05 15:34:47,783 sending stop signal to worker thread
galaxy.jobs.handler INFO 2016-07-05 15:34:47,784 job handler queue stopped
galaxy.jobs.runners INFO 2016-07-05 15:34:47,784 TaskRunner: Sending stop signal to 2 worker threads
galaxy.jobs.runners INFO 2016-07-05 15:34:47,784 LocalRunner: Sending stop signal to 4 worker threads
galaxy.jobs.handler INFO 2016-07-05 15:34:47,784 sending stop signal to worker thread
galaxy.jobs.handler INFO 2016-07-05 15:34:47,784 job handler stop queue stopped
Testing complete. HTML report is in "/home/travis/build/peterjc/galaxy_blast/tool_test_output.html".
There were problems with 15 test(s) - out of 70 test(s) executed. See /home/travis/build/peterjc/galaxy_blast/tool_test_output.html for detailed breakdown.
blast2go[0]: failed
blast_reciprocal_best_hits[0]: passed
blast_reciprocal_best_hits[1]: passed
blast_reciprocal_best_hits[2]: passed
blast_reciprocal_best_hits[3]: passed
blast_reciprocal_best_hits[4]: passed
blast_reciprocal_best_hits[5]: passed
blast_reciprocal_best_hits[6]: passed
blast_reciprocal_best_hits[7]: passed
blast_reciprocal_best_hits[8]: passed
blast_reciprocal_best_hits[9]: passed
blastxml_to_tabular[0]: passed
blastxml_to_tabular[1]: passed
blastxml_to_tabular[2]: passed
blastxml_to_tabular[3]: passed
blastxml_to_tabular[4]: passed
blastxml_to_tabular[5]: passed
blastxml_to_tabular[6]: passed
blastxml_to_tabular[7]: passed
blastxml_to_tabular[8]: passed
blastxml_to_tabular[9]: passed
blastxml_to_tabular[10]: passed
blastxml_to_tabular[11]: passed
blastxml_to_top_descr[0]: passed
blastxml_to_top_descr[1]: passed
ncbi_blastdbcmd_info[0]: failed
ncbi_blastdbcmd_info[1]: failed
ncbi_blastdbcmd_info[2]: failed
ncbi_blastdbcmd_wrapper[0]: failed
ncbi_blastn_wrapper[0]: passed
ncbi_blastn_wrapper[1]: passed
ncbi_blastn_wrapper[2]: passed
ncbi_blastn_wrapper[3]: passed
ncbi_blastn_wrapper[4]: failed
ncbi_blastn_wrapper[5]: failed
ncbi_blastn_wrapper[6]: failed
ncbi_blastn_wrapper[7]: failed
ncbi_blastp_wrapper[0]: passed
ncbi_blastp_wrapper[1]: passed
ncbi_blastp_wrapper[2]: passed
ncbi_blastp_wrapper[3]: passed
ncbi_blastx_wrapper[0]: passed
ncbi_blastx_wrapper[1]: passed
ncbi_blastx_wrapper[2]: passed
ncbi_blastx_wrapper[3]: passed
ncbi_convert2blastmask_wrapper[0]: passed
ncbi_convert2blastmask_wrapper[1]: passed
ncbi_deltablast_wrapper[0]: failed
ncbi_deltablast_wrapper[1]: failed
ncbi_deltablast_wrapper[2]: failed
ncbi_deltablast_wrapper[3]: failed
ncbi_dustmasker_wrapper[0]: passed
ncbi_dustmasker_wrapper[1]: passed
ncbi_dustmasker_wrapper[2]: passed
ncbi_makeblastdb[0]: passed
ncbi_makeblastdb[1]: passed
ncbi_makeblastdb[2]: passed
ncbi_makeblastdb[3]: passed
ncbi_makeprofiledb[0]: passed
ncbi_rpsblast_wrapper[0]: failed
ncbi_rpstblastn_wrapper[0]: failed
ncbi_segmasker_wrapper[0]: passed
ncbi_segmasker_wrapper[1]: passed
ncbi_segmasker_wrapper[2]: passed
ncbi_tblastn_wrapper[0]: passed
ncbi_tblastn_wrapper[1]: passed
ncbi_tblastn_wrapper[2]: passed
ncbi_tblastn_wrapper[3]: passed
ncbi_tblastn_wrapper[4]: passed
ncbi_tblastx_wrapper[0]: passed
The command "planemo test --galaxy_root ${TRAVIS_BUILD_DIR}/galaxy-${GALAXY_BRANCH} --skip_venv tools/" exited with 0.
Done. Your build exited with 0.
```

**Comment by peterjc** [comment]
And a third example, https://travis-ci.org/peterjc/pico_galaxy/jobs/141594841

**Comment by peterjc** [comment]
In https://travis-ci.org/peterjc/pico_galaxy/jobs/148065621 I tried running ``planemo test_reports`` afterwards via:

```
script:
 - cd ${TRAVIS_BUILD_DIR}
 - planemo test --galaxy_root ${TRAVIS_BUILD_DIR}/galaxy-${GALAXY_BRANCH} --skip_venv tools/ ; export RC=$?
 - planemo test_reports --test_output_markdown /dev/stdout tool_test_output.json
 - bash -c "exit $RC"
```

This failed suggesting there is a problem with the JSON output which seems relevant to the confused status?

```
$ planemo test_reports --test_output_markdown /dev/stdout tool_test_output.json
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.9/bin/planemo", line 11, in <module>
    sys.exit(planemo())
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/planemo/cli.py", line 174, in handle_profile_options
    return f(*args, **kwds)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/planemo/commands/cmd_test_reports.py", line 25, in cli
    handle_reports(ctx, test_data.structured_data, kwds)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/planemo/galaxy/test/actions.py", line 152, in handle_reports
    raise exceptions[0]
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'job'
The command "planemo test_reports --test_output_markdown /dev/stdout tool_test_output.json" exited with 1.
```

**Comment by nsoranzo** [comment]
Maybe planemo it's returning as exit status the result of the tests on the latest subdirectory?

**Comment by jmchilton** [comment]
dev and 16.07 was broken from the GCC hackathon until this was merged last Friday https://github.com/galaxyproject/galaxy/pull/2691/files - were you testing against the latest Galaxy dev during that time?

**Comment by nsoranzo** [comment]
Ah, I can't recognise a bug I fixed, LOL!

**Comment by peterjc** [comment]
The problem examples I gave were all Galaxy ``dev`` branch - it looks like Galaxy ``master`` is/was OK.

If ``dev`` was fixed on Friday, then I should get clear failures if I re-run the TravisCI build - I'll try that now. Thanks!

**Comment by jmchilton** [comment]
@peterjc I think this would also explain why your repos were affected but not devteam and IUC.

So two things I'm going to try to do this week to address this - 
 - I'm going to rollback some of planemo's testing in order to get a core set of tests that pass more reliably. In the run up to the GCC - I put some features into planemo that had tests that don't yet reliably pass and so I've grown accustom to a failing planemo Travis builds. This isn't acceptable - and I should not have done this.
 - https://github.com/galaxyproject/galaxy/issues/2642 I've already started work on a community-driven infrastructure for QA of Galaxy - I believe if Galaxy were being tested nightly against planemo as outlined in that issue we would have discovered this problem right away. We can include your tool tests in the framework pilot if you'd like as well I think - @blankenberg and I had discussed how to find well maintained tools to test Galaxy against and I don't think there is a better set of such tools out there than your repositories.

**Comment by peterjc** [comment]
Confirmed: https://travis-ci.org/peterjc/pico_galaxy/jobs/148057047 failed on rerunning, Galaxy dev branch seems to be fixed - thank you!

Problems with the planemo's own tests already filed as #523 

In terms of https://github.com/galaxyproject/galaxy/issues/2642 right now my tools are not ideal - I need to recreate the whitelist/blacklist functionality which I had prior to (trying to) switch to ``planemo test``, as there are some unfinished tool wrappers in my repositories and/or tools with hard to install dependencies.
