### ISSUE TITLE
install_galaxy problem

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/planemo#55]
From @erasche: http://fpaste.org/168638/69015142/ freshly installed planemo and ran `planemo t --install_galaxy`.

**Comment by erasche** [comment]
Error message reproduced below (for posterity when that paste disappears)

```
galaxy.eggs DEBUG 2015-01-12 07:23:10,739 Fetched http://eggs.galaxyproject.org/requests/requests-2.2.1-py2.7.egg
Usage: functional_tests.py [options]
 
functional_tests.py: error: no such option: --with-nosehtml
functional_tests.py ERROR 2015-01-12 07:23:10,952 Failure running tests
Traceback (most recent call last):
  File "./scripts/functional_tests.py", line 505, in main
    success = _run_functional_test( )
  File "./scripts/functional_tests.py", line 465, in _run_functional_test
    test_config.configure( sys.argv )
  File "/tmp/tmp8D7aIF/galaxy-central-master/eggs/nose-0.11.1-py2.7.egg/nose/config.py", line 249, in configure
    options, args = self._parseArgs(argv, cfg_files)
  File "/tmp/tmp8D7aIF/galaxy-central-master/eggs/nose-0.11.1-py2.7.egg/nose/config.py", line 237, in _parseArgs
    return parser.parseArgsAndConfigFiles(argv[1:], cfg_files)
  File "/tmp/tmp8D7aIF/galaxy-central-master/eggs/nose-0.11.1-py2.7.egg/nose/config.py", line 133, in parseArgsAndConfigFiles
    return self._parser.parse_args(args, values)
  File "/usr/lib/python2.7/optparse.py", line 1402, in parse_args
    self.error(str(err))
  File "/usr/lib/python2.7/optparse.py", line 1584, in error
    self.exit(2, "%s: error: %s\n" % (self.get_prog_name(), msg))
  File "/usr/lib/python2.7/optparse.py", line 1574, in exit
    sys.exit(status)
SystemExit: 2

...

Cannot locate xUnit report option for tests - update Galaxy for more detailed breakdown.
```

**Comment by jmchilton** [comment]
@erasche I believe this should be addressed by pull request #56. Can you update planemo and let me know if the issue persists? It should be fixed now for both pip installs and brew installs of planemo.

**Comment by erasche** [comment]
Fixed! Thanks so much!

**Comment by jmchilton** [comment]
Awesome - thanks for the bug report!
