### ISSUE TITLE
planemo conda_init fails on Travis

### ISSUE THREAD

**Issue by martenson** [galaxyproject/planemo#582]
see https://travis-ci.org/galaxyproject/tools-devteam/jobs/163841480

`ImportError: No module named container_resolvers.explicit`

<details>
```
$ planemo conda_init
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.9/bin/planemo", line 7, in <module>
    from planemo.cli import planemo
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/planemo/cli.py", line 11, in <module>
    from planemo.galaxy import profiles
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/planemo/galaxy/__init__.py", line 5, in <module>
    from .config import galaxy_config
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/planemo/galaxy/config.py", line 25, in <module>
    from planemo.docker import docker_host_args
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/planemo/docker.py", line 8, in <module>
    from galaxy.tools.deps.dockerfiles import docker_host_args
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/galaxy/tools/deps/dockerfiles.py", line 6, in <module>
    from ..deps.containers import docker_cache_path
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/galaxy/tools/deps/containers.py", line 15, in <module>
    from .container_resolvers.explicit import ExplicitContainerResolver
ImportError: No module named container_resolvers.explicit
```
<detail>

**Comment by martenson** [comment]
> Planemo is unchanged - something wrong with galaxy-lib.

**Comment by peterjc** [comment]
I saw this too, e.g. https://travis-ci.org/peterjc/tools-iuc/jobs/163863165

Filed as https://github.com/galaxyproject/galaxy-lib/issues/16

**Comment by jmchilton** [comment]
But I think I fixed it this morning - is it still broken?

**Comment by martenson** [comment]
I do not think it is broken, just takes time to propagate because you need to update galaxy-lib
