### ISSUE TITLE
planemo ci_find_repos - $TRAVIS_COMMIT_RANGE Problem executing commands

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/planemo#588]
This test run was from a rebased branch which had been force updated, meaning TravisCI does not have a meaningful ``$TRAVIS_COMMIT_RANGE`` thus as per https://github.com/galaxyproject/tools-iuc/pull/973 and https://github.com/galaxyproject/tools-iuc/issues/961 the ``.travis.yml`` file set this to differences from the master branch.

Unfortunately ``planemo ci_find_repos`` then breaks, e.g. https://travis-ci.org/peterjc/tools-iuc/jobs/165764988

<details>
```
$ if ! git diff --quiet "$TRAVIS_COMMIT_RANGE" -- ; then TRAVIS_COMMIT_RANGE=master...; fi
fatal: bad revision '13f515d37121...2ebff2330354'

$ echo $TRAVIS_COMMIT_RANGE
master...

4.63s$ planemo ci_find_repos --exclude_from .tt_blacklist \
                        --exclude packages --exclude data_managers \
                        --changed_in_commit_range "$TRAVIS_COMMIT_RANGE" \
                        --chunk_count 4 --chunk "${CHUNK}" \
                        --output changed_repositories_chunk.list
  
cd '/home/travis/build/peterjc/tools-iuc' && git diff --name-only 'master...' --
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.9/bin/planemo", line 11, in <module>
    sys.exit(planemo())
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/planemo/cli.py", line 175, in handle_profile_options
    return f(*args, **kwds)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/planemo/commands/cmd_ci_find_repos.py", line 25, in cli
    paths = filter_paths(ctx, raw_paths, path_type="dir", **kwds)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/planemo/ci.py", line 24, in filter_paths
    diff_files = git.diff(ctx, cwd, changed_in_commit_range)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/planemo/git.py", line 53, in diff
    cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/planemo/io.py", line 43, in communicate
    raise RuntimeError(msg)
RuntimeError: Problem executing commands cd '/home/travis/build/peterjc/tools-iuc' && git diff --name-only 'master...' -- - (, fatal: bad revision 'master...'
)
The command "planemo ci_find_repos --exclude_from .tt_blacklist \
                        --exclude packages --exclude data_managers \
                        --changed_in_commit_range "$TRAVIS_COMMIT_RANGE" \
                        --chunk_count 4 --chunk "${CHUNK}" \
                        --output changed_repositories_chunk.list
  " failed and exited with 1 during .
Your build has been stopped.
```
</details>

**Comment by nsoranzo** [comment]
I think that the problem is at https://travis-ci.org/peterjc/tools-iuc/jobs/165764988#L111 , `gmap` is the only available branch, `master` does not exist locally.

**Comment by peterjc** [comment]
But https://github.com/peterjc/tools-iuc/tree/master does exist, and would have done some from when the repository was first forked. I updated it recently to parity with https://github.com/galaxyproject/tools-iuc/tree/master but not sure if that was before or after triggering this build.

Do you mean in the local git repository on the TravisCI VM the master branch might not exist? If so would ``$ export TRAVIS_COMMIT_RANGE=origin/master...`` be worth trying instead?

**Comment by nsoranzo** [comment]
I obviously mean the local git repo on TravisCI created by the command I've linked above:
```
$ git clone --depth=50 --branch=gmap https://github.com/peterjc/tools-iuc.git peterjc/tools-iuc
Cloning into 'peterjc/tools-iuc'...
remote: Counting objects: 4286, done.
remote: Compressing objects: 100% (2777/2777), done.
remote: Total 4286 (delta 1629), reused 3374 (delta 1310), pack-reused 0
Receiving objects: 100% (4286/4286), 34.88 MiB | 9.99 MiB/s, done.
Resolving deltas: 100% (1629/1629), done.
Checking connectivity... done.
$ cd peterjc/tools-iuc
$ git diff --name-only 'master...' --
fatal: bad revision 'master...'
$ git branch
* gmap
  remotes/origin/gmap
```
Since this is a shallow clone (due to the `--depth` option of `git clone`), there seems to be no easy way to fetch the `master` branch. Sorry, I see no solution apart from avoid rebasing or using PRs to test.

**Comment by peterjc** [comment]
Thanks for clarifying Nicola - you're right, I'd forgotten TravisCI does a shallow clone to speed things up.

Let's leave this issue open for making the ``planemo ci_find_repos --changed_in_commit_range XXX`` failure more graceful.

Separately perhaps the ``tools-iuc`` repo can do something along these lines to ensure the master branch will be present?:

```
if ! git diff --quiet "$TRAVIS_COMMIT_RANGE" -- ; then git remote add ...; git fetch ...; TRAVIS_COMMIT_RANGE=master...; fi
```

**Comment by nsoranzo** [comment]
I found a trick!
```
$ git remote set-branches --add origin master
$ git fetch
$ git diff --name-only 'origin/master...' --
packages/package_gmap_2013_05_09/.shed.yml
packages/package_gmap_2013_05_09/tool_dependencies.xml
tools/gmap/.shed.yml
tools/gmap/README
tools/gmap/datatypes_conf.xml
tools/gmap/gmap.xml
tools/gmap/gmap_build.xml
tools/gmap/gsnap.xml
tools/gmap/iit_store.xml
tools/gmap/lib/galaxy/datatypes/gmap.py
tools/gmap/snpindex.xml
tools/gmap/test-data/ss.chr17.fasta
tools/gmap/test-data/ss.her2.chr17.txt
tools/gmap/test-data/ss.her2.fasta
tools/gmap/tool-data/datatypes_conf.xml
tools/gmap/tool-data/datatypes_conf.xml~
tools/gmap/tool-data/gmap_indices.loc.sample
tools/gmap/tool_dependencies.xml
```

**Comment by peterjc** [comment]
I was hoping https://github.com/galaxyproject/tools-iuc/issues/998 from @nsoranzo would fix this, but sadly no.

This branch was just rebased to ``tools-iuc/master`` and force pushed: https://travis-ci.org/peterjc/tools-iuc/jobs/168615665

```
0.01s$ git diff --quiet "$TRAVIS_COMMIT_RANGE" -- ; GIT_DIFF_EXIT_CODE=$?
fatal: bad revision '3a9877744057...40c0a8a57560'
install.9
0.31s$ if [ "$GIT_DIFF_EXIT_CODE" -gt 1 ] ; then
    git remote set-branches --add origin master;
    git fetch;
    TRAVIS_COMMIT_RANGE=master...;
  fi
  
From https://github.com/peterjc/tools-iuc
 * [new branch]      master     -> origin/master
install.10
0.00s$ echo $TRAVIS_COMMIT_RANGE
master...
6.63s$ planemo ci_find_repos --exclude_from .tt_blacklist \
                        --exclude packages --exclude data_managers \
                        --changed_in_commit_range "$TRAVIS_COMMIT_RANGE" \
                        --chunk_count 4 --chunk "${CHUNK}" \
                        --output changed_repositories_chunk.list
  
cd '/home/travis/build/peterjc/tools-iuc' && git diff --name-only 'master...' --
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.9/bin/planemo", line 11, in <module>
    sys.exit(planemo())
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/planemo/cli.py", line 175, in handle_profile_options
    return f(*args, **kwds)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/planemo/commands/cmd_ci_find_repos.py", line 25, in cli
    paths = filter_paths(ctx, raw_paths, path_type="dir", **kwds)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/planemo/ci.py", line 24, in filter_paths
    diff_files = git.diff(ctx, cwd, changed_in_commit_range)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/planemo/git.py", line 53, in diff
    cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/planemo/io.py", line 43, in communicate
    raise RuntimeError(msg)
RuntimeError: Problem executing commands cd '/home/travis/build/peterjc/tools-iuc' && git diff --name-only 'master...' -- - (, fatal: bad revision 'master...'
)
The command "planemo ci_find_repos --exclude_from .tt_blacklist \
                        --exclude packages --exclude data_managers \
                        --changed_in_commit_range "$TRAVIS_COMMIT_RANGE" \
                        --chunk_count 4 --chunk "${CHUNK}" \
                        --output changed_repositories_chunk.list
  " failed and exited with 1 during .
Your build has been stopped.
```

**Comment by peterjc** [comment]
Looks like this would solve it, tiny difference in ``.travis.yml`` from @nsoranzo's comment above:

```
$ git diff --quiet "master..." -- ; echo "Return $?"
fatal: bad revision 'master...'
Return 128
$ git diff --quiet "origin/master..." -- ; echo "Return $?"
Return 1
```

See https://github.com/galaxyproject/tools-iuc/pull/1003

**Comment by nsoranzo** [comment]
I am no good at copy/paste :cry:

**Comment by peterjc** [comment]
On the bright side, your pull request reviews frequently catch typos and other easily missed issued - it more than balances out in your favour 😄

**Comment by jmchilton** [comment]
This idiom should be moved into planemo so that all tool repository Travis setups can leverage it cleanly.

**Comment by peterjc** [comment]
It would mean adding a new command line option in place of ``planemo ci_find_repos --changed_in_commit_range "$TRAVIS_COMMIT_RANGE"`` but I think doing this in planemo is a good idea in principle.

**Comment by peterjc** [comment]
Still not always working, e.g. https://travis-ci.org/peterjc/tools-iuc/builds/168948103 has all tests passing because it wrongly thinks none changed:

```
...
$ planemo --version
planemo, version 0.34.1
$ conda --version
conda 3.19.3
$ git diff --quiet "$TRAVIS_COMMIT_RANGE" -- ; GIT_DIFF_EXIT_CODE=$?
$ if [ "$GIT_DIFF_EXIT_CODE" -gt 1 ] ; then
    git remote set-branches --add origin master;
    git fetch;
    TRAVIS_COMMIT_RANGE=origin/master...;
  fi
  
$ echo $TRAVIS_COMMIT_RANGE
7311c8245ab6...c1f730ca1773
$ planemo ci_find_repos --exclude_from .tt_blacklist \
                        --exclude packages --exclude data_managers \
                        --changed_in_commit_range "$TRAVIS_COMMIT_RANGE" \
                        --chunk_count 4 --chunk "${CHUNK}" \
                        --output changed_repositories_chunk.list
  
cd '/home/travis/build/peterjc/tools-iuc' && git diff --name-only '7311c8245ab6...c1f730ca1773' $ cat changed_repositories_chunk.list

$ cd "$TRAVIS_BUILD_DIR" && flake8 --exclude=.git .
...
```

Here ``7311c8245ab6...c1f730ca1773`` is only the last two commits - which were recent pushes on top of what was a force rebased branch. It looks like TravisCI set ``$TRAVIS_COMMIT_RANGE`` to that?

**Comment by peterjc** [comment]
Good news - a force push worked 👍 

From https://travis-ci.org/peterjc/tools-iuc/jobs/168955783 (which sadly fails):

```
$ planemo --version
planemo, version 0.34.1
$ conda --version
conda 3.19.3
$ git diff --quiet "$TRAVIS_COMMIT_RANGE" -- ; GIT_DIFF_EXIT_CODE=$?
fatal: bad revision 'c1f730ca1773...1dc5aac65fef'
$ if [ "$GIT_DIFF_EXIT_CODE" -gt 1 ] ; then
    git remote set-branches --add origin master;
    git fetch;
    TRAVIS_COMMIT_RANGE=origin/master...;
  fi
  
From https://github.com/peterjc/tools-iuc
 * [new branch]      master     -> origin/master
$ echo $TRAVIS_COMMIT_RANGE
origin/master...
$ planemo ci_find_repos --exclude_from .tt_blacklist \
                        --exclude packages --exclude data_managers \
                        --changed_in_commit_range "$TRAVIS_COMMIT_RANGE" \
                        --chunk_count 4 --chunk "${CHUNK}" \
                        --output changed_repositories_chunk.list
  
cd '/home/travis/build/peterjc/tools-iuc' && git diff --name-only 'origin/master...' --
$ cat changed_repositories_chunk.list
tools/gmap
$ cd "$TRAVIS_BUILD_DIR" && flake8 --exclude=.git .
...
```

**Comment by Iristyle** [comment]
FYI the `TRAVIS_COMMIT_RANGE` variable should contain `..` instead of `...`

This is how we're fixing it in Puppet - https://github.com/puppetlabs/puppet/pull/5405

**Comment by bebatut** [comment]
@nsoranzo I think I have the same issue when I have a branch on my fork with only one commit: https://travis-ci.org/bebatut/tools-iuc/jobs/271772424:

```
$ planemo ci_find_repos --exclude_from .tt_blacklist \
                        --changed_in_commit_range "$TRAVIS_COMMIT_RANGE" \
                        --output changed_repositories.list
  
cd '/home/travis/build/bebatut/tools-iuc' && git diff --name-only 'c0e9a0db2289...043482f1a928' --
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.13/bin/planemo", line 11, in <module>
    sys.exit(planemo())
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/planemo/cli.py", line 178, in handle_blended_options
    return f(*args, **kwds)
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/planemo/commands/cmd_ci_find_repos.py", line 28, in cli
    paths = filter_paths(ctx, raw_paths, path_type="repo", **kwds)
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/planemo/ci.py", line 25, in filter_paths
    diff_files = git.diff(ctx, cwd, changed_in_commit_range)
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/planemo/git.py", line 80, in diff
    cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/planemo/io.py", line 43, in communicate
    raise RuntimeError(msg)
RuntimeError: Problem executing commands cd '/home/travis/build/bebatut/tools-iuc' && git diff --name-only 'c0e9a0db2289...043482f1a928' -- - (, fatal: bad revision 'c0e9a0db2289...043482f1a928'
)
```

but if `git diff --name-only 'c0e9a0db2289...043482f1a928' --` is working fine for me locally

**Comment by nsoranzo** [comment]
@bebatut:
- Did you force push to the branch? I think it never worked on force-pushed branches.
- It looks like that this trick is applied only on the `test` stages, but should be added (with a YAML macro) also to the `lint` and `deploy` stages.
