### ISSUE TITLE
planemo test ignores $GALAXY_TEST_FILE_DIR

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/planemo#594]
As per discussion on https://github.com/galaxyproject/galaxy/issues/3065 both @nsoranzo and I would expect planemo to respect the `$GALAXY_TEST_FILE_DIR` setting.

Example setup:

```
$ planemo --version
planemo, version 0.35.0.dev0
$ git clone https://github.com/galaxyproject/galaxy-test-data.git
$ git clone https://github.com/galaxyproject/galaxy.git
$ cd galaxy
$ git checkout dev
```

Attempting to use `$GALAXY_TEST_FILE_DIR` with planemo:

```
$ export GALAXY_TEST_FILE_DIR=../galaxy-test-data/
$ ls -1 $GALAXY_TEST_FILE_DIR/gff_filter_*.gff
../galaxy-test-data//gff_filter_attr_in1.gff
../galaxy-test-data//gff_filter_by_attribute_out1.gff
../galaxy-test-data//gff_filter_by_attribute_out2.gff
../galaxy-test-data//gff_filter_by_feature_count_out1.gff
../galaxy-test-data//gff_filter_by_feature_count_out2.gff
$ planemo test --galaxy_root . tools/filters/gff/gff_filter_by_attribute.xml 
...
======================================================================
ERROR: Filter GFF data by attribute ( gff_filter_by_attribute ) > Test-1
----------------------------------------------------------------------
Traceback (most recent call last):
...
IOError: [Errno 2] No such file or directory: '/Volumes/Hitachi-3TB-mirrored/repositories/galaxy/test-data/gff_filter_attr_in1.gff'
-------------------- >> begin captured logging << --------------------
...
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: Filter GFF data by attribute ( gff_filter_by_attribute ) > Test-2
----------------------------------------------------------------------
Traceback (most recent call last):
...
IOError: [Errno 2] No such file or directory: '/Volumes/Hitachi-3TB-mirrored/repositories/galaxy/test-data/gff_filter_attr_in1.gff'
-------------------- >> begin captured logging << --------------------
...
FAILED (errors=2)
test_driver INFO 2016-10-21 14:07:16,988 Shutting down
test_driver INFO 2016-10-21 14:07:16,988 Shutting down embedded galaxy web server
test_driver INFO 2016-10-21 14:07:16,991 Embedded web server galaxy stopped
test_driver INFO 2016-10-21 14:07:16,991 Stopping application galaxy
galaxy.jobs.handler INFO 2016-10-21 14:07:16,992 sending stop signal to worker thread
galaxy.jobs.handler INFO 2016-10-21 14:07:16,992 job handler queue stopped
galaxy.jobs.runners INFO 2016-10-21 14:07:16,992 TaskRunner: Sending stop signal to 2 worker threads
galaxy.jobs.runners INFO 2016-10-21 14:07:16,993 LocalRunner: Sending stop signal to 4 worker threads
galaxy.jobs.handler INFO 2016-10-21 14:07:16,994 sending stop signal to worker thread
galaxy.jobs.handler INFO 2016-10-21 14:07:16,994 job handler stop queue stopped
test_driver INFO 2016-10-21 14:07:16,995 Application galaxy stopped.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/pjcock/.planemo/gx_venv/lib/python2.7/site-packages/paste/httpserver.py", line 1101, in serve_forever
    self.handle_request()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 276, in handle_request
    fd_sets = _eintr_retry(select.select, [self], [], [], timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 155, in _eintr_retry
    return func(*args)
error: (9, 'Bad file descriptor')

galaxy.jobs.handler INFO 2016-10-21 14:07:16,997 sending stop signal to worker thread
galaxy.jobs.handler INFO 2016-10-21 14:07:16,997 job handler queue stopped
galaxy.jobs.runners INFO 2016-10-21 14:07:16,997 TaskRunner: Sending stop signal to 2 worker threads
galaxy.jobs.runners INFO 2016-10-21 14:07:16,997 LocalRunner: Sending stop signal to 4 worker threads
galaxy.jobs.handler INFO 2016-10-21 14:07:16,997 sending stop signal to worker thread
galaxy.jobs.handler INFO 2016-10-21 14:07:16,997 job handler stop queue stopped
Testing complete. HTML report is in "/Volumes/Hitachi-3TB-mirrored/repositories/galaxy/tool_test_output.html".
There were problems with 2 test(s) - out of 2 test(s) executed. See /Volumes/Hitachi-3TB-mirrored/repositories/galaxy/tool_test_output.html for detailed breakdown.
Traceback (most recent call last):
  File "/usr/local/bin/planemo", line 9, in <module>
    load_entry_point('planemo==0.35.0.dev0', 'console_scripts', 'planemo')()
  File "/Library/Python/2.7/site-packages/click-5.1-py2.7.egg/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click-5.1-py2.7.egg/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click-5.1-py2.7.egg/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click-5.1-py2.7.egg/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click-5.1-py2.7.egg/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click-5.1-py2.7.egg/click/decorators.py", line 63, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/Library/Python/2.7/site-packages/click-5.1-py2.7.egg/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/planemo-0.35.0.dev0-py2.7.egg/planemo/cli.py", line 175, in handle_profile_options
    return f(*args, **kwds)
  File "/Library/Python/2.7/site-packages/planemo-0.35.0.dev0-py2.7.egg/planemo/commands/cmd_test.py", line 77, in cli
    return_value = run_in_config(ctx, config, **kwds)
  File "/Library/Python/2.7/site-packages/planemo-0.35.0.dev0-py2.7.egg/planemo/galaxy/test/actions.py", line 115, in run_in_config
    kwds=kwds
  File "/Library/Python/2.7/site-packages/planemo-0.35.0.dev0-py2.7.egg/planemo/galaxy/test/actions.py", line 129, in handle_reports_and_summary
    **kwds
  File "/Library/Python/2.7/site-packages/planemo-0.35.0.dev0-py2.7.egg/planemo/galaxy/test/actions.py", line 220, in _handle_summary
    **kwds
  File "/Library/Python/2.7/site-packages/planemo-0.35.0.dev0-py2.7.egg/planemo/galaxy/test/actions.py", line 232, in _summarize_tests_full
    _summarize_test_case(test_case_data, **kwds)
  File "/Library/Python/2.7/site-packages/planemo-0.35.0.dev0-py2.7.egg/planemo/galaxy/test/actions.py", line 250, in _summarize_test_case
    get_dict_value("data", structured_data)
  File "/Library/Python/2.7/site-packages/planemo-0.35.0.dev0-py2.7.egg/planemo/test/results.py", line 113, in get_dict_value
    raise KeyError("No key [%s] in [%s]" % (key, data))
KeyError: 'No key [status] in [None]'
```

As an aside, planemo is failing most ungracefully here.

**Comment by peterjc** [comment]
Workaround is to copy the files from ``$GALAXY_TEST_FILE_DIR`` into the Galaxy instance being used (not possible if using ``planemo test --install_galaxy`` though):

```
$ cp $GALAXY_TEST_FILE_DIR/gff_filter_*.gff test-data/
$ unset GALAXY_TEST_FILE_DIR
$ planemo test --galaxy_root . tools/filters/gff/gff_filter_by_attribute.xml
...
All 2 test(s) executed passed.
gff_filter_by_attribute[0]: passed
gff_filter_by_attribute[1]: passed
```

**Comment by jmchilton** [comment]
I believe you want to pass ``--test_data`` instead of setting that environment variable.

I'm not sure if Planemo should respect Galaxy's variables by default or not.

**Comment by peterjc** [comment]
Thanks John, using ``--test_data`` is a much better work around:

```
$ planemo --version
planemo, version 0.36.0.dev0
$ git clone https://github.com/galaxyproject/galaxy-test-data.git
$ git clone https://github.com/galaxyproject/galaxy.git
$ cd galaxy
$ git checkout dev
$ planemo test --test_data ../galaxy-test-data --galaxy_root . tools/filters/gff/gff_filter_by_attribute.xml
...
All 2 test(s) executed passed.
gff_filter_by_attribute[0]: passed
gff_filter_by_attribute[1]: passed
```

Does Planemo respect other Galaxy environment variables?

**Comment by jmchilton** [comment]
Let's say no. Some may happen to work but in general planemo is trying to control how these tests run.

**Comment by mvdbeek** [comment]
I think we can close this, `--test_data` is the way to go
