### ISSUE TITLE
Installation instructions inside README

### ISSUE THREAD

**Issue by mmiladi** [galaxyproject/planemo#615]
Installation instructions inside README do not work. On Ubunutu 16.04, I tried both pip and brew installation commands. Both of them either failed or had runtime exceptions.

**Comment by mmiladi** [comment]
However the Conda installation from https://planemo.readthedocs.io/en/latest/installation.html worked fine.

**Comment by nsoranzo** [comment]
@mmiladi Can you post details about the errors you got?

**Comment by mmiladi** [comment]
Hi @nsoranzo,
First I tried the brew setup which failed with errors coming below. For pip probably the brew incomplete installation made it fail.

```
$ brew tap galaxyproject/tap
$ brew install planemo

...
==> python -c import setuptools... --no-user-cfg install --prefix=/home/user/.linuxbrew/Cellar/planemo/0.36.1/libexec/vendor --single-version-externally-managed --record=installed.txt
Last 15 lines from /home/user/.cache/Homebrew/Logs/planemo/11.python:
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/curl
copying python/curl/__init__.py -> build/lib.linux-x86_64-2.7/curl
running build_ext
building 'pycurl' extension
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/src
/usr/bin/gcc-5 -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Os -w -pipe -march=core2 -isystem/home/user/.linuxbrew/include -fPIC -DPYCURL_VERSION="7.19.5.3" -DHAVE_CURL_OPENSSL=1 -DHAVE_CURL_SSL=1 -I/usr/include/python2.7 -c src/docstrings.c -o build/temp.linux-x86_64-2.7/src/docstrings.o
In file included from src/docstrings.c:4:0:
src/pycurl.h:161:31: fatal error: openssl/crypto.h: No such file or directory
compilation terminated.
error: command '/usr/bin/gcc-5' failed with exit status 1

READ THIS: https://github.com/Linuxbrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/galaxyproject/homebrew-tap/issues

/usr/lib/ruby/2.3.0/open-uri.rb:359:in `open_http': 422 Unprocessable Entity (GitHub::Error)
Validation Failed
	from /usr/lib/ruby/2.3.0/open-uri.rb:737:in `buffer_open'
	from /usr/lib/ruby/2.3.0/open-uri.rb:212:in `block in open_loop'
	from /usr/lib/ruby/2.3.0/open-uri.rb:210:in `catch'
	from /usr/lib/ruby/2.3.0/open-uri.rb:210:in `open_loop'
	from /usr/lib/ruby/2.3.0/open-uri.rb:151:in `open_uri'
	from /usr/lib/ruby/2.3.0/open-uri.rb:717:in `open'
	from /usr/lib/ruby/2.3.0/open-uri.rb:31:in `open'
	from /home/user/.linuxbrew/Library/Homebrew/utils.rb:621:in `open'
	from /home/user/.linuxbrew/Library/Homebrew/utils.rb:654:in `issues_matching'
	from /home/user/.linuxbrew/Library/Homebrew/utils.rb:686:in `issues_for_formula'
	from /home/user/.linuxbrew/Library/Homebrew/exceptions.rb:222:in `fetch_issues'
	from /home/user/.linuxbrew/Library/Homebrew/exceptions.rb:218:in `issues'
	from /home/user/.linuxbrew/Library/Homebrew/exceptions.rb:263:in `dump'
	from /home/user/.linuxbrew/Library/brew.rb:133:in `rescue in <main>'
	from /home/user/.linuxbrew/Library/brew.rb:29:in `<main>'


```

**Comment by nsoranzo** [comment]
Thanks @mmiladi, unfortunately I don't have much experience with brew (I could help more with pip), but looking at the error this could be something similar to http://mattseymour.net/blog/2015/04/pip-install-pycurl-failed-with-exit-status-1/ (even if the problem there is with pip). Can you check that you have `libssl-dev` installed on your Ubuntu?

**Comment by mmiladi** [comment]
Thanks @nsoranzo ! 

`libssl-dev` was not installed. After installing it with system package manager, the brew installation successfully finishes.  I guess `libssl-dev` should be added to the dependency set of the brew recipe.

**Comment by jmchilton** [comment]
Thanks for the issue creation and the advice to fix it - I made that change and it seems to work!

**Comment by mmiladi** [comment]
Thanks @jmchilton  for the quick update.
