### ISSUE TITLE
Ugly error message for missing credentials

### ISSUE THREAD

**Issue by erasche** [galaxyproject/planemo#66]
TTS creds were missing from my ~/.planemo.yml, this was the error I was presented with.

```
Traceback (most recent call last):
  File "/usr/local/bin/planemo", line 9, in <module>
    load_entry_point('planemo==0.2.0', 'console_scripts', 'planemo')()
  File "/usr/local/lib/python2.7/dist-packages/click-3.3-py2.7.egg/click/core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click-3.3-py2.7.egg/click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click-3.3-py2.7.egg/click/core.py", line 936, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click-3.3-py2.7.egg/click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click-3.3-py2.7.egg/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click-3.3-py2.7.egg/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click-3.3-py2.7.egg/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/planemo-0.2.0-py2.7.egg/planemo/commands/cmd_shed_upload.py", line 78, in cli
    error(e.read())
AttributeError: 'exceptions.TypeError' object has no attribute 'read'
```

**Comment by jmchilton** [comment]
Specific read problem is no longer an issue - but missing credentials still result in an ugly error. Closing this in lieu of tracking the problem with #153 - until a new bioblend release is issued which will fix the problem.
