### ISSUE TITLE
Cannot locate xUnit report for tests - required to build planemo report and summarize tests.

### ISSUE THREAD

**Issue by jjkoehorst** [galaxyproject/planemo#724]
It worked for a few attempts but suddenly I receive a:

**Cannot locate xUnit report [/tmp/tmpMg_ryK/xunit.xml] for tests - required to build planemo report and summarize tests.**

I am running this as followed on a MacBook Pro (macOS Sierra)

    planemo test galaxy_embl.xml --test_data ./

or

    planemo test galaxy_embl.xml --test_data ./ --galaxy_root=/Users/jasperkoehorst/GitLab/galaxy

`
Testing using galaxy_root /Users/jasperkoehorst/GitLab/galaxy
Testing tools with command [cd /Users/jasperkoehorst/GitLab/galaxy; if [ -d .venv ] || [ -f dist-eggs.ini ]; then GALAXY_VIRTUAL_ENV=.venv;  else GALAXY_VIRTUAL_ENV=/Users/jasperkoehorst/.planemo/gx_venv; fi; export GALAXY_VIRTUAL_ENV; if [ ! -e $GALAXY_VIRTUAL_ENV ]; then /usr/local/bin/virtualenv -p /usr/local/bin/python2.7 $GALAXY_VIRTUAL_ENV; fi; [ -e $GALAXY_VIRTUAL_ENV ] && . $GALAXY_VIRTUAL_ENV/bin/activate; sh run_tests.sh $COMMON_STARTUP_ARGS --report_file /Users/jasperkoehorst/GitLab/galaxy/tools/sapp/Modules/Conversion/tool_test_output.html --xunit_report_file /tmp/tmpMg_ryK/xunit.xml --structured_data_report_file /Users/jasperkoehorst/GitLab/galaxy/tools/sapp/Modules/Conversion/tool_test_output.json functional.test_toolbox]
Activating virtualenv at .venv
Requirement already satisfied: pip>=8.1 in ./.venv/lib/python2.7/site-packages
Requirement already satisfied: bx-python==0.7.3 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 2))
...
...
...
Requirement already satisfied: requests>=2.0.0 in ./.venv/lib/python2.7/site-packages (from sphinx->-r ./lib/galaxy/dependencies/dev-requirements.txt (line 8))
Requirement already satisfied: Pygments>=2.0 in ./.venv/lib/python2.7/site-packages (from sphinx->-r ./lib/galaxy/dependencies/dev-requirements.txt (line 8))
Requirement already satisfied: commonmark<=0.5.4 in ./.venv/lib/python2.7/site-packages (from recommonmark->-r ./lib/galaxy/dependencies/dev-requirements.txt (line 11))
Requirement already satisfied: pytz>=0a in ./.venv/lib/python2.7/site-packages (from babel!=2.0,>=1.3->sphinx->-r ./lib/galaxy/dependencies/dev-requirements.txt (line 8))
Requirement already satisfied: MarkupSafe>=0.23 in ./.venv/lib/python2.7/site-packages (from Jinja2>=2.3->sphinx->-r ./lib/galaxy/dependencies/dev-requirements.txt (line 8))
Activating virtualenv at .venv
2017-09-08 07:37:39,342 WARNI [galaxy.containers] config file './config/containers_conf.yml' does not exist, running with default config
2017-09-08 07:37:39,343 INFO  [galaxy.queue_worker] Initializing main Galaxy Queue Worker on sqlalchemy+sqlite://
2017-09-08 07:37:39,450 ERROR [galaxy.model.migrate.check] Problem determining migration changeset for engine [Engine(sqlite:////var/folders/7s/1n66vsfj1c93hm09w2xz747c0000gn/T/tmpQ9DWhy/tmpN3QW_M/tmpvOMsh4/database/galaxy.sqlite)]
Traceback (most recent call last):
  File "./scripts/functional_tests.py", line 122, in <module>
    driver_util.drive_test(find_test_driver())
  File "/Users/jasperkoehorst/GitLab/galaxy/test/base/driver_util.py", line 737, in drive_test
    sys.exit(test_driver.run())
  File "/Users/jasperkoehorst/GitLab/galaxy/test/base/driver_util.py", line 608, in run
    self.setup()
  File "/Users/jasperkoehorst/GitLab/galaxy/test/base/driver_util.py", line 676, in setup
    self.app = build_galaxy_app(galaxy_config)
  File "/Users/jasperkoehorst/GitLab/galaxy/test/base/driver_util.py", line 481, in build_galaxy_app
    app = GalaxyUniverseApplication( **simple_kwargs )
  File "/Users/jasperkoehorst/GitLab/galaxy/lib/galaxy/app.py", line 75, in __init__
    self._configure_models( check_migrate_databases=True, check_migrate_tools=check_migrate_tools, config_file=config_file )
  File "/Users/jasperkoehorst/GitLab/galaxy/lib/galaxy/config.py", line 1025, in _configure_models
    create_or_verify_database( db_url, config_file, self.config.database_engine_options, app=self )
  File "/Users/jasperkoehorst/GitLab/galaxy/lib/galaxy/model/migrate/check.py", line 47, in create_or_verify_database
    migrate()
  File "/Users/jasperkoehorst/GitLab/galaxy/lib/galaxy/model/migrate/check.py", line 43, in migrate
    migrate_to_current_version( engine, db_schema )
  File "/Users/jasperkoehorst/GitLab/galaxy/lib/galaxy/model/migrate/check.py", line 108, in migrate_to_current_version
    raise e
AssertionError: There is no script for 135 version
Testing complete. HTML report is in "/Users/jasperkoehorst/GitLab/galaxy/tools/sapp/Modules/Conversion/tool_test_output.html".
Cannot locate xUnit report [/tmp/tmpMg_ryK/xunit.xml] for tests - required to build planemo report and summarize tests.
Traceback (most recent call last):
  File "/usr/local/Cellar/planemo/0.38.1/libexec/bin/planemo", line 11, in <module>
    load_entry_point('planemo==0.38.1', 'console_scripts', 'planemo')()
  File "/usr/local/Cellar/planemo/0.38.1/libexec/vendor/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/planemo/0.38.1/libexec/vendor/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/planemo/0.38.1/libexec/vendor/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/planemo/0.38.1/libexec/vendor/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/planemo/0.38.1/libexec/vendor/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/planemo/0.38.1/libexec/vendor/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/Cellar/planemo/0.38.1/libexec/vendor/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/planemo/0.38.1/libexec/lib/python2.7/site-packages/planemo/cli.py", line 175, in handle_profile_options
    return f(*args, **kwds)
  File "/usr/local/Cellar/planemo/0.38.1/libexec/lib/python2.7/site-packages/planemo/commands/cmd_test.py", line 77, in cli
    return_value = run_in_config(ctx, config, **kwds)
  File "/usr/local/Cellar/planemo/0.38.1/libexec/lib/python2.7/site-packages/planemo/galaxy/test/actions.py", line 102, in run_in_config
    _check_test_outputs(xunit_report_file_tracker, structured_report_file_tracker)
  File "/usr/local/Cellar/planemo/0.38.1/libexec/lib/python2.7/site-packages/planemo/galaxy/test/actions.py", line 283, in _check_test_outputs
    raise Exception(message)
Exception: Cannot locate xUnit report [/tmp/tmpMg_ryK/xunit.xml] for tests - required to build planemo report and summarize tests.`

Just linting the XML shows no problems:

> planemo lint galaxy_embl.xml --no_xsd      
> Linting tool /Users/jasperkoehorst/GitLab/galaxy/tools/sapp/Modules/Conversion/galaxy_embl.xml
> Applying linter tests... CHECK
> .. CHECK: 1 test(s) found.
> Applying linter stdio... CHECK
> .. INFO: No stdio definition found, tool will determine an error from stderr.
> Applying linter output... CHECK
> .. INFO: 1 outputs found.
> Applying linter inputs... CHECK
> .. INFO: Found 2 input parameters.
> Applying linter help... CHECK
> .. CHECK: Tool contains help section.
> .. CHECK: Help contains valid reStructuredText.
> Applying linter general... CHECK
> .. CHECK: Tool defines a version [0.0.1].
> .. CHECK: Tool defines a name [EMBL to GBOL].
> .. CHECK: Tool defines an id [CONVERSION_EMBL].
> Applying linter command... CHECK
> .. INFO: Tool contains a command.
>

**Comment by jmchilton** [comment]
The underlying Galaxy issue is

> AssertionError: There is no script for 135 version Testing complete

The error handling is poor here - but since Galaxy wasn't able to startup the artifacts Planemo expects it to produce were not able to be produced. 

That Galaxy issue is what happens when you start Galaxy with a newer commit and then checkout an older commit and so a pyc file for a newer database migration is present with no matching migration in the older release. This can be fixed by executing ``/bin/rm lib/galaxy/model/migrate/versions/*pyc`` from your Galaxy directory.
