### ISSUE TITLE
URL linting can fail with: Connection reset by peer

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/planemo#744]
e.g. from https://travis-ci.org/peterjc/galaxy_blast/jobs/295377753 failed with:

```
$ python --version
Python 2.7.13
$ pip --version
pip 9.0.1 from /home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages (python 2.7)
...
$ pip install planemo
Collecting planemo
  Using cached planemo-0.46.1-py2.py3-none-any.whl
...
$ echo "Using planemo lint to check for obvious tool errors"
Using planemo lint to check for obvious tool errors
$ planemo shed_lint --tools --fail_level error --ensure_metadata --urls -r ${TRAVIS_BUILD_DIR}
Linting repository /home/travis/build/peterjc/galaxy_blast/datatypes/blast_datatypes
...
+Linting tool /home/travis/build/peterjc/galaxy_blast/tools/ncbi_blast_plus/tools/ncbi_blast_plus/ncbi_segmasker_wrapper.xml
Applying linter tests... CHECK
.. CHECK: 3 test(s) found.
Applying linter output... CHECK
.. INFO: 1 outputs found.
Applying linter inputs... CHECK
.. INFO: Found 14 input parameters.
Applying linter help... CHECK
.. CHECK: Tool contains help section.
.. CHECK: Help contains valid reStructuredText.
Applying linter general... CHECK
.. CHECK: Tool defines a version [0.3.0].
.. CHECK: Tool defines a name [NCBI BLAST+ segmasker].
.. CHECK: Tool defines an id [ncbi_segmasker_wrapper].
.. CHECK: Tool targets 16.01 Galaxy profile.
Applying linter command... CHECK
.. INFO: Tool contains a command.
Applying linter citations... CHECK
.. CHECK: Found 2 likely valid citations.
Applying linter tool_xsd... CHECK
.. INFO: File validates against XML schema.
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.13/bin/planemo", line 11, in <module>
    sys.exit(planemo())
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/planemo/cli.py", line 178, in handle_blended_options
    return f(*args, **kwds)
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/planemo/commands/cmd_shed_lint.py", line 58, in cli
    exit_code = shed.for_each_repository(ctx, lint, paths, **kwds)
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/planemo/shed/__init__.py", line 767, in for_each_repository
    function(realized_repository)
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/planemo/commands/cmd_shed_lint.py", line 55, in lint
    return shed_lint.lint_repository(ctx, realized_repository, **kwds)
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/planemo/shed_lint.py", line 112, in lint_repository
    tools_failed = lint_repository_tools(ctx, realized_repository, lint_ctx, lint_args)
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/planemo/shed_lint.py", line 134, in lint_repository_tools
    extra_modules=lint_args["extra_modules"]
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/galaxy/tools/lint.py", line 54, in lint_tool_source_with
    lint_context.lint(name, value, tool_source)
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/galaxy/tools/lint.py", line 82, in lint
    lint_func(lint_target, self)
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/planemo/linters/urls.py", line 8, in lint_tool_urls
    planemo.lint.lint_urls(tool_source.root, lint_ctx)
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/planemo/lint.py", line 164, in lint_urls
    validate_url(url, lint_ctx, BROWSER_USER_AGENT)
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/planemo/lint.py", line 146, in validate_url
    handle = urlopen(req)
  File "/opt/python/2.7.13/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/python/2.7.13/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/opt/python/2.7.13/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/python/2.7.13/lib/python2.7/urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "/opt/python/2.7.13/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/opt/python/2.7.13/lib/python2.7/urllib2.py", line 654, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/opt/python/2.7.13/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/opt/python/2.7.13/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/opt/python/2.7.13/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/opt/python/2.7.13/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/opt/python/2.7.13/lib/python2.7/urllib2.py", line 1201, in do_open
    r = h.getresponse(buffering=True)
  File "/opt/python/2.7.13/lib/python2.7/httplib.py", line 1121, in getresponse
    response.begin()
  File "/opt/python/2.7.13/lib/python2.7/httplib.py", line 438, in begin
    version, status, reason = self._read_status()
  File "/opt/python/2.7.13/lib/python2.7/httplib.py", line 394, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/opt/python/2.7.13/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "/opt/python/2.7.13/lib/python2.7/ssl.py", line 766, in recv
    return self.read(buflen)
  File "/opt/python/2.7.13/lib/python2.7/ssl.py", line 653, in read
    v = self._sslobj.read(len)
socket.error: [Errno 104] Connection reset by peer
The command "planemo shed_lint --tools --fail_level error --ensure_metadata --urls -r ${TRAVIS_BUILD_DIR}" failed and exited with 1 during .
```

This is likely a missing clause in the try/except.

**Comment by peterjc** [comment]
Looks like this was fixed late last month by @nsoranzo in 4f989e7b5c614cdd4b46290feab3e79618e5331f - so should be resolved in the next release of planemo.

Should we leave this issue open till then, or close it now?
