### ISSUE TITLE
Cannot run planemo serve from a fresh clone

### ISSUE THREAD

**Issue by AnnaSyme** [galaxyproject/planemo#750]
(Actually filed by @erasche)

```
Initializing static/welcome.html from welcome.html.sample
The Galaxy client build is out of date.  Please run 'make client' or your choice of client build target (client-*).
If you're sure you'd like to skip this check, you can run galaxy with the --skip-client-build flag, though this is not recommended as the client and server code will potentially be out of sync.
See ./client/README.md in the Galaxy repository for more information, including how to get help if you're having trouble.
Problem running Galaxy command [].
Traceback (most recent call last):
  File "/usr/local/bin/planemo", line 11, in <module>
    sys.exit(planemo())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/planemo/cli.py", line 178, in handle_blended_options
    return f(*args, **kwds)
  File "/usr/local/lib/python2.7/site-packages/planemo/commands/cmd_serve.py", line 42, in cli
    galaxy_serve(ctx, runnables, **kwds)
  File "/usr/local/lib/python2.7/site-packages/planemo/galaxy/serve.py", line 19, in serve
    return _serve(ctx, runnables, **kwds)
  File "/usr/local/lib/python2.7/site-packages/planemo/galaxy/serve.py", line 46, in _serve
    raise Exception(message)
Exception: Problem running Galaxy command [].
```

**Comment by mvdbeek** [comment]
What command did you use to run planemo ? `planemo serve` should use a release branch, where the above error should not occur.

**Comment by erasche** [comment]
per the title, ran planemo pointing at a fresh clone of galaxy with `--galaxy_root`

**Comment by jmchilton** [comment]
Yeah - the client checks added to galaxy @ dev broke Planemo - I recommend using release_17.09 for now - I'll try to have a work around in place today. The tests are failing on this same issue.

**Comment by dannon** [comment]
(unintentional github automatic close of the issue when https://github.com/galaxyproject/galaxy/pull/5371 was merged)
