### ISSUE TITLE
brew is complaining

### ISSUE THREAD

**Issue by nekrut** [galaxyproject/planemo#757]
Installing from brew (on Ubuntu 17.10) generates the following warning:

## At setting the tap:

```
~/git/tools-iuc$ brew tap galaxyproject/tap
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
binutils        checkstyle      gifsicle        osquery         rgbds
bit             dlib            libebur128      pango           rsync
ccache          encfs           netcdf          ranger          vault

==> Tapping galaxyproject/tap
Cloning into '/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/galaxyproject/homebrew-tap'...
remote: Counting objects: 4, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4 (delta 0), reused 3 (delta 0), pack-reused 0
Unpacking objects: 100% (4/4), done.
Warning: Calling 'depends_on :python' is deprecated!
Use 'depends_on "python"' instead.
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/galaxyproject/homebrew-tap/planemo.rb:16:in `<class:Planemo>'
Please report this to the galaxyproject/tap tap!

Tapped 1 formula (28 files, 120.9KB)
```

## At installing planemo:
```
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "setup.py", line 731, in <module>
    ext = get_extension(sys.argv, split_extension_source=split_extension_source)
  File "setup.py", line 488, in get_extension
    ext_config = ExtensionConfiguration(argv)
  File "setup.py", line 71, in __init__
    self.configure()
  File "setup.py", line 107, in configure_unix
    raise ConfigurationError(msg)
__main__.ConfigurationError: Could not run curl-config: [Errno 2] No such file or directory

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/galaxyproject/homebrew-tap/issues
```

**Comment by martenson** [comment]
@nekrut I think you should be using `pip install planemo` to get it. Our brew tap is really behind (one year of versions) and we should maybe drop it. (@jmchilton)

**Comment by jmchilton** [comment]
Dropping Brew support for now I think, the configuration matrix is already so messy (xref https://xkcd.com/1987/).
