### ISSUE TITLE
planemo test silently ignoring tool with tests

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/planemo#765]
I was seeing a silent failure locally (running on CentOS, where I let ``planemo test`` create its own Galaxy instance), but have now reproduced it on TravisCI (were I pre-create the Galaxy instance in order to try specific branches).

Consider this job: https://travis-ci.org/peterjc/kodoja_galaxy/jobs/338520395 (using Galaxy ``master``)

```
$ planemo --version
planemo, version 0.47.0
The command "planemo --version" exited with 0.

$ planemo test --galaxy_root ${HOME}/galaxy-${GALAXY_BRANCH} --skip_venv ${TRAVIS_BUILD_DIR}
Testing using galaxy_root /home/travis/galaxy-master
...
----------------------------------------------------------------------
XML: /tmp/tmpkENNF8/xunit.xml
----------------------------------------------------------------------
Ran 0 tests in 0.000s
OK
```

I am expecting the tests to fail (as I've not yet told Galaxy how to find the output file).

The commit prior ``planemo test`` was finding the three tests https://travis-ci.org/peterjc/kodoja_galaxy/jobs/338510306 and they failed due to the ``test-data/*.loc`` file being loaded:

```
$ planemo --version
planemo, version 0.47.0
The command "planemo --version" exited with 0.

$ planemo test --galaxy_root ${HOME}/galaxy-${GALAXY_BRANCH} --skip_venv ${TRAVIS_BUILD_DIR}
Testing using galaxy_root /home/travis/galaxy-master
...
----------------------------------------
Kodoja database search ( kodoja_search ) > Test-1 ... ERROR
Kodoja database search ( kodoja_search ) > Test-2 ... ERROR
Kodoja database search ( kodoja_search ) > Test-3 ... ERROR
======================================================================
ERROR: Kodoja database search ( kodoja_search ) > Test-1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/galaxy-master/test/functional/test_toolbox.py", line 317, in test_tool
    self.do_it(td)
  File "/home/travis/galaxy-master/test/functional/test_toolbox.py", line 68, in do_it
    raise e
RunToolException: Error creating a job for these tool inputs - Specify a dataset of the required format / build.
======================================================================
ERROR: Kodoja database search ( kodoja_search ) > Test-2
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/galaxy-master/test/functional/test_toolbox.py", line 317, in test_tool
    self.do_it(td)
  File "/home/travis/galaxy-master/test/functional/test_toolbox.py", line 68, in do_it
    raise e
RunToolException: Error creating a job for these tool inputs - Specify a dataset of the required format / build.
======================================================================
ERROR: Kodoja database search ( kodoja_search ) > Test-3
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/galaxy-master/test/functional/test_toolbox.py", line 317, in test_tool
    self.do_it(td)
  File "/home/travis/galaxy-master/test/functional/test_toolbox.py", line 68, in do_it
    raise e
RunToolException: Error creating a job for these tool inputs - Specify a dataset of the required format / build.
----------------------------------------------------------------------
XML: /tmp/tmpQoCkQ5/xunit.xml
----------------------------------------------------------------------
Ran 3 tests in 1.425s
FAILED (errors=3)
```

The only change on my side was a single commit https://github.com/peterjc/kodoja_galaxy/commit/cd0113ebb25e1e88a32934df68f2aee588dce16a which setup the ``*.loc`` files manually.

My guess is an exception of some sort is being caught and ignored, rather than reported as a test failure?

[Cross reference https://github.com/galaxyproject/galaxy/issues/5466 for why these TravisCI jobs are failing with the Galaxy ``dev`` branch]

[Cross reference https://github.com/galaxyproject/galaxy/pull/5465 for improving the exception message for the data table parameter]

**Comment by peterjc** [comment]
From running this locally,

```
$ planemo --version
planemo, version 0.48.0.dev0

$ planemo test kodoja_search.xml 
git --git-dir /home/xxx/.planemo/gx_repo fetch >/dev/null 2>&1
...
2018-02-07 14:53:06,923 INFO  [galaxy.model.migrate.check] Migrating 132 -> 133... 
2018-02-07 14:53:07,448 INFO  [galaxy.model.migrate.check] 
2018-02-07 14:53:07,449 INFO  [galaxy.model.migrate.check] Add dependencies column to jobs table
2018-02-07 14:53:07,449 INFO  [galaxy.model.migrate.check] 
2018-02-07 14:53:07,449 INFO  [galaxy.model.migrate.check] 
2018-02-07 14:53:07,482 INFO  [galaxy.config] Install database targetting Galaxy's database configuration.
2018-02-07 14:53:08,055 ERROR [galaxy.visualization.genomes] Error reading twobit.loc: [Errno 2] No such file or directory: '/tmp/tmpw84plsc_/galaxy-dev/tool-data/twobit.loc'
Traceback (most recent call last):
  File "/tmp/tmpw84plsc_/galaxy-dev/lib/galaxy/visualization/genomes.py", line 210, in reload_genomes
    for line in open( os.path.join( self.app.config.tool_data_path, "twobit.loc" ) ):
IOError: [Errno 2] No such file or directory: '/tmp/tmpw84plsc_/galaxy-dev/tool-data/twobit.loc'
2018-02-07 14:53:08,075 INFO  [galaxy.jobs] Setting <handlers> default to child with id 'main'
2018-02-07 14:53:09,103 INFO  [galaxy.tools.toolbox.watcher] Watchdog library unavailable, cannot monitor tools.
2018-02-07 14:53:09,103 INFO  [galaxy.tools.toolbox.base] Parsing the tool configuration /tmp/tmpw84plsc_/tool_conf.xml
2018-02-07 14:53:09,118 INFO  [galaxy.tools.toolbox.base] Parsing the tool configuration /tmp/tmpw84plsc_/shed_tools_conf.xml
2018-02-07 14:53:09,119 INFO  [galaxy.tools.toolbox.base] Parsing the tool configuration /tmp/tmpw84plsc_/empty_tool_conf.xml
No handlers could be found for logger "galaxy.datatypes.display_applications.application"
2018-02-07 14:53:11,499 WARNI [galaxy.webhooks] directory not found: /tmp/tmpw84plsc_/galaxy-dev/lib/galaxy/util/../../.././config/plugins/webhooks/demo/config
2018-02-07 14:53:11,515 INFO  [galaxy.jobs] Handler 'main' will load all configured runner plugins
2018-02-07 14:53:11,523 INFO  [galaxy.jobs.handler] job handler stop queue started
2018-02-07 14:53:11,540 INFO  [galaxy.jobs.handler] job handler queue started
2018-02-07 14:53:14,946 INFO  [galaxy.queue_worker] Binding and starting galaxy control worker for main
/home/pc40583/.planemo/gx_venv/lib/python2.7/site-packages/sqlalchemy/sql/default_comparator.py:153: SAWarning: The IN-predicate on "request_type.id" was invoked with an empty sequence. This results in a contradiction, which nonetheless can be expensive to evaluate.  Consider alternative strategies for improved performance.
  'strategies for improved performance.' % expr)

----------------------------------------------------------------------
XML: /tmp/tmpw84plsc_/xunit.xml
----------------------------------------------------------------------
Ran 0 tests in 0.001s

OK
2018-02-07 14:53:17,332 INFO  [test_driver] Shutting down
2018-02-07 14:53:17,332 INFO  [test_driver] Shutting down embedded galaxy web server
2018-02-07 14:53:17,336 INFO  [test_driver] Embedded web server galaxy stopped
2018-02-07 14:53:17,336 INFO  [test_driver] Stopping application galaxy
2018-02-07 14:53:17,336 INFO  [galaxy.jobs.handler] sending stop signal to worker thread
2018-02-07 14:53:17,336 INFO  [galaxy.jobs.handler] job handler queue stopped
2018-02-07 14:53:17,336 INFO  [galaxy.jobs.runners] TaskRunner: Sending stop signal to 2 worker threads
2018-02-07 14:53:17,336 INFO  [galaxy.jobs.runners] LocalRunner: Sending stop signal to 4 worker threads
2018-02-07 14:53:17,337 INFO  [galaxy.jobs.handler] sending stop signal to worker thread
2018-02-07 14:53:17,337 INFO  [galaxy.jobs.handler] job handler stop queue stopped
2018-02-07 14:53:17,338 INFO  [test_driver] Application galaxy stopped.
2018-02-07 14:53:18,252 INFO  [galaxy.jobs.handler] sending stop signal to worker thread
2018-02-07 14:53:18,252 INFO  [galaxy.jobs.handler] job handler queue stopped
2018-02-07 14:53:18,252 INFO  [galaxy.jobs.runners] TaskRunner: Sending stop signal to 2 worker threads
2018-02-07 14:53:18,252 INFO  [galaxy.jobs.runners] LocalRunner: Sending stop signal to 4 worker threads
2018-02-07 14:53:18,253 INFO  [galaxy.jobs.handler] sending stop signal to worker thread
2018-02-07 14:53:18,253 INFO  [galaxy.jobs.handler] job handler stop queue stopped
Testing complete. HTML report is in "/mnt/shared/users/pc40583/repositories/kodoja_galaxy/tool_test_output.html".
No tests were executed - see Galaxy output for details.
```

Planemo lint is happy there are 3 tests:

```
$ planemo lint kodoja_search.xml 
Linting tool /mnt/shared/users/xxx/repositories/kodoja_galaxy/kodoja_search.xml
Applying linter tests... CHECK
.. CHECK: 3 test(s) found.
Applying linter output... CHECK
.. INFO: 1 outputs found.
Applying linter inputs... CHECK
.. INFO: Found 6 input parameters.
Applying linter help... CHECK
.. CHECK: Tool contains help section.
.. CHECK: Help contains valid reStructuredText.
Applying linter general... CHECK
.. CHECK: Tool defines a version [0.0.0].
.. CHECK: Tool defines a name [Kodoja database search].
.. CHECK: Tool defines an id [kodoja_search].
.. CHECK: Tool targets 16.01 Galaxy profile.
Applying linter command... CHECK
.. INFO: Tool contains a command.
Applying linter citations... CHECK
.. CHECK: Found 1 likely valid citations.
Applying linter tool_xsd... CHECK
.. INFO: File validates against XML schema.
```

**Comment by mvdbeek** [comment]
Probably the same issue as in https://github.com/galaxyproject/planemo/issues/752, we really need to do something here.

**Comment by peterjc** [comment]
It has certain similarities... they key looks to be ``watchdog`` failures, which I had missed in the full log:

```
2018-02-07 14:26:17,427 INFO  [galaxy.tools.toolbox.base] Parsing the tool configuration /tmp/tmpkENNF8/tool_conf.xml
2018-02-07 14:26:17,463 ERROR [galaxy.tools.toolbox.base] Error reading tool from path: data_source/upload.xml
Traceback (most recent call last):
  File "/home/travis/galaxy-master/lib/galaxy/tools/toolbox/base.py", line 564, in _load_tool_tag_set
    tool = self.load_tool(concrete_path, use_cached=False)
  File "/home/travis/galaxy-master/lib/galaxy/tools/toolbox/base.py", line 754, in load_tool
    self._tool_watcher.watch_file(config_file, tool.id)
  File "/home/travis/galaxy-master/lib/galaxy/tools/toolbox/watcher.py", line 198, in watch_file
    self.monitor(tool_dir)
  File "/home/travis/galaxy-master/lib/galaxy/tools/toolbox/watcher.py", line 190, in monitor
    self.observer.schedule(self.event_handler, dir, recursive=False)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/watchdog/observers/api.py", line 293, in schedule
    emitter.start()
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/watchdog/utils/__init__.py", line 111, in start
    self.on_thread_start()
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/watchdog/observers/inotify.py", line 121, in on_thread_start
    self._inotify = InotifyBuffer(path, self.watch.is_recursive)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/watchdog/observers/inotify_buffer.py", line 35, in __init__
    self._inotify = Inotify(path, recursive)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/watchdog/observers/inotify_c.py", line 187, in __init__
    self._add_dir_watch(path, recursive, event_mask)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/watchdog/observers/inotify_c.py", line 364, in _add_dir_watch
    self._add_watch(path, mask)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/watchdog/observers/inotify_c.py", line 385, in _add_watch
    Inotify._raise_error()
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/watchdog/observers/inotify_c.py", line 402, in _raise_error
    raise OSError("inotify watch limit reached")
OSError: inotify watch limit reached
2018-02-07 14:26:17,472 ERROR [galaxy.tools.toolbox.base] Failed to load potential tool /home/travis/build/peterjc/kodoja_galaxy/kodoja_search.xml.
Traceback (most recent call last):
  File "/home/travis/galaxy-master/lib/galaxy/tools/toolbox/base.py", line 713, in quick_load
    tool = self.load_tool(tool_file)
  File "/home/travis/galaxy-master/lib/galaxy/tools/toolbox/base.py", line 754, in load_tool
    self._tool_watcher.watch_file(config_file, tool.id)
  File "/home/travis/galaxy-master/lib/galaxy/tools/toolbox/watcher.py", line 198, in watch_file
    self.monitor(tool_dir)
  File "/home/travis/galaxy-master/lib/galaxy/tools/toolbox/watcher.py", line 190, in monitor
    self.observer.schedule(self.event_handler, dir, recursive=False)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/watchdog/observers/api.py", line 293, in schedule
    emitter.start()
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/watchdog/utils/__init__.py", line 111, in start
    self.on_thread_start()
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/watchdog/observers/inotify.py", line 121, in on_thread_start
    self._inotify = InotifyBuffer(path, self.watch.is_recursive)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/watchdog/observers/inotify_buffer.py", line 35, in __init__
    self._inotify = Inotify(path, recursive)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/watchdog/observers/inotify_c.py", line 187, in __init__
    self._add_dir_watch(path, recursive, event_mask)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/watchdog/observers/inotify_c.py", line 364, in _add_dir_watch
    self._add_watch(path, mask)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/watchdog/observers/inotify_c.py", line 385, in _add_watch
    Inotify._raise_error()
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/watchdog/observers/inotify_c.py", line 402, in _raise_error
    raise OSError("inotify watch limit reached")
OSError: inotify watch limit reached
2018-02-07 14:26:17,474 INFO  [galaxy.tools.toolbox.base] Parsing the tool configuration /tmp/tmpkENNF8/shed_tools_conf.xml
2018-02-07 14:26:17,475 INFO  [galaxy.tools.toolbox.base] Parsing the tool configuration /tmp/tmpkENNF8/empty_tool_conf.xml
2018-02-07 14:26:17,493 INFO  [galaxy.tools.deps.conda_util] Installing Conda, this may take several minutes.
```

**Comment by mvdbeek** [comment]
Ah, that is a very good lead!

**Comment by peterjc** [comment]
Frustratingly on my local install there are no ``watchdog`` errors nor the log entry ``Failed to load potential tool``, so I may have been too quick in jumping to conclusions here. All we have is:

``[galaxy.tools.toolbox.watcher] Watchdog library unavailable, cannot monitor tools.``

However, perhaps that in itself means ``planemo test`` won't even look at my tool?

**Comment by peterjc** [comment]
I guessed the local networked file system might have been why watchdog failed, so I re-tried that on ``/tmp`` which is a local disk:

```
$ planemo test kodoja_search.xml ; echo "$? after doing conda install watchdog, and on /tmp"
git --git-dir /home/xxx/.planemo/gx_repo fetch >/dev/null 2>&1
...
2018-02-08 09:34:25,023 INFO  [galaxy.model.migrate.check] 
2018-02-08 09:34:25,073 INFO  [galaxy.config] Install database targetting Galaxy's database configuration.
2018-02-08 09:34:25,784 ERROR [galaxy.visualization.genomes] Error reading twobit.loc: [Errno 2] No such file or directory: '/tmp/tmpkbkq7hqa/galaxy-dev/tool-data/twobit.loc'
Traceback (most recent call last):
  File "/tmp/tmpkbkq7hqa/galaxy-dev/lib/galaxy/visualization/genomes.py", line 210, in reload_genomes
    for line in open( os.path.join( self.app.config.tool_data_path, "twobit.loc" ) ):
IOError: [Errno 2] No such file or directory: '/tmp/tmpkbkq7hqa/galaxy-dev/tool-data/twobit.loc'
2018-02-08 09:34:25,801 INFO  [galaxy.jobs] Setting <handlers> default to child with id 'main'
2018-02-08 09:34:26,551 INFO  [galaxy.tools.toolbox.watcher] Watchdog library unavailable, cannot monitor tools.
2018-02-08 09:34:26,551 INFO  [galaxy.tools.toolbox.base] Parsing the tool configuration /tmp/tmpkbkq7hqa/tool_conf.xml
2018-02-08 09:34:26,569 INFO  [galaxy.tools.toolbox.base] Parsing the tool configuration /tmp/tmpkbkq7hqa/shed_tools_conf.xml
2018-02-08 09:34:26,570 INFO  [galaxy.tools.toolbox.base] Parsing the tool configuration /tmp/tmpkbkq7hqa/empty_tool_conf.xml
No handlers could be found for logger "galaxy.datatypes.display_applications.application"
2018-02-08 09:34:29,057 WARNI [galaxy.webhooks] directory not found: /tmp/tmpkbkq7hqa/galaxy-dev/lib/galaxy/util/../../.././config/plugins/webhooks/demo/config
2018-02-08 09:34:29,073 INFO  [galaxy.jobs] Handler 'main' will load all configured runner plugins
2018-02-08 09:34:29,082 INFO  [galaxy.jobs.handler] job handler stop queue started
2018-02-08 09:34:29,102 INFO  [galaxy.jobs.handler] job handler queue started
2018-02-08 09:34:33,104 INFO  [galaxy.queue_worker] Binding and starting galaxy control worker for main
/home/pc40583/.planemo/gx_venv/lib/python2.7/site-packages/sqlalchemy/sql/default_comparator.py:153: SAWarning: The IN-predicate on "request_type.id" was invoked with an empty sequence. This results in a contradiction, which nonetheless can be expensive to evaluate.  Consider alternative strategies for improved performance.
  'strategies for improved performance.' % expr)

----------------------------------------------------------------------
XML: /tmp/tmpkbkq7hqa/xunit.xml
----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
2018-02-08 09:34:35,596 INFO  [test_driver] Shutting down
2018-02-08 09:34:35,596 INFO  [test_driver] Shutting down embedded galaxy web server
2018-02-08 09:34:35,599 INFO  [test_driver] Embedded web server galaxy stopped
2018-02-08 09:34:35,599 INFO  [test_driver] Stopping application galaxy
2018-02-08 09:34:35,599 INFO  [galaxy.jobs.handler] sending stop signal to worker thread
2018-02-08 09:34:35,599 INFO  [galaxy.jobs.handler] job handler queue stopped
2018-02-08 09:34:35,599 INFO  [galaxy.jobs.runners] TaskRunner: Sending stop signal to 2 worker threads
2018-02-08 09:34:35,600 INFO  [galaxy.jobs.runners] LocalRunner: Sending stop signal to 4 worker threads
2018-02-08 09:34:35,600 INFO  [galaxy.jobs.handler] sending stop signal to worker thread
2018-02-08 09:34:35,600 INFO  [galaxy.jobs.handler] job handler stop queue stopped
2018-02-08 09:34:35,601 INFO  [test_driver] Application galaxy stopped.
2018-02-08 09:34:36,203 INFO  [galaxy.jobs.handler] sending stop signal to worker thread
2018-02-08 09:34:36,203 INFO  [galaxy.jobs.handler] job handler queue stopped
2018-02-08 09:34:36,204 INFO  [galaxy.jobs.runners] TaskRunner: Sending stop signal to 2 worker threads
2018-02-08 09:34:36,204 INFO  [galaxy.jobs.runners] LocalRunner: Sending stop signal to 4 worker threads
2018-02-08 09:34:36,204 INFO  [galaxy.jobs.handler] sending stop signal to worker thread
2018-02-08 09:34:36,204 INFO  [galaxy.jobs.handler] job handler stop queue stopped
Testing complete. HTML report is in "/tmp/kodoja_galaxy/tool_test_output.html".
No tests were executed - see Galaxy output for details.
0 after doing conda install watchdog, and on /tmp
```

So, I think that _probably_ rules out watchdog as the problem.

**Comment by peterjc** [comment]
I think this may be specific to running planemo under Python 3. While exploring the following patch was helpful:

```diff
diff --git a/planemo/cli.py b/planemo/cli.py
index 275b0c7..4756825 100644
--- a/planemo/cli.py
+++ b/planemo/cli.py
@@ -228,7 +228,7 @@ def _setup_profile_options(ctx, profile_defaults, kwds):
 
 
 @click.command(cls=PlanemoCLI, context_settings=CONTEXT_SETTINGS)
-@click.version_option(__version__)
+@click.version_option(__version__ + " - under Python " + sys.version)
 @click.option('-v', '--verbose', is_flag=True,
               help='Enables verbose mode.')
 @click.option('--config',
```

And now testing locally on Linux under a self compiled Python 2.7,

```
$ ~/bin/planemo --version && ~/bin/planemo test kodoja_search.xml
planemo, version 0.48.0.dev0 - under Python 2.7.10 (default, Sep 28 2015, 13:58:31) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-16)]
git --git-dir /home/xxx/.planemo/gx_repo fetch >/dev/null 2>&1
...
Testing complete. HTML report is in "/mnt/shared/users/xxx/repositories/kodoja_galaxy/tool_test_output.html".
There were problems with 3 test(s) - out of 3 test(s) executed. See /mnt/shared/users/xxx/repositories/kodoja_galaxy/tool_test_output.html for detailed breakdown.
kodoja_search[0]: failed
kodoja_search[1]: failed
kodoja_search[2]: failed
```

(I am expecting the three tests to fail, so this is good!)

Versus locally on Linux with planemo installed under Conda's Python 3.6.3:

```
$ /mnt/shared/scratch/synology/xxx/apps/conda/bin/planemo --version && /mnt/shared/scratch/synology/xxx/apps/conda/bin/planem test kodoja_search.xml 
planemo, version 0.48.0.dev0 - under Python 3.6.3 | packaged by conda-forge | (default, Oct  5 2017, 14:07:33) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]
git --git-dir /home/pc40583/.planemo/gx_repo fetch >/dev/null 2>&1
...
Testing complete. HTML report is in "/mnt/shared/users/pc40583/repositories/kodoja_galaxy/tool_test_output.html".
No tests were executed - see Galaxy output for details.
```

I was deliberately using Python 2.7 on TravisCI which is why I didn't suspect this earlier, but from the https://travis-ci.org/peterjc/kodoja_galaxy/jobs/338520395  log, parts of the Galaxy/planemo system are using Python 3.5.2 despite my intent:

```
...
2018-02-07 14:26:17,493 INFO  [galaxy.tools.deps.conda_util] Installing Conda, this may take several minutes.
PREFIX=/home/travis/miniconda3
installing: python-3.5.2-0 ...
installing: conda-env-2.6.0-0 ...
installing: openssl-1.0.2j-0 ...
installing: pycosat-0.6.1-py35_1 ...
installing: readline-6.2-2 ...
installing: requests-2.11.1-py35_0 ...
installing: ruamel_yaml-0.11.14-py35_0 ...
installing: sqlite-3.13.0-0 ...
installing: tk-8.5.18-0 ...
installing: xz-5.2.2-0 ...
installing: yaml-0.1.6-0 ...
installing: zlib-1.2.8-3 ...
installing: conda-4.2.12-py35_0 ...
installing: pycrypto-2.6.1-py35_4 ...
installing: pip-8.1.2-py35_0 ...
installing: wheel-0.29.0-py35_0 ...
installing: setuptools-27.2.0-py35_0 ...
Python 3.5.2 :: Continuum Analytics, Inc.
...
```

**Comment by jmchilton** [comment]
https://github.com/galaxyproject/planemo/pull/774/commits/3e46d71cc25b25d9ddb8c3def38d1adc5e98599f should fix that - sorry about this and thanks for all the debugging. @nekrut also hit the same bug I think.

I think I labelled  this project as supporting Python 3 in a sort of aspirational way and the result has been a terrible user experience as it hasn't actually really supported it. For instance we were linting against Python 3 but not testing in CI. Through the heroic efforts of @nsoranzo on #774 and #768 we are getting very close to real working Python 3 support though and the tests will hopefully be turned on today or tomorrow. Sorry about this.

**Comment by peterjc** [comment]
Thanks John - yes, the subtle Python 2 vs 3 issue you've identified does likely explain this.
