### ISSUE TITLE
running a test with --update_test_data does not work if expected file does not exist anymore

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/planemo#846]
Running planemo with `planemo t --update_test_data peptide_prophet.xml` was creating a file in `test-data` if the file was not there before. With 18.05 this changed and Galaxy is raising this error:

```
Traceback (most recent call last):
  File "/home/bag/projects/code/galaxy/test/functional/test_toolbox.py", line 88, in test_tool
    self.do_it(tool_version=tool_version, test_index=test_index)
  File "/home/bag/projects/code/galaxy/test/functional/test_toolbox.py", line 41, in do_it
    verify_tool(tool_id, self.galaxy_interactor, resource_parameters=resource_parameters, test_index=test_index, tool_version=tool_version, register_job_data=register_job_data)
  File "/home/bag/projects/code/galaxy/lib/galaxy/tools/verify/interactor.py", line 689, in verify_tool
    raise e
JobOutputsError
```

**Comment by mblue9** [comment]
I keep running into this new error with 18.05 in a slightly different context. I'd been running tests using the --no_cleanup option with planemo and letting that generate any new test files. But now I get this (not very descriptive) error if a file doesn't already exist in the test-data folder so I've started creating empty files before running planemo test with --no_cleanup now.

**Comment by mvdbeek** [comment]
I think this is because galaxy's test-data API only returns the test data path if it exists, given that it could be in a couple of different places for a running galaxy instance.
Updating the test-data only makes sense if not testing against an external galaxy, right ? So we'd have to factor that in somehow.

**Comment by suhaibMo** [comment]
Another error with Planemo testing that is similar. What is interesting its failed after. Although the lint testing works perfectly. 

```Traceback (most recent call last):
  File "/private/var/folders/0j/h_hw9q7s3d5b8l647l097rjh261_3j/T/tmp2SFVPK/galaxy-dev/test/functional/test_toolbox.py", line 88, in test_tool
    self.do_it(tool_version=tool_version, test_index=test_index)
  File "/private/var/folders/0j/h_hw9q7s3d5b8l647l097rjh261_3j/T/tmp2SFVPK/galaxy-dev/test/functional/test_toolbox.py", line 41, in do_it
    verify_tool(tool_id, self.galaxy_interactor, resource_parameters=resource_parameters, test_index=test_index, tool_version=tool_version, register_job_data=register_job_data)
  File "/private/var/folders/0j/h_hw9q7s3d5b8l647l097rjh261_3j/T/tmp2SFVPK/galaxy-dev/lib/galaxy/tools/verify/interactor.py", line 689, in verify_tool
    raise e
JobOutputsError

----------------------------------------------------------------------
XML: /private/var/folders/0j/h_hw9q7s3d5b8l647l097rjh261_3j/T/tmp2SFVPK/xunit.xml
----------------------------------------------------------------------
Ran 1 test in 66.979s```
