### ISSUE TITLE
pip install planemo fails in python 3.7

### ISSUE THREAD

**Issue by zfrenchee** [galaxyproject/planemo#863]
```
...
Collecting ruamel.yaml<0.15,>=0.12.4 (from cwltool==1.0.20180508202931->planemo)
  Using cached https://files.pythonhosted.org/packages/cf/86/7ef6c24317e20e6cef0eab407520d49f3d3836e454d5377bdcbcf03d385c/ruamel.yaml-0.14.12.tar.gz
    Complete output from command python setup.py egg_info:
    /var/folders/0w/fzyy4qz93l56_bh1jyn3vgp00000gn/T/tmp_ruamel_zm7ie1ka/test_ruamel_yaml.c:6:8: warning: explicitly assigning value of variable of type 'yaml_parser_t' (aka 'struct yaml_parser_s') to itself [-Wself-assign]
    parser = parser;  /* prevent warning */
    ~~~~~~ ^ ~~~~~~
    /var/folders/0w/fzyy4qz93l56_bh1jyn3vgp00000gn/T/tmp_ruamel_zm7ie1ka/test_ruamel_yaml.c:6:10: warning: variable 'parser' is uninitialized when used here [-Wuninitialized]
    parser = parser;  /* prevent warning */
             ^~~~~~
    /var/folders/0w/fzyy4qz93l56_bh1jyn3vgp00000gn/T/tmp_ruamel_zm7ie1ka/test_ruamel_yaml.c:5:1: note: variable 'parser' is declared here
    yaml_parser_t parser;
    ^
    2 warnings generated.
    Warning: 'keywords' should be a list, got type 'NoneType'
    sys.argv ['-c', 'egg_info', '--egg-base', 'pip-egg-info']
    test compiling test_ruamel_yaml
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/0w/fzyy4qz93l56_bh1jyn3vgp00000gn/T/pip-install-2oemz2wi/ruamel.yaml/setup.py", line 858, in <module>
        main()
      File "/private/var/folders/0w/fzyy4qz93l56_bh1jyn3vgp00000gn/T/pip-install-2oemz2wi/ruamel.yaml/setup.py", line 847, in main
        setup(**kw)
      File "/Users/alex/Documents/galaxy-neurolincs/venv/lib/python3.7/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/Users/alex/Documents/galaxy-neurolincs/venv/lib/python3.7/site-packages/setuptools/dist.py", line 372, in __init__
        _Distribution.__init__(self, attrs)
      File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 267, in __init__
        getattr(self.metadata, "set_" + key)(val)
      File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 1203, in set_keywords
        self.keywords = _ensure_list(value, 'keywords')
      File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 40, in _ensure_list
        value = list(value)
    TypeError: 'NoneType' object is not iterable

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/0w/fzyy4qz93l56_bh1jyn3vgp00000gn/T/pip-install-2oemz2wi/ruamel.yaml/
```

**Comment by nsoranzo** [comment]
We need to update Planemo `requirements.txt` to depend on a cwltool release which includes https://github.com/common-workflow-language/cwltool/pull/831 .
