### ISSUE TITLE
better exception handling for a non-existent test-file

### ISSUE THREAD

**Issue by mmiladi** [galaxyproject/planemo#881]
`planemo test` error report is very cryptic, in the cases where the input or putput files defined in the tool xml file are missing in the test-directory.

A better error report message would be great.

* case input(param) test file is missing:
```
Traceback (most recent call last):
  File "/tmp/tmpiiE_At/galaxy-dev/test/functional/test_toolbox.py", line 88, in test_tool
    self.do_it(tool_version=tool_version, test_index=test_index)
  File "/tmp/tmpiiE_At/galaxy-dev/test/functional/test_toolbox.py", line 41, in do_it
    verify_tool(tool_id, self.galaxy_interactor, resource_parameters=resource_parameters, test_index=test_index, tool_version=tool_version, register_j
ob_data=register_job_data)
  File "/tmp/tmpiiE_At/galaxy-dev/lib/galaxy/tools/verify/interactor.py", line 653, in verify_tool
    stage_data_in_history(galaxy_interactor, tool_id, testdef.test_data(), test_history)
  File "/tmp/tmpiiE_At/galaxy-dev/lib/galaxy/tools/verify/interactor.py", line 59, in stage_data_in_history
    upload_wait = galaxy_interactor.stage_data_async(test_data, history, tool_id)
  File "/tmp/tmpiiE_At/galaxy-dev/lib/galaxy/tools/verify/interactor.py", line 267, in stage_data_async
    file_name = self.test_data_path(tool_id, fname)
  File "/tmp/tmpiiE_At/galaxy-dev/lib/galaxy/tools/verify/interactor.py", line 232, in test_data_path
    assert response.status_code == 200
AssertionError
```

* case output test file is missing:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/tmp/tmpTndn4N/galaxy-dev/test/functional/test_toolbox.py", line 88, in test_tool
    self.do_it(tool_version=tool_version, test_index=test_index)
  File "/tmp/tmpTndn4N/galaxy-dev/test/functional/test_toolbox.py", line 41, in do_it
    verify_tool(tool_id, self.galaxy_interactor, resource_parameters=resource_parameters, test_index=test_index, tool_version=tool_version, register_job_data=register_job_data)
  File "/tmp/tmpTndn4N/galaxy-dev/lib/galaxy/tools/verify/interactor.py", line 689, in verify_tool
    raise e
JobOutputsError
```

**Comment by mvdbeek** [comment]
I think that's a lot better now with https://github.com/mvdbeek/galaxy/blob/2c8e5b2e266e8eec5ce7ed76080f01b7462d27eb/lib/galaxy/tool_util/verify/interactor.py#L288
