### ISSUE TITLE
"planemo test" can't successfully start

### ISSUE THREAD

**Issue by crashfrog** [galaxyproject/planemo#884]
CWL loading during tests causes unrecoverable `NoneType` errors

`$ planemo t --install_galaxy --galaxy_branch release_18.05`

	2018-10-30 17:41:48,741 INFO  [galaxy.tools.parser.factory] Loading CWL tool - this is experimental - tool likely will not function in future at least in same way.
	2018-10-30 17:41:48,741 ERROR [galaxy.tools.toolbox.base] Failed to load potential tool /usr/local/lib/python2.7/dist-packages/schema_salad/tests/test_schema/test14.cwl.
	Traceback (most recent call last):
	  File "/tmp/tmpxwyuS7/galaxy-dev/lib/galaxy/tools/toolbox/base.py", line 719, in quick_load
		tool = self.load_tool(tool_file)
	  File "/tmp/tmpxwyuS7/galaxy-dev/lib/galaxy/tools/toolbox/base.py", line 754, in load_tool
		tool = self.create_tool(config_file=config_file, repository_id=repository_id, guid=guid, **kwds)
	  File "/tmp/tmpxwyuS7/galaxy-dev/lib/galaxy/tools/__init__.py", line 271, in create_tool
		return self._create_tool_from_source(tool_source, config_file=config_file, **kwds)
	  File "/tmp/tmpxwyuS7/galaxy-dev/lib/galaxy/tools/__init__.py", line 274, in _create_tool_from_source
		return create_tool_from_source(self.app, tool_source, **kwds)
	  File "/tmp/tmpxwyuS7/galaxy-dev/lib/galaxy/tools/__init__.py", line 219, in create_tool_from_source
		tool = ToolClass(config_file, tool_source, app, **kwds)
	TypeError: 'NoneType' object is not callable
	2018-10-30 17:41:48,746 INFO  [galaxy.tools.parser.factory] Loading CWL tool - this is experimental - tool likely will not function in future at least in same way.
	2018-10-30 17:41:48,747 ERROR [galaxy.tools.toolbox.base] Failed to load potential tool /usr/local/lib/python2.7/dist-packages/schema_salad/tests/test_schema/test17.cwl.
	Traceback (most recent call last):
	  File "/tmp/tmpxwyuS7/galaxy-dev/lib/galaxy/tools/toolbox/base.py", line 719, in quick_load
		tool = self.load_tool(tool_file)
	  File "/tmp/tmpxwyuS7/galaxy-dev/lib/galaxy/tools/toolbox/base.py", line 754, in load_tool
		tool = self.create_tool(config_file=config_file, repository_id=repository_id, guid=guid, **kwds)
	  File "/tmp/tmpxwyuS7/galaxy-dev/lib/galaxy/tools/__init__.py", line 271, in create_tool
		return self._create_tool_from_source(tool_source, config_file=config_file, **kwds)
	  File "/tmp/tmpxwyuS7/galaxy-dev/lib/galaxy/tools/__init__.py", line 274, in _create_tool_from_source
		return create_tool_from_source(self.app, tool_source, **kwds)
	  File "/tmp/tmpxwyuS7/galaxy-dev/lib/galaxy/tools/__init__.py", line 219, in create_tool_from_source
		tool = ToolClass(config_file, tool_source, app, **kwds)
	TypeError: 'NoneType' object is not callable
	2018-10-30 17:41:48,762 INFO  [galaxy.tools.parser.factory] Loading CWL tool - this is experimental - tool likely will not function in future at least in same way.
	2018-10-30 17:41:48,762 ERROR [galaxy.tools.toolbox.base] Failed to load potential tool /usr/local/lib/python2.7/dist-packages/schema_salad/tests/test_schema/test18.cwl.
	Traceback (most recent call last):
	  File "/tmp/tmpxwyuS7/galaxy-dev/lib/galaxy/tools/toolbox/base.py", line 719, in quick_load
		tool = self.load_tool(tool_file)
	  File "/tmp/tmpxwyuS7/galaxy-dev/lib/galaxy/tools/toolbox/base.py", line 754, in load_tool
		tool = self.create_tool(config_file=config_file, repository_id=repository_id, guid=guid, **kwds)
	  File "/tmp/tmpxwyuS7/galaxy-dev/lib/galaxy/tools/__init__.py", line 271, in create_tool
		return self._create_tool_from_source(tool_source, config_file=config_file, **kwds)
	  File "/tmp/tmpxwyuS7/galaxy-dev/lib/galaxy/tools/__init__.py", line 274, in _create_tool_from_source
		return create_tool_from_source(self.app, tool_source, **kwds)
	  File "/tmp/tmpxwyuS7/galaxy-dev/lib/galaxy/tools/__init__.py", line 219, in create_tool_from_source
		tool = ToolClass(config_file, tool_source, app, **kwds)
	TypeError: 'NoneType' object is not callable

**Comment by crashfrog** [comment]
Oops, sorry, was running in the wrong directory.
