### ISSUE TITLE
Planemo lint misses reserved parameter names

### ISSUE THREAD

**Issue by erasche** [galaxyproject/planemo#904]
E.g. `sleep` is a non-functional parameter name and the tool will crash if it is used. Would be nice to enumerate all reserved names and have planemo lint catch them.

**Comment by erasche** [comment]
It's not the python keywords:

```
galaxy.jobs.handler INFO 2018-12-18 11:54:19,925 [p:604141,w:1,m:0] [JobHandlerQueue.monitor_thread] (36) Job dispatched
root INFO 2018-12-18 11:54:19,979 [p:604141,w:1,m:0] [CondorRunner.work_thread-1]  The following keys are members of the Template class and will result in NameMapper collisions!
root INFO 2018-12-18 11:54:19,979 [p:604141,w:1,m:0] [CondorRunner.work_thread-1]   > sleep
root INFO 2018-12-18 11:54:19,979 [p:604141,w:1,m:0] [CondorRunner.work_thread-1]  Please change the key's name or use the compiler setting "prioritizeSearchListOverSelf=True" to prevent the NameMapper from using
root INFO 2018-12-18 11:54:19,979 [p:604141,w:1,m:0] [CondorRunner.work_thread-1]  the Template member in place of your searchList variable
galaxy.jobs.runners ERROR 2018-12-18 11:54:19,998 [p:604141,w:1,m:0] [CondorRunner.work_thread-1] (36) Failure preparing job
Traceback (most recent call last):
  File "lib/galaxy/jobs/runners/__init__.py", line 187, in prepare_job
    job_wrapper.prepare()
  File "lib/galaxy/jobs/__init__.py", line 875, in prepare
    self.command_line, self.extra_filenames, self.environment_variables = tool_evaluator.build()
  File "lib/galaxy/tools/evaluation.py", line 455, in build
    raise e
TypeError: sleep() takes exactly 2 arguments (1 given)
```

We can generate the full list with

```console
$ python -c 'from Cheetah.Template import Template as t
for x in sorted(list(t.Reserved_SearchList)): print(x)'
```

which outputs things like

```
...
_normalizePreprocessorSettings
_preprocessSource
_updateSettingsWithPreprocessTokens
application
compile
errorCatcher
generatedClassCode
generatedModuleCode
getCacheRegion
getCacheRegions
getFileContents
getVar
hasVar
i18n
refreshCache
request
respond
runAsMainProgram
searchList
serverSidePath
session
shutdown
sleep
subclass
transaction
varExists
...
```

So should be easy enough to implement, just import the reserved list + compare

**Comment by peterjc** [comment]
Ah, Cheetah reserved words - that makes sense given how the parameter names are used in the command template.
