### ISSUE TITLE
planemo dependencies broken in pip

### ISSUE THREAD

**Issue by ppouchin** [galaxyproject/planemo#911]
Hi,

Installing planemo through pip in a brand new virtualenv yields:
```
ImportError: No module named OpenSSL.SSL
```

It seems pip did not install the same dependencies in the new environment as it did previously...

**Comment by nsoranzo** [comment]
Thanks for reporting the issue!

The full traceback makes clear that the issue is coming from requests-toolbelt, one of the Planemo dependencies:
```
Traceback (most recent call last):
  File "/usr/users/ga002/soranzon/software/nsoranzo_planemo/testvenv/bin/planemo", line 6, in <module>
    from planemo.cli import planemo
  File "/usr/users/ga002/soranzon/software/nsoranzo_planemo/testvenv/local/lib/python2.7/site-packages/planemo/cli.py", line 14, in <module>
    from planemo.galaxy import profiles
  File "/usr/users/ga002/soranzon/software/nsoranzo_planemo/testvenv/local/lib/python2.7/site-packages/planemo/galaxy/__init__.py", line 5, in <module>
    from .config import galaxy_config
  File "/usr/users/ga002/soranzon/software/nsoranzo_planemo/testvenv/local/lib/python2.7/site-packages/planemo/galaxy/config.py", line 51, in <module>
    from .workflows import (
  File "/usr/users/ga002/soranzon/software/nsoranzo_planemo/testvenv/local/lib/python2.7/site-packages/planemo/galaxy/workflows.py", line 7, in <module>
    from bioblend.galaxy.client import Client
  File "/usr/users/ga002/soranzon/software/nsoranzo_planemo/testvenv/local/lib/python2.7/site-packages/bioblend/galaxy/__init__.py", line 9, in <module>
    from bioblend.galaxyclient import GalaxyClient
  File "/usr/users/ga002/soranzon/software/nsoranzo_planemo/testvenv/local/lib/python2.7/site-packages/bioblend/galaxyclient.py", line 13, in <module>
    from requests_toolbelt import MultipartEncoder
  File "/usr/users/ga002/soranzon/software/nsoranzo_planemo/testvenv/local/lib/python2.7/site-packages/requests_toolbelt/__init__.py", line 12, in <module>
    from .adapters import SSLAdapter, SourceAddressAdapter
  File "/usr/users/ga002/soranzon/software/nsoranzo_planemo/testvenv/local/lib/python2.7/site-packages/requests_toolbelt/adapters/__init__.py", line 12, in <module>
    from .ssl import SSLAdapter
  File "/usr/users/ga002/soranzon/software/nsoranzo_planemo/testvenv/local/lib/python2.7/site-packages/requests_toolbelt/adapters/ssl.py", line 16, in <module>
    from .._compat import poolmanager
  File "/usr/users/ga002/soranzon/software/nsoranzo_planemo/testvenv/local/lib/python2.7/site-packages/requests_toolbelt/_compat.py", line 59, in <module>
    from urllib3.contrib.pyopenssl import PyOpenSSLContext
  File "/usr/users/ga002/soranzon/software/nsoranzo_planemo/testvenv/local/lib/python2.7/site-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
ImportError: No module named OpenSSL.SSL
```

In fact, the cause is https://github.com/requests/toolbelt/issues/241 , introduced with requests-toolbelt 0.9.0 . You can easily workaround the issue by installing the previous version in the virtualenv with:
```
$ pip install 'requests-toolbelt==0.8.0'
```

**Comment by nsoranzo** [comment]
Added workaround in the `master` branch of BioBlend: https://github.com/galaxyproject/bioblend/commit/b2b79f7688cf275495c8c20201a80c2587e1e302

**Comment by nsoranzo** [comment]
requests-toolbelt 0.9.1 has been released, which fixes the issue for future installs.
