### ISSUE TITLE
planemo test can't handle same tool used twice in a workflow

### ISSUE THREAD

**Issue by davidchristiany** [galaxyproject/planemo#939]
I am using planemo test on a galaxy workflow with this command:
```
planemo test --galaxy_url <url> --galaxy_user_key <user_key> --no_shed_install --engine external_galaxy workflow.ga
```

It is working when my workflow only use each tool once:
```
All 1 test(s) executed passed.
workflow_frogs.ga_0: passed
```

But when I am using the same tool twice, I get an error:

```
galaxy.tools.verify INFO: ## files diff on '/home/dchristiany/proteore_project/ProteoRE/workflows/expected/Filters_excluded.tsv' and '/tmp/tmpp1xH50Filters_excluded.tsv': lines_diff = 0, found diff = 785`
`galaxy.tools.verify INFO: ## files diff on '/home/dchristiany/proteore_project/ProteoRE/workflows/expected/Filters_sequences.fasta' and '/tmp/tmp4lsKOhFilters_sequences.fasta': lines_diff = 0, found diff = 86`
`galaxy.tools.verify INFO: ## files diff on '/home/dchristiany/proteore_project/ProteoRE/workflows/expected/Filters_report.html' and '/tmp/tmpLbQaXhFilters_report.html': lines_diff = 0, found diff = 8`
`Traceback (most recent call last):
  File "/home/dchristiany/.venv/bin/planemo", line 10, in <module>
    sys.exit(planemo())
  File "/home/dchristiany/.venv/local/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/dchristiany/.venv/local/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/dchristiany/.venv/local/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dchristiany/.venv/local/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dchristiany/.venv/local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/dchristiany/.venv/local/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/dchristiany/.venv/local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/dchristiany/.venv/local/lib/python2.7/site-packages/planemo/cli.py", line 195, in handle_blended_options
    return f(*args, **kwds)
  File "/home/dchristiany/.venv/local/lib/python2.7/site-packages/planemo/commands/cmd_test.py", line 87, in cli
    test_data = engine.test(runnables)
  File "/home/dchristiany/.venv/local/lib/python2.7/site-packages/planemo/engine/interface.py", line 82, in test
    test_case_data = test_case.structured_test_data(run_response)
  File "/home/dchristiany/.venv/local/lib/python2.7/site-packages/planemo/runnable.py", line 256, in structured_test_data
    self._check_output(output_id, output_value, output_test)
  File "/home/dchristiany/.venv/local/lib/python2.7/site-packages/planemo/runnable.py", line 314, in _check_output
    output_test,
  File "/home/dchristiany/.venv/local/lib/python2.7/site-packages/planemo/test/_check_output.py", line 43, in check_output
    verify_extra_files=None,
  File "/home/dchristiany/.venv/local/lib/python2.7/site-packages/galaxy/tools/verify/__init__.py", line 133, in verify
    errmsg += str(err)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 848: ordinal not in range(128)`
```

From what I understand, output files are not compared to the right expected files probably due to the same output_name from the same tool used twice even when I put different labels on ouput_names.

I dont understand why I also get an '\xa0' error (it is supposed to be non breakable space),it only occurs when I am using the same tool twice in my workflow.

Does anyone know how to fix that ?

**Comment by mvdbeek** [comment]
The diff in your test output contains `u'\xa0'`, and then it'll just fail with when you do `str(u'\xa0')` on python 2.
We'll have a fix shortly, but in the meantime you could edit line 133 of /home/dchristiany/.venv/local/lib/python2.7/site-packages/galaxy/tools/verify/__init__.py and change `errmsg += str(err)` to `errmsg += err`

**Comment by davidchristiany** [comment]
Thanks for the quick answer.
I tried and got this:

`galaxy.tools.verify INFO: ## files diff on '/home/dchristiany/proteore_project/ProteoRE/workflows/expected/Filters_excluded.tsv' and '/tmp/tmp4UzBmwFilters_excluded.tsv': lines_diff = 0, found diff = 785`
`Traceback (most recent call last):
  File "/home/dchristiany/.venv/bin/planemo", line 10, in <module>
    sys.exit(planemo())
  File "/home/dchristiany/.venv/local/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/dchristiany/.venv/local/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/dchristiany/.venv/local/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dchristiany/.venv/local/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dchristiany/.venv/local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/dchristiany/.venv/local/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/dchristiany/.venv/local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/dchristiany/.venv/local/lib/python2.7/site-packages/planemo/cli.py", line 195, in handle_blended_options
    return f(*args, **kwds)
  File "/home/dchristiany/.venv/local/lib/python2.7/site-packages/planemo/commands/cmd_test.py", line 87, in cli
    test_data = engine.test(runnables)
  File "/home/dchristiany/.venv/local/lib/python2.7/site-packages/planemo/engine/interface.py", line 82, in test
    test_case_data = test_case.structured_test_data(run_response)
  File "/home/dchristiany/.venv/local/lib/python2.7/site-packages/planemo/runnable.py", line 256, in structured_test_data
    self._check_output(output_id, output_value, output_test)
  File "/home/dchristiany/.venv/local/lib/python2.7/site-packages/planemo/runnable.py", line 314, in _check_output
    output_test,
  File "/home/dchristiany/.venv/local/lib/python2.7/site-packages/planemo/test/_check_output.py", line 43, in check_output
    verify_extra_files=None,
  File "/home/dchristiany/.venv/local/lib/python2.7/site-packages/galaxy/tools/verify/__init__.py", line 133, in verify
    errmsg += err
TypeError: coercing to Unicode: need string or buffer, exceptions.AssertionError found`

I checked all outputs and I almost sure outputs files from the second use of the same tool is compared to the expected files of the first use of the tool. I used different labels but it might be due to output_names. That's why I get 785 lines_diff (the entire file).

I tried planemo test on the same workflow but without checking output files from the first use of the tool used twice and it worked. There is definitely something's going wrong when the same tool is called more than once in a workflow.

**Comment by mvdbeek** [comment]
That's possible, but let's fix one bug after the other :).

**Comment by mvdbeek** [comment]
Could you check with the changes in https://github.com/mvdbeek/galaxy/commit/a663b45d1caa2b866b1bdcdf3dcc95d4afac5e21 ?
I'll have a look at what might be going on with the other issue.

**Comment by davidchristiany** [comment]
with the changes in mvdbeek/galaxy@a663b45, I still get the same error:

`galaxy.tools.verify INFO: ## files diff on '/home/dchristiany/FROGS-wrappers/workflow_frogs/expected/Filters_excluded.tsv' and '/tmp/tmpJcbXHiFilters_excluded.tsv': lines_diff = 0, found diff = 785`
`galaxy.tools.verify INFO: ## files diff on '/home/dchristiany/FROGS-wrappers/workflow_frogs/expected/Filters_sequences.fasta' and '/tmp/tmpFgeZouFilters_sequences.fasta': lines_diff = 0, found diff = 86`
`galaxy.tools.verify INFO: ## files diff on '/home/dchristiany/FROGS-wrappers/workflow_frogs/expected/Filters_report.html' and '/tmp/tmpoVNh_2Filters_report.html': lines_diff = 0, found diff = 8`
`Traceback (most recent call last):
  File "/home/dchristiany/.venv/bin/planemo", line 10, in <module>
    sys.exit(planemo())
  File "/home/dchristiany/.venv/local/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/dchristiany/.venv/local/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/dchristiany/.venv/local/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dchristiany/.venv/local/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dchristiany/.venv/local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/dchristiany/.venv/local/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/dchristiany/.venv/local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/dchristiany/.venv/local/lib/python2.7/site-packages/planemo/cli.py", line 195, in handle_blended_options
    return f(*args, **kwds)
  File "/home/dchristiany/.venv/local/lib/python2.7/site-packages/planemo/commands/cmd_test.py", line 87, in cli
    test_data = engine.test(runnables)
  File "/home/dchristiany/.venv/local/lib/python2.7/site-packages/planemo/engine/interface.py", line 82, in test
    test_case_data = test_case.structured_test_data(run_response)
  File "/home/dchristiany/.venv/local/lib/python2.7/site-packages/planemo/runnable.py", line 256, in structured_test_data
    self._check_output(output_id, output_value, output_test)
  File "/home/dchristiany/.venv/local/lib/python2.7/site-packages/planemo/runnable.py", line 314, in _check_output
    output_test,
  File "/home/dchristiany/.venv/local/lib/python2.7/site-packages/planemo/test/_check_output.py", line 46, in check_output
    problems.append(str(e))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 1075: ordinal not in range(128)`

**Comment by mvdbeek** [comment]
this isn't the same error though

**Comment by nsoranzo** [comment]
I think that:
```diff
diff --git a/planemo/test/_check_output.py b/planemo/test/_check_output.py
index 90d2c3c..6e631db 100644
--- a/planemo/test/_check_output.py
+++ b/planemo/test/_check_output.py
@@ -3,6 +3,7 @@
 import os
 
 from galaxy.tools.verify import verify
+from galaxy.util import unicodify
 
 
 def check_output(runnable, output_properties, test_properties, **kwds):
@@ -43,7 +44,7 @@ def check_output(runnable, output_properties, test_properties, **kwds):
             verify_extra_files=None,
         )
     except AssertionError as e:
-        problems.append(str(e))
+        problems.append(unicodify(e))
 
     return problems
 
```
should fix the new issue, with unicodify modified as in https://github.com/galaxyproject/galaxy/pull/8221 .
