### ISSUE TITLE
Planemo test + Python 3 errors

### ISSUE THREAD

**Issue by selten** [galaxyproject/planemo#955]
Not sure if this belongs here or in https://github.com/galaxyproject/galaxy.

I run 
```bash
planemo t --galaxy_root=[Root Folder] --conda_dependency_resolution --test_output ./tool_test.html --job_output_files job_output/ --conda_ensure_channels [Conda Channels]
``` in a custom container that uses Galaxy 19.09 with Python 3 (planemo is setup inside this container).    

The following errors pop up when running the test:
Uploading test data:
```python
2019-09-11 18:10:22,233 ERROR [galaxy.tools.toolbox.base] Error reading tool from path: data_source/upload.xml
Traceback (most recent call last):
  File "/galaxy/galaxy/lib/galaxy/tools/toolbox/base.py", line 632, in _load_tool_tag_set
    tool = self.load_tool(concrete_path, use_cached=False)
  File "/galaxy/galaxy/lib/galaxy/tools/toolbox/base.py", line 816, in load_tool
    self.watch_tool(tool)
  File "/galaxy/galaxy/lib/galaxy/tools/toolbox/base.py", line 824, in watch_tool
    self._tool_watcher.watch_file(tool.config_file, tool.id)
  File "/galaxy/galaxy/lib/galaxy/tools/toolbox/watcher.py", line 174, in watch_file
    self.monitor(tool_dir)
  File "/galaxy/galaxy/lib/galaxy/tools/toolbox/watcher.py", line 166, in monitor
    self.observer.schedule(self.event_handler, dir, recursive=False)
AttributeError: 'NoneType' object has no attribute 'schedule'
```

Running tool:
```python
2019-09-11 18:10:22,238 ERROR [galaxy.tools.toolbox.base] Failed to load potential tool /builds/galaxy/tools/TOOL/TOOL.xml.
Traceback (most recent call last):
  File "/galaxy/galaxy/lib/galaxy/tools/toolbox/base.py", line 769, in quick_load
    tool = self.load_tool(tool_file)
  File "/galaxy/galaxy/lib/galaxy/tools/toolbox/base.py", line 816, in load_tool
    self.watch_tool(tool)
  File "/galaxy/galaxy/lib/galaxy/tools/toolbox/base.py", line 824, in watch_tool
    self._tool_watcher.watch_file(tool.config_file, tool.id)
  File "/galaxy/galaxy/lib/galaxy/tools/toolbox/watcher.py", line 174, in watch_file
    self.monitor(tool_dir)
  File "/galaxy/galaxy/lib/galaxy/tools/toolbox/watcher.py", line 166, in monitor
    self.observer.schedule(self.event_handler, dir, recursive=False)
AttributeError: 'NoneType' object has no attribute 'schedule'
```

Afterwards this pops up (this isn't a data manager):
```
2019-09-11 18:10:22,309 ERROR [galaxy.tools.data_manager.manager] Error loading data_manager ''NoneType' object has no attribute 'schedule'':
<data_manager id="test_data_manager" tool_file="data_manager.xml" version="1.0"><data_table name="testbeta"><output><column name="value" /><column name="path" output_ref="out_file"><move relativize_symlinks="True" type="directory"><target base="${GALAXY_DATA_MANAGER_DATA_PATH}">testbeta/${value}</target></move><value_translation>${GALAXY_DATA_MANAGER_DATA_PATH}/testbeta/${value}/${path}</value_translation><value_translation type="function">abspath</value_translation></column></output></data_table></data_manager>
```

And furthermore:
```
2019-09-11 18:10:22,396 ERROR [galaxy.datatypes.registry] Error loading converter (/galaxy/galaxy/lib/galaxy/datatypes/converters)
Traceback (most recent call last):
  File "/galaxy/galaxy/lib/galaxy/datatypes/registry.py", line 614, in load_datatype_converters
    converter = toolbox.load_tool(config_path, use_cached=use_cached)
  File "/galaxy/galaxy/lib/galaxy/tools/toolbox/base.py", line 816, in load_tool
    self.watch_tool(tool)
  File "/galaxy/galaxy/lib/galaxy/tools/toolbox/base.py", line 824, in watch_tool
    self._tool_watcher.watch_file(tool.config_file, tool.id)
  File "/galaxy/galaxy/lib/galaxy/tools/toolbox/watcher.py", line 174, in watch_file
    self.monitor(tool_dir)
  File "/galaxy/galaxy/lib/galaxy/tools/toolbox/watcher.py", line 166, in monitor
    self.observer.schedule(self.event_handler, dir, recursive=False)
AttributeError: 'NoneType' object has no attribute 'schedule'
```

**Comment by nsoranzo** [comment]
This may be due to https://github.com/galaxyproject/galaxy/pull/8078 . Can you try to point planemo to a Galaxy root at release 19.05 ?

Ping @mvdbeek
