### ISSUE TITLE
Exception : Cannot locate JSON report [..] for tests - required to build planemo report and summarize tests.

### ISSUE THREAD

**Issue by Delphine-L** [galaxyproject/planemo#967]
I am trying to test a set of tools  with planemo test with the following command  (planemo, version 0.61.0) : 
```  planemo test --galaxy_root ~/Library/galaxy/ --no_cleanup --test_output_xunit ~/ ```

And receive immediately the following error : 
``` Testing using galaxy_root /Users/delphinel/Library/galaxy
Testing tools with command [cd /Users/delphinel/Library/galaxy && if [ -d .venv ] || [ -f dist-eggs.ini ]; then GALAXY_VIRTUAL_ENV=.venv; else GALAXY_VIRTUAL_ENV=/Users/delphinel/.planemo/gx_venv; fi && export GALAXY_VIRTUAL_ENV && if [ ! -e "$GALAXY_VIRTUAL_ENV" ]; then /Library/miniconda3/envs/planemo/bin/virtualenv -p /usr/bin/python2.7 $GALAXY_VIRTUAL_ENV; fi && if [ -e "$GALAXY_VIRTUAL_ENV" ]; then . "$GALAXY_VIRTUAL_ENV"/bin/activate; fi && sh run_tests.sh $COMMON_STARTUP_ARGS --report_file /Users/delphinel/Documents/tools-iuc/tools/transit/tool_test_output.html --xunit_report_file /Users/delphinel --structured_data_report_file /Users/delphinel/Documents/tools-iuc/tools/transit/tool_test_output.json functional.test_toolbox]
sh: run_tests.sh: No such file or directory
Cannot locate JSON report [/Users/delphinel/Documents/tools-iuc/tools/transit/tool_test_output.json] for tests - required to build planemo report and summarize tests.
Traceback (most recent call last):
  File "/Library/miniconda3/envs/planemo/bin/planemo", line 10, in <module>
    sys.exit(planemo())
  File "/Library/miniconda3/envs/planemo/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Library/miniconda3/envs/planemo/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Library/miniconda3/envs/planemo/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/miniconda3/envs/planemo/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/miniconda3/envs/planemo/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Library/miniconda3/envs/planemo/lib/python3.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/Library/miniconda3/envs/planemo/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Library/miniconda3/envs/planemo/lib/python3.7/site-packages/planemo/cli.py", line 189, in handle_blended_options
    return f(*args, **kwds)
  File "/Library/miniconda3/envs/planemo/lib/python3.7/site-packages/planemo/commands/cmd_test.py", line 93, in cli
    return_value = run_in_config(ctx, config, **kwds)
  File "/Library/miniconda3/envs/planemo/lib/python3.7/site-packages/planemo/galaxy/test/actions.py", line 102, in run_in_config
    _check_test_outputs(xunit_report_file_tracker, structured_report_file_tracker)
  File "/Library/miniconda3/envs/planemo/lib/python3.7/site-packages/planemo/galaxy/test/actions.py", line 288, in _check_test_outputs
    raise Exception(message)
Exception: Cannot locate JSON report [/Users/delphinel/Documents/tools-iuc/tools/transit/tool_test_output.json] for tests - required to build planemo report and summarize tests. ```

**Comment by nsoranzo** [comment]
Actually the error is on the second line:
```
sh: run_tests.sh: No such file or directory
```

Is the `run_tests.sh` file present in `~/Library/galaxy/` ?

**Comment by martenson** [comment]
@nsoranzo that whole folder was broken, but the same error has been reported when galaxy_root was not specified

I cloned new galaxy to a different folder, and installed planemo under python2 and now it seems to work. I think that system is not in a pristine shape wrt python & conda.

**Comment by nsoranzo** [comment]
> but the same error has been reported when galaxy_root was not specified

Which of the 2 error messages?

> I cloned new galaxy to a different folder, and installed planemo under python2 and now it seems to work. I think that system is not in a pristine shape wrt python & conda.

There are too many ways to install Planemo and Galaxy with Python 2 vs 3 in virtualenv vs conda for various Galaxy releases. Happy to investigate a reproducible issue, otherwise I fear it's a lost cause (especially if it's under macOS, which I don't have access to).

**Comment by martenson** [comment]
@nsoranzo I agree
